In [1]:
import pandas as pd
from pathlib import Path
from tabulate import tabulate
from openai import OpenAI

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / ".git").exists() and PROJECT_ROOT != PROJECT_ROOT.parent:
    PROJECT_ROOT = PROJECT_ROOT.parent

df = pd.read_json(PROJECT_ROOT / "datasets" / "ViNumQA" / "test.json")
df.sample(n=5)

,pre_text,table,post_text,id,qa
7,[đánh giá quý 1: phương pháp quản trị thận trọ...,"[[Năm tài chính (31/12), 12/16, 12/17, 12/18, ...",[.],masvn/2020/2020053-200427_VCB_1Q20_review_vn/p...,{'question': 'tốc độ tăng trưởng lợi nhuận sau...
230,"[tính đến cuối 2019, ppc có 1.284 tỷ đồng nợ n...","[[, 2016, 2017, 2018, 2019], [Tỷ suất lợi nhuậ...",[.],masvn/2020/2020040-PPC_Báocáol_n__u-05022020/p...,{'question': 'tổng lượng tiền mặt và các khoản...
282,[tái cơ cấu nợ có vấn đề (tdr) tdr là một khoả...,"[[tính bằng triệu đô la, ngày 31 tháng 12 năm ...",[( a ) theo hướng dẫn của cơ quan quản lý ban ...,PNC/2012/page_174.pdf-5,"{'question': 'Trong năm 2012, tỷ lệ phần trăm ..."
383,[thỏa thuận tín dụng ngân hàng tuần hoàn đã ca...,"[[đơn vị triệu đô la, 2010, 2011, 2012, 2013, ...",[(a) tổng nợ chỉ bao gồm các khoản thanh toán ...,IP/2009/page_45.pdf-2,{'question': 'Tỷ lệ phần trăm của các nghĩa vụ...
227,[thông tin bổ sung về các hoạt động sản xuất d...,"[[(tính bằng triệu), 2004, 2003, 2002], [doanh...",[.],MRO/2004/page_125.pdf-2,{'question': 'Tỷ lệ giảm chi phí phát triển tr...

In [2]:
len(df)

497

In [3]:
def formatting_pre_text(sample):
    return "\n".join(sample["pre_text"])

def formatting_table(sample):
    return tabulate(sample["table"][1:], headers=sample["table"][0], tablefmt="github")

def formatting_post_text(sample):
    return "\n".join(sample["post_text"])

def processing_input_question(sample):
    return sample["qa"]["question"]

def processing_program_content(sample):
    return sample["qa"]["program"]

def processing_answer_content(sample):
    return sample["qa"]["exe_ans"]

df["pre_text_processed"] = df.apply(lambda x: formatting_pre_text(x), axis=1)
df["post_text_processed"] = df.apply(lambda x: formatting_post_text(x), axis=1)
df["table_processed"] = df.apply(lambda x: formatting_table(x), axis=1)
df["table_raw"] = df["table"]  # keep raw rows for table_* row-name lookup at eval time
df["input_question"] = df.apply(lambda x: processing_input_question(x), axis=1)
df["program_processed"] = df.apply(lambda x: processing_program_content(x), axis=1)
df["answer_processed"] = df.apply(lambda x: processing_answer_content(x), axis=1)
df.sample(n=5)

,pre_text,table,post_text,id,qa,pre_text_processed,post_text_processed,table_processed,table_raw,input_question,program_processed,answer_processed
47,"[năm 2019, hpg đã cung cấp gần 2,8 triệu tấn t...","[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",[.],masvn/2020/2020056-HPG_Companynote_MAS22.05.20...,{'question': 'Tỷ lệ ROE (%) của HPG trong năm ...,"năm 2019, hpg đã cung cấp gần 2,8 triệu tấn th...",.,| (Tỷ đồng) | FY 2015 | FY 2016 |...,"[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",Tỷ lệ ROE (%) của HPG trong năm 2020 dự kiến g...,"subtract(14.6, 17.1)",-2.5
118,[kqkd 9m19 của pme đã ghi nhận chứng kiến về t...,"[[FY (Dec.), 12/15, 12/16, 12/17, 12/18, 12/19...",[.],masvn/2020/2020036-MAS_VN_PME_Initiate_Nov_14/...,{'question': 'doanh thu cao nhất (tỷ VNĐ) được...,kqkd 9m19 của pme đã ghi nhận chứng kiến về tă...,.,| FY (Dec.) | 12/15 | 12/16 ...,"[[FY (Dec.), 12/15, 12/16, 12/17, 12/18, 12/19...",doanh thu cao nhất (tỷ VNĐ) được ghi nhận tron...,"table_max(Doanh thu (VNDbn), none)",1781.0
455,[kqkd 9m19 của pme đã ghi nhận chứng kiến về t...,"[[FY (Dec.), 12/15, 12/16, 12/17, 12/18, 12/19...",[.],masvn/2020/2020036-MAS_VN_PME_Initiate_Nov_14/...,{'question': 'Lợi nhuận sau thuế (LNST) của PM...,kqkd 9m19 của pme đã ghi nhận chứng kiến về tă...,.,| FY (Dec.) | 12/15 | 12/16 ...,"[[FY (Dec.), 12/15, 12/16, 12/17, 12/18, 12/19...",Lợi nhuận sau thuế (LNST) của PME giảm bao nhi...,"subtract(307, 309), divide(#0, 309)",-0.00647
322,[thuyết minh báo cáo tài chính hợp nhất ( tiếp...,"[[(đơn vị tính: triệu đô la), 2013, 2012], [cá...",[các khoản phải thu tài chính và hợp đồng soc ...,SNA/2013/page_84.pdf-3,"{'question': 'Trong năm 2013, bao nhiêu phần t...",thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,các khoản phải thu tài chính và hợp đồng soc t...,| (đơn vị tính: triệu đô la) ...,"[[(đơn vị tính: triệu đô la), 2013, 2012], [cá...","Trong năm 2013, bao nhiêu phần trăm các khoản ...","divide(14.9, 546.5)",0.02726
126,[thuyết minh báo cáo tài chính hợp nhất giá tr...,"[[Đơn vị: triệu $, tính đến tháng 12 năm 2012,...",[1 thể hiện tác động lên các công cụ phái sinh...,GS/2012/page_121.pdf-2,{'question': 'Tỷ lệ thay đổi phần trăm trong t...,thuyết minh báo cáo tài chính hợp nhất giá trị...,1 thể hiện tác động lên các công cụ phái sinh ...,| Đơn vị: triệu $ ...,"[[Đơn vị: triệu $, tính đến tháng 12 năm 2012,...",Tỷ lệ thay đổi phần trăm trong tổng các khoản ...,"subtract(377677, 388669), divide(#0, 388669)",-0.02828

In [4]:
df = df[["pre_text_processed", "table_processed", "table_raw", "post_text_processed", "input_question", "program_processed", "answer_processed"]]
df.columns = [["pre_text", "table", "table_raw", "post_text", "question", "program", "answer"]]
df["generated_program"] = ""
df["calculated_program"] = ""
df

,pre_text,table,table_raw,post_text,question,program,answer,generated_program,calculated_program
0,thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,| các thành phần của ảnh hưởng lũy kế của việc...,[[các thành phần của ảnh hưởng lũy kế của việc...,.,Sự thay đổi trong thu nhập ròng từ hiệu ứng tí...,"add(30, 1)",31.0,,
1,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,"Theo dự phóng, doanh thu và lợi nhuận ròng quý...","subtract(9829, 642)",9187.0,,
2,"sử dụng phương pháp p/b và rnav để định giá, c...",| Năm tài chính (31/12) | 2016 | 2017 | ...,"[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",.,IDC có bao nhiêu ha quỹ đất sẵn sàng cho thuê ...,"add(495, 398)",893.0,,
3,27/10/13 26/10/14 25/10/15 30/10/16 29/10/17 2...,| | 27/10/2013 |...,"[[, 27/10/2013, 26/10/2014, 25/10/2015, 30/10/...",.,Tỷ suất lợi nhuận trên đầu tư (ROI) của Applie...,"subtract(96.67, 100), divide(#0, 100)",-0.0333,,
4,thông tin tài chính bổ sung hiệu suất cổ phiếu...,| | 12/26/08 | ...,"[[, 12/26/08, 12/31/09, 12/31/10, 12/31/11, 12...",218 báo cáo thường niên năm 2013 của goldman s...,tỷ lệ lợi nhuận tích lũy tổng cộng theo phần t...,"subtract(248.36, 100), divide(#0, 100)",1.4836,,
...,...,...,...,...,...,...,...,...,...
492,thuyết minh báo cáo tài chính hợp nhất năm 201...,| ...,"[[, 2008, 2007], [Số dư đầu kỳ, $ 134.8, $ 266...",trong tổng số lợi ích thuế chưa được ghi nhận ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575,,
493,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Doanh thu trung bình từ năm tài chính 2017 đến...,"add(29710, 32662), add(#0, 35374), divide(#1, 3)",32582.0,,
494,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Tính phần trăm thay đổi EPS từ năm 2020 đến 2021.,"subtract(962, 788), divide(#0, 788)",0.22081,,
495,"trong quá trình kinh doanh thông thường, dựa t...",| ( đơn vị: nghìn ) | diện tích ròng chưa ph...,"[[( đơn vị: nghìn ), diện tích ròng chưa phát ...",( a ) một giếng khoan thăm dò được lên kế hoạc...,Tỷ lệ phần trăm diện tích đất chưa phát triển ...,"divide(145, 586)",0.24744,,
496,.,| | 1Q18 | 1Q19 | YoY (%...,"[[, 1Q18, 1Q19, YoY (%), Kế hoạch 2019 (%)], [...",doanh thu tăng trưởng trong quý đầu năm có phầ...,"dựa trên kết quả quý 1 năm 2019, lợi nhuận sau...","divide(1041, 0.292)",3565.06849,,

In [5]:
import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ["API_KEY"]
BASE_URL = os.environ["BASE_URL"]

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)

MODEL = "DeepSeek-V4-Flash" # Llama-3.3-70B-Instruct, DeepSeek-V4-Flash, gemma-3-27b-it

In [6]:
SYSTEM_MESSAGE = """You are a financial analysis AI. Your task is to generate a sequential computation program to answer the question, based on the provided context.

### LIST OF 10 VALID OPERATORS:

1. add(a, b) -> a + b
2. subtract(a, b) -> a - b
3. multiply(a, b) -> a * b
4. divide(a, b) -> a / b
5. exp(a, b) -> a^b
6. greater(a, b) -> 1.0 if a > b, else 0.0
7. table_sum(row_name, none) -> sum of the numeric values in the table row named `row_name`
8. table_average(row_name, none) -> arithmetic mean of the numeric values in the table row named `row_name`
9. table_max(row_name, none) -> maximum of the numeric values in the table row named `row_name`
10. table_min(row_name, none) -> minimum of the numeric values in the table row named `row_name`

### RULES:
- Do not use free-form mathematical symbols ("+", "-", "*", "/") outside of parentheses. Every calculation must use one of the 10 operators above.
- table_* operators take exactly two arguments: the row name (copied exactly as it appears as the first cell of the target row) and the literal `none` (e.g. table_max(Lãi ròng, none)), never a list of numeric values.
- Do not perform mental calculations or provide explanations. The output must contain only the program string.
- Reference the result of a previous step using #0 (step 1), #1 (step 2), etc. Steps are separated by commas.
- Preserve the original number format from the context. If a value is missing, use 'none'."""

USER_MESSAGE_FRAME = """### CONTEXT:
[TEXT BEFORE TABLE]
{pre_text}
 
[TABLE]
{table}
 
[TEXT AFTER TABLE]
{post_text}
 
### QUESTION:
{question}
 
### PROGRAM:"""

# 3 few-shot demonstrations sampled from train.json, one per evidence type
# (Table Only / Text Only / Table & Text), following the ViNumQA task's
# own categorization (see VLSP 2025 NumQA paper, Section 3.3).
# The "table" field of each shot is pre-rendered to the same GitHub-markdown
# format that `formatting_table` produces for the real data, so the few-shot
# demonstrations are formatted identically to the actual queries.
FEW_SHOT_EXAMPLES = [
    {
        # Table Only (train idx 1959): answer is derived purely from two table cells.
        "pre_text": "phụ lục iv ace limited và các công ty con thông tin bổ sung về phí tái bảo hiểm thu được cho các năm kết thúc ngày 31 tháng 12 năm 2010, 2009 và 2008 (tính bằng triệu đô la mỹ, ngoại trừ tỷ lệ phần trăm) số tiền trực tiếp nhượng cho các công ty nhận từ các công ty khác số tiền ròng tỷ lệ phần trăm số tiền nhận được trên.",
        "table": (
            "|   cho các năm kết thúc ngày 31 tháng 12 năm 2010, 2009 và 2008 (tính bằng triệu đô la Mỹ, ngoại trừ tỷ lệ phần trăm) | số tiền trực tiếp   | nhượng cho các công ty khác   | nhận từ các công ty khác   | số tiền ròng   | tỷ lệ phần trăm số tiền nhận được trên số tiền ròng   |\n"
            "|----------------------------------------------------------------------------------------------------------------------|---------------------|-------------------------------|----------------------------|----------------|-------------------------------------------------------|\n"
            "|                                                                                                                 2010 | $ 15780             | $ 5792                        | $ 3516                     | $ 13504        | 26% ( 26 % )                                          |\n"
            "|                                                                                                                 2009 | $ 15415             | $ 5943                        | $ 3768                     | $ 13240        | 28% ( 28 % )                                          |\n"
            "|                                                                                                                 2008 | $ 16087             | $ 6144                        | $ 3260                     | $ 13203        | 25% ( 25 % )                                          |"
        ),
        "post_text": ".",
        "question": "Sự khác biệt giữa số tiền chuyển giao và nhận chuyển giao trong năm 2010 là bao nhiêu?",
        "program": "subtract(5792, 3516)",
    },
    {
        # Text Only (train idx 93): the supplied table (VHM financial summary) is
        # irrelevant to the question; the program only uses numbers from pre_text.
        "pre_text": "hệ số khả năng thanh toán lãi vay cũng tăng cao đạt mức 13.2 lần, so với chỉ 10.3 lần cùng kỳ.",
        "table": (
            "|                   |   FY 2015 |   FY 2016 |   FY 2017 |   FY 2018 |   FY 2019(F) |\n"
            "|-------------------|-----------|-----------|-----------|-----------|--------------|\n"
            "| Doanh thu (VNDbn) |      4920 |     11217 |     15297 |     38664 |        71115 |\n"
            "| Lãi gộp (Vbn)     |       718 |      2420 |      3128 |      7617 |        10983 |"
        ),
        "post_text": ".",
        "question": "Hệ số khả năng thanh toán lãi vay tăng bao nhiêu lần so với cùng kỳ năm ngoái?",
        "program": "subtract(13.2, 10.3)",
    },
    {
        # Table & Text (train idx 1127): must locate the right table row ("Nội dung số")
        # across three columns and chain two operators via the #0 reference.
        "pre_text": "tỷ lệ phần trăm chi phí vốn trên phần trăm tổng tài sản của mảng viễn thông được duy trì trên 1, cho thấy sự tập trung phân bổ chi phí vốn vào mảng viễn thông của fpt qua các năm.\nngoài ra, tỷ lệ này của mảng đầu tư và giáo dục là 1,1 vào năm 2018 và 0,9 vào năm 2019, khẳng định fpt cũng đang tập trung vào phát triển 2 mảng này trong 2 năm gần đây.",
        "table": (
            "|                     |   2014 |   2015 |   2016 |   2017 |   2018 |   2019 |\n"
            "|---------------------|--------|--------|--------|--------|--------|--------|\n"
            "| Viễn thông          |    1.8 |    2.4 |    1.9 |    1.4 |    1.7 |    1.8 |\n"
            "| Nội dung số         |    0.4 |    0.2 |    0.9 |    0.1 |    0.1 |    0.1 |\n"
            "| Phát triển phần mềm |    2.4 |    1.3 |    3.1 |    1.1 |    0.4 |    0.5 |"
        ),
        "post_text": ".",
        "question": "Tổng tỷ lệ của mảng Nội dung số trong ba năm từ 2014 đến 2016 là bao nhiêu?",
        "program": "add(0.4, 0.2), add(#0, 0.9)",
    },
]

In [7]:
from tqdm import tqdm

# Build the fixed few-shot prefix once: alternating user/assistant turns,
# one pair per FEW_SHOT_EXAMPLES entry, each following the same USER_MESSAGE_FRAME
# used for the real query so the model sees a consistent input/output format.
few_shot_messages = []
for shot in FEW_SHOT_EXAMPLES:
    few_shot_messages.append({
        "role": "user",
        "content": USER_MESSAGE_FRAME.format(
            pre_text=shot["pre_text"],
            table=shot["table"],
            post_text=shot["post_text"],
            question=shot["question"],
        )
    })
    few_shot_messages.append({"role": "assistant", "content": shot["program"]})

for df_index, values in tqdm(df.iterrows(), total=len(df), desc="Generating program..."):
    pre_text = values["pre_text"]
    table = values["table"]
    post_text = values["post_text"]
    question = values["question"]

    chat_completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": SYSTEM_MESSAGE,
            },
            *few_shot_messages,
            {
                "role": "user",
                "content": USER_MESSAGE_FRAME.format(pre_text=pre_text, table=table, post_text=post_text, question=question)
            },
        ],
            temperature=0.0,
            max_tokens=8096,
            stream=False
            )
    output = chat_completion.choices[0].message.content.strip().strip("\n")

    df.at[df_index, "generated_program"] = output

    print(f"TEST SAMPLE {df_index}:\n\nPREDICTION:\n{output}\n\nGROUND_TRUTH:\n{values['program']}")
    print("="*100)

Generating program...:   0%|          | 1/497 [00:01<14:54,  1.80s/it]

TEST SAMPLE 0:

PREDICTION:
add(-54, 30), add(#0, 1)

GROUND_TRUTH:
add(30, 1)
====================================================================================================

Generating program...:   0%|          | 2/497 [00:03<12:05,  1.47s/it]

TEST SAMPLE 1:

PREDICTION:
subtract(9829, 642)

GROUND_TRUTH:
subtract(9829, 642)
====================================================================================================

Generating program...:   1%|          | 3/497 [00:07<23:26,  2.85s/it]

TEST SAMPLE 2:

PREDICTION:
add(495, 0), add(398, 0)

GROUND_TRUTH:
add(495, 398)
====================================================================================================

Generating program...:   1%|          | 4/497 [00:09<20:03,  2.44s/it]

TEST SAMPLE 3:

PREDICTION:
subtract(96.67, 100), divide(#0, 100)

GROUND_TRUTH:
subtract(96.67, 100), divide(#0, 100)
====================================================================================================

Generating program...:   1%|          | 5/497 [00:13<24:42,  3.01s/it]

TEST SAMPLE 4:

PREDICTION:
divide(248.36, 100.00), subtract(#0, 1), multiply(#1, 100)

GROUND_TRUTH:
subtract(248.36, 100), divide(#0, 100)
====================================================================================================

Generating program...:   1%|          | 6/497 [00:14<18:14,  2.23s/it]

TEST SAMPLE 5:

PREDICTION:
subtract(684, 1535), divide(#0, 1535)

GROUND_TRUTH:
subtract(684, 1535), divide(#0, 1535)
====================================================================================================

Generating program...:   1%|▏         | 7/497 [00:14<13:53,  1.70s/it]

TEST SAMPLE 6:

PREDICTION:
subtract(2147, 1430), divide(#0, 1430)

GROUND_TRUTH:
subtract(2147, 1430), divide(#0, 1430)
====================================================================================================

Generating program...:   2%|▏         | 8/497 [00:15<12:20,  1.51s/it]

TEST SAMPLE 7:

PREDICTION:
subtract(19296, 18511), divide(#0, 18511), multiply(#1, 100)

GROUND_TRUTH:
subtract(19296, 18511), divide(#0, 18511)
====================================================================================================

Generating program...:   2%|▏         | 9/497 [00:16<10:46,  1.32s/it]

TEST SAMPLE 8:

PREDICTION:
subtract(27.1, 26.4), divide(#0, 26.4), multiply(#1, 100)

GROUND_TRUTH:
subtract(27.1, 26.4), divide(#0, 26.4)
====================================================================================================

Generating program...:   2%|▏         | 10/497 [00:18<10:42,  1.32s/it]

TEST SAMPLE 9:

PREDICTION:
subtract(349, 331), divide(#0, 349), multiply(#1, 100)

GROUND_TRUTH:
subtract(331, 349), divide(#0, 349)
====================================================================================================

Generating program...:   2%|▏         | 11/497 [00:25<26:47,  3.31s/it]

TEST SAMPLE 10:

PREDICTION:
divide(22500, 113300), multiply(#0, 100)

GROUND_TRUTH:
divide(22500, 113300)
====================================================================================================

Generating program...:   2%|▏         | 12/497 [00:28<24:11,  2.99s/it]

TEST SAMPLE 11:

PREDICTION:
divide(79.0, 268.4)

GROUND_TRUTH:
divide(79.0, 268.4)
====================================================================================================

Generating program...:   3%|▎         | 13/497 [00:28<18:06,  2.25s/it]

TEST SAMPLE 12:

PREDICTION:
subtract(74300, 70647)

GROUND_TRUTH:
subtract(74300, 70647)
====================================================================================================

Generating program...:   3%|▎         | 14/497 [00:31<19:48,  2.46s/it]

TEST SAMPLE 13:

PREDICTION:
subtract(11, 11)

GROUND_TRUTH:
subtract(11, 11)
====================================================================================================

Generating program...:   3%|▎         | 15/497 [00:32<15:41,  1.95s/it]

TEST SAMPLE 14:

PREDICTION:
table_min(chênh lệch tỷ giá hối đoái, none)

GROUND_TRUTH:
table_max(chênh lệch tỷ giá hối đoái, none)
====================================================================================================

Generating program...:   3%|▎         | 16/497 [00:34<16:22,  2.04s/it]

TEST SAMPLE 15:

PREDICTION:
divide(997, 7000), multiply(#0, 100)

GROUND_TRUTH:
multiply(7, 1000), divide(997, #0)
====================================================================================================

Generating program...:   3%|▎         | 17/497 [00:35<13:24,  1.68s/it]

TEST SAMPLE 16:

PREDICTION:
subtract(36613, 31624), divide(#0, 31624)

GROUND_TRUTH:
subtract(36613, 31624), divide(#0, 31624)
====================================================================================================

Generating program...:   4%|▎         | 18/497 [00:36<12:10,  1.52s/it]

TEST SAMPLE 17:

PREDICTION:
divide(27301, 52667), multiply(#0, 100)

GROUND_TRUTH:
divide(27301, 52667)
====================================================================================================

Generating program...:   4%|▍         | 19/497 [00:38<12:27,  1.56s/it]

TEST SAMPLE 18:

PREDICTION:
add(248107, 433161), divide(#0, 1381518), multiply(#1, 100)

GROUND_TRUTH:
divide(433161, 15973855)
====================================================================================================

Generating program...:   4%|▍         | 20/497 [00:40<13:30,  1.70s/it]

TEST SAMPLE 19:

PREDICTION:
divide(333, 0.159)

GROUND_TRUTH:
divide(333, 0.159)
====================================================================================================

Generating program...:   4%|▍         | 21/497 [00:40<11:04,  1.40s/it]

TEST SAMPLE 20:

PREDICTION:
table_min(ROE (%), none)

GROUND_TRUTH:
table_min(ROE (%), none)
====================================================================================================

Generating program...:   4%|▍         | 22/497 [00:43<12:54,  1.63s/it]

TEST SAMPLE 21:

PREDICTION:
subtract(29.26, 19.78), divide(#0, 19.78), multiply(#1, 100)

GROUND_TRUTH:
subtract(29.26, 24.57), divide(#0, 24.57)
====================================================================================================

Generating program...:   5%|▍         | 23/497 [00:44<11:54,  1.51s/it]

TEST SAMPLE 22:

PREDICTION:
table_max(hóa chất, none), table_min(hóa chất, none), subtract(#0, #1)

GROUND_TRUTH:
subtract(3664, 3474)
====================================================================================================

Generating program...:   5%|▍         | 24/497 [00:45<11:03,  1.40s/it]

TEST SAMPLE 23:

PREDICTION:
divide(2073, 13208), multiply(#0, 100)

GROUND_TRUTH:
divide(2073, 13208)
====================================================================================================

Generating program...:   5%|▌         | 25/497 [00:46<09:52,  1.26s/it]

TEST SAMPLE 24:

PREDICTION:
subtract(52.04, 22.29)

GROUND_TRUTH:
subtract(52.04, 22.3)
====================================================================================================

Generating program...:   5%|▌         | 26/497 [00:47<08:28,  1.08s/it]

TEST SAMPLE 25:

PREDICTION:
subtract(2233, 1921)

GROUND_TRUTH:
subtract(2233, 1921)
====================================================================================================

Generating program...:   5%|▌         | 27/497 [00:50<13:11,  1.68s/it]

TEST SAMPLE 26:

PREDICTION:
subtract(33.1, 22.7), divide(#0, 33.1), multiply(#1, 100)

GROUND_TRUTH:
subtract(22.7, 33.1), divide(#0, 33.1)
====================================================================================================

Generating program...:   6%|▌         | 28/497 [00:51<11:47,  1.51s/it]

TEST SAMPLE 27:

PREDICTION:
subtract(62, 34)

GROUND_TRUTH:
subtract(34, 62), divide(#0, 62)
====================================================================================================

Generating program...:   6%|▌         | 29/497 [00:57<22:55,  2.94s/it]

TEST SAMPLE 28:

PREDICTION:
add(27789, 0)

GROUND_TRUTH:
multiply(2615079, 4.5)
====================================================================================================

Generating program...:   6%|▌         | 30/497 [00:59<21:23,  2.75s/it]

TEST SAMPLE 29:

PREDICTION:
subtract(652, 655)

GROUND_TRUTH:
subtract(652, 655)
====================================================================================================

Generating program...:   6%|▌         | 31/497 [01:00<16:44,  2.16s/it]

TEST SAMPLE 30:

PREDICTION:
subtract(987, 947)

GROUND_TRUTH:
subtract(987, 947)
====================================================================================================

Generating program...:   6%|▋         | 32/497 [01:03<18:27,  2.38s/it]

TEST SAMPLE 31:

PREDICTION:
divide(182, 0.9)

GROUND_TRUTH:
subtract(1, 0.10), divide(182, #0)
====================================================================================================

Generating program...:   7%|▋         | 33/497 [01:13<35:32,  4.60s/it]

TEST SAMPLE 32:

PREDICTION:
subtract(652, 522), divide(#0, 652), multiply(#1, 100)

GROUND_TRUTH:
subtract(652, 522), divide(#0, 652)
====================================================================================================

Generating program...:   7%|▋         | 34/497 [01:16<32:24,  4.20s/it]

TEST SAMPLE 33:

PREDICTION:
divide(3640, 5977), multiply(#0, 100)

GROUND_TRUTH:
divide(3640, 5977)
====================================================================================================

Generating program...:   7%|▋         | 35/497 [01:17<25:04,  3.26s/it]

TEST SAMPLE 34:

PREDICTION:
divide(1733, 2655), multiply(#0, 100)

GROUND_TRUTH:
divide(1733, 2655)
====================================================================================================

Generating program...:   7%|▋         | 36/497 [01:19<20:50,  2.71s/it]

TEST SAMPLE 35:

PREDICTION:
table_min(thuế suất hiệu dụng, none)

GROUND_TRUTH:
table_min(thuế suất hiệu dụng, none)
====================================================================================================

Generating program...:   7%|▋         | 37/497 [01:19<16:02,  2.09s/it]

TEST SAMPLE 36:

PREDICTION:
table_average(ROA, none)

GROUND_TRUTH:
table_average(ROA, none)
====================================================================================================

Generating program...:   8%|▊         | 38/497 [01:20<13:14,  1.73s/it]

TEST SAMPLE 37:

PREDICTION:
subtract(4104, 4073)

GROUND_TRUTH:
subtract(4073, 4104)
====================================================================================================

Generating program...:   8%|▊         | 39/497 [01:21<12:19,  1.62s/it]

TEST SAMPLE 38:

PREDICTION:
divide(35, 285), multiply(#0, 100)

GROUND_TRUTH:
divide(35, 285)
====================================================================================================

Generating program...:   8%|▊         | 40/497 [01:22<09:48,  1.29s/it]

TEST SAMPLE 39:

PREDICTION:
add(20, 30)

GROUND_TRUTH:
add(0.20, 0.30)
====================================================================================================

Generating program...:   8%|▊         | 41/497 [01:23<08:51,  1.16s/it]

TEST SAMPLE 40:

PREDICTION:
subtract(3627, 2726), divide(#0, 2726), multiply(#1, 100)

GROUND_TRUTH:
subtract(3627, 2726), divide(#0, 2726)
====================================================================================================

Generating program...:   8%|▊         | 42/497 [01:25<10:24,  1.37s/it]

TEST SAMPLE 41:

PREDICTION:
subtract(248.36, 100.00), divide(#0, 100.00)

GROUND_TRUTH:
subtract(248.36, 100)
====================================================================================================

Generating program...:   9%|▊         | 43/497 [01:26<09:32,  1.26s/it]

TEST SAMPLE 42:

PREDICTION:
add(43408, 17573), divide(39763, #0)

GROUND_TRUTH:
add(43408, 17573), divide(39763, #0)
====================================================================================================

Generating program...:   9%|▉         | 44/497 [01:32<20:20,  2.69s/it]

TEST SAMPLE 43:

PREDICTION:
subtract(92.49, 100)

GROUND_TRUTH:
subtract(92.49, 100), divide(#0, 100)
====================================================================================================

Generating program...:   9%|▉         | 45/497 [01:33<16:43,  2.22s/it]

TEST SAMPLE 44:

PREDICTION:
table_min(P/E (x), none)

GROUND_TRUTH:
table_min(P/E (x), none)
====================================================================================================

Generating program...:   9%|▉         | 46/497 [01:34<15:13,  2.03s/it]

TEST SAMPLE 45:

PREDICTION:
add(1, 0.62), divide(966, #0)

GROUND_TRUTH:
add(100%, 62%), divide(966, #0)
====================================================================================================

Generating program...:   9%|▉         | 47/497 [01:50<44:31,  5.94s/it]

TEST SAMPLE 46:

PREDICTION:
subtract(546.5, 14.9)

GROUND_TRUTH:
subtract(546.5, 516.9)
====================================================================================================

Generating program...:  10%|▉         | 48/497 [01:51<34:53,  4.66s/it]

TEST SAMPLE 47:

PREDICTION:
subtract(17.1, 14.6)

GROUND_TRUTH:
subtract(14.6, 17.1)
====================================================================================================

Generating program...:  10%|▉         | 49/497 [01:53<27:22,  3.67s/it]

TEST SAMPLE 48:

PREDICTION:
table_max(DCF (FCFF), none)

GROUND_TRUTH:
table_max(DCF (FCFF), none)
====================================================================================================

Generating program...:  10%|█         | 50/497 [01:54<21:22,  2.87s/it]

TEST SAMPLE 49:

PREDICTION:
divide(9151, 0.741)

GROUND_TRUTH:
divide(9151, 0.741)
====================================================================================================

Generating program...:  10%|█         | 51/497 [01:55<17:16,  2.32s/it]

TEST SAMPLE 50:

PREDICTION:
multiply(160196, 58.02)

GROUND_TRUTH:
multiply(160196, 58.02)
====================================================================================================

Generating program...:  10%|█         | 52/497 [01:55<13:51,  1.87s/it]

TEST SAMPLE 51:

PREDICTION:
table_max(Tỷ suất lợi nhuận gộp biên, none)

GROUND_TRUTH:
table_max(Tỷ suất lợi nhuận gộp biên, none)
====================================================================================================

Generating program...:  11%|█         | 53/497 [01:56<11:00,  1.49s/it]

TEST SAMPLE 52:

PREDICTION:
add(19038.8, 9445.09), add(#0, 6286.89)

GROUND_TRUTH:
add(19038.80, 9445.09), add(#0, 6286.89)
====================================================================================================

Generating program...:  11%|█         | 54/497 [01:58<13:01,  1.76s/it]

TEST SAMPLE 53:

PREDICTION:
add(1, 0.244), divide(50000, #0)

GROUND_TRUTH:
add(1, 0.244), divide(50000, #0)
====================================================================================================

Generating program...:  11%|█         | 55/497 [01:59<10:36,  1.44s/it]

TEST SAMPLE 54:

PREDICTION:
multiply(45686, 37.73)

GROUND_TRUTH:
multiply(45686, 37.73)
====================================================================================================

Generating program...:  11%|█▏        | 56/497 [02:01<11:59,  1.63s/it]

TEST SAMPLE 55:

PREDICTION:
subtract(9.3, 8.4), divide(#0, 8.4), multiply(#1, 100)

GROUND_TRUTH:
subtract(9.3, 8.4), add(#0, 8.4)
====================================================================================================

Generating program...:  11%|█▏        | 57/497 [02:03<12:01,  1.64s/it]

TEST SAMPLE 56:

PREDICTION:
table_average(Biên lãi hoạt động (%), none)

GROUND_TRUTH:
table_average(Biên lãi hoạt động (%), none)
====================================================================================================

Generating program...:  12%|█▏        | 58/497 [02:04<11:11,  1.53s/it]

TEST SAMPLE 57:

PREDICTION:
divide(105, 156), multiply(#0, 100)

GROUND_TRUTH:
divide(105, 190)
====================================================================================================

Generating program...:  12%|█▏        | 59/497 [02:12<25:07,  3.44s/it]

TEST SAMPLE 58:

PREDICTION:
table_max(Tỷ suất sinh lợi trên doanh thu thuần, none)

GROUND_TRUTH:
table_max(Tỷ suất sinh lợi trên doanh thu thuần, none)
====================================================================================================

Generating program...:  12%|█▏        | 60/497 [02:15<23:56,  3.29s/it]

TEST SAMPLE 59:

PREDICTION:
divide(24206, 51627), multiply(#0, 100)

GROUND_TRUTH:
divide(24206, 51627)
====================================================================================================

Generating program...:  12%|█▏        | 61/497 [02:16<18:36,  2.56s/it]

TEST SAMPLE 60:

PREDICTION:
subtract(2233, 1075), divide(#0, 1075), multiply(#1, 100)

GROUND_TRUTH:
subtract(2233, 1075), divide(#0, 1075)
====================================================================================================

Generating program...:  12%|█▏        | 62/497 [02:17<16:37,  2.29s/it]

TEST SAMPLE 61:

PREDICTION:
subtract(1171, 1701)

GROUND_TRUTH:
subtract(1171, 1701)
====================================================================================================

Generating program...:  13%|█▎        | 63/497 [02:18<13:08,  1.82s/it]

TEST SAMPLE 62:

PREDICTION:
subtract(18.5, 16.9)

GROUND_TRUTH:
subtract(18.5, 16.9), divide(#0, 16.9)
====================================================================================================

Generating program...:  13%|█▎        | 64/497 [02:19<10:31,  1.46s/it]

TEST SAMPLE 63:

PREDICTION:
add(6571, 8213)

GROUND_TRUTH:
add(6571, 8213)
====================================================================================================

Generating program...:  13%|█▎        | 65/497 [02:20<10:01,  1.39s/it]

TEST SAMPLE 64:

PREDICTION:
divide(69, 1676), multiply(#0, 100)

GROUND_TRUTH:
divide(247, 1676)
====================================================================================================

Generating program...:  13%|█▎        | 66/497 [02:21<08:25,  1.17s/it]

TEST SAMPLE 65:

PREDICTION:
subtract(17.2, 18.5)

GROUND_TRUTH:
subtract(17.2, 18.5), divide(#0, 18.5)
====================================================================================================

Generating program...:  13%|█▎        | 67/497 [02:22<08:05,  1.13s/it]

TEST SAMPLE 66:

PREDICTION:
divide(7874, 16044), multiply(#0, 100)

GROUND_TRUTH:
divide(7874, 16044)
====================================================================================================

Generating program...:  14%|█▎        | 68/497 [02:23<07:39,  1.07s/it]

TEST SAMPLE 67:

PREDICTION:
table_max(ROE (%), none)

GROUND_TRUTH:
table_max(ROE (%), none)
====================================================================================================

Generating program...:  14%|█▍        | 69/497 [02:24<08:57,  1.26s/it]

TEST SAMPLE 68:

PREDICTION:
subtract(342, 301), divide(#0, 301), multiply(#1, 100)

GROUND_TRUTH:
subtract(342, 301), divide(#0, 301)
====================================================================================================

Generating program...:  14%|█▍        | 70/497 [02:26<09:23,  1.32s/it]

TEST SAMPLE 69:

PREDICTION:
divide(92, 1)

GROUND_TRUTH:
divide(92, 1)
====================================================================================================

Generating program...:  14%|█▍        | 71/497 [02:27<08:22,  1.18s/it]

TEST SAMPLE 70:

PREDICTION:
subtract(36.3, 32.9)

GROUND_TRUTH:
subtract(36.3%, 32.9%)
====================================================================================================

Generating program...:  14%|█▍        | 72/497 [02:30<12:20,  1.74s/it]

TEST SAMPLE 71:

PREDICTION:
add(table_sum(Tổng giá trị các dự án, none), table_sum(Tiền mặt, none)), subtract(#0, table_sum(Nợ vay, none))

GROUND_TRUTH:
add(3286158, 278418), subtract(#0, 1070451)
====================================================================================================

Generating program...:  15%|█▍        | 73/497 [02:31<10:21,  1.47s/it]

TEST SAMPLE 72:

PREDICTION:
subtract(774, 631), divide(#0, 631), multiply(#1, 100)

GROUND_TRUTH:
subtract(774, 631), divide(#0, 631)
====================================================================================================

Generating program...:  15%|█▍        | 74/497 [02:32<10:18,  1.46s/it]

TEST SAMPLE 73:

PREDICTION:
divide(95, 3252), multiply(#0, 100)

GROUND_TRUTH:
divide(95, 3252)
====================================================================================================

Generating program...:  15%|█▌        | 75/497 [02:33<08:27,  1.20s/it]

TEST SAMPLE 74:

PREDICTION:
divide(13536, 16594)

GROUND_TRUTH:
divide(13536, 16594)
====================================================================================================

Generating program...:  15%|█▌        | 76/497 [02:34<08:22,  1.19s/it]

TEST SAMPLE 75:

PREDICTION:
subtract(7162, 8213), divide(#0, 8213), multiply(#1, 100)

GROUND_TRUTH:
subtract(7162, 8213), divide(#0, 8213)
====================================================================================================

Generating program...:  15%|█▌        | 77/497 [02:35<08:34,  1.22s/it]

TEST SAMPLE 76:

PREDICTION:
subtract(9.54, 10.8)

GROUND_TRUTH:
subtract(9.54, 10.8), divide(#0, 10.8)
====================================================================================================

Generating program...:  16%|█▌        | 78/497 [02:36<08:47,  1.26s/it]

TEST SAMPLE 77:

PREDICTION:
divide(126, 1300), multiply(#0, 100)

GROUND_TRUTH:
add(240, 1060), divide(126, #0)
====================================================================================================

Generating program...:  16%|█▌        | 79/497 [02:37<07:16,  1.04s/it]

TEST SAMPLE 78:

PREDICTION:
subtract(11133, 8421)

GROUND_TRUTH:
subtract(11133, 8421)
====================================================================================================

Generating program...:  16%|█▌        | 80/497 [02:38<07:15,  1.04s/it]

TEST SAMPLE 79:

PREDICTION:
table_average(Lợi nhuận HĐKD (VNDbn), none)

GROUND_TRUTH:
table_average(Lợi nhuận HĐKD (VNDbn), none)
====================================================================================================

Generating program...:  16%|█▋        | 81/497 [02:39<07:06,  1.03s/it]

TEST SAMPLE 80:

PREDICTION:
divide(448.6, 793.3)

GROUND_TRUTH:
divide(448.6, 793.3)
====================================================================================================

Generating program...:  16%|█▋        | 82/497 [02:41<08:40,  1.25s/it]

TEST SAMPLE 81:

PREDICTION:
divide(26483, 67373), multiply(#0, 100)

GROUND_TRUTH:
divide(26483, 67373)
====================================================================================================

Generating program...:  17%|█▋        | 83/497 [02:41<07:16,  1.05s/it]

TEST SAMPLE 82:

PREDICTION:
subtract(16.63, 14.23)

GROUND_TRUTH:
subtract(16.63%, 14.23%)
====================================================================================================

Generating program...:  17%|█▋        | 84/497 [02:43<07:47,  1.13s/it]

TEST SAMPLE 83:

PREDICTION:
divide(6.3, 18.1), multiply(#0, 100)

GROUND_TRUTH:
divide(6.3, 18.1)
====================================================================================================

Generating program...:  17%|█▋        | 85/497 [02:43<06:39,  1.03it/s]

TEST SAMPLE 84:

PREDICTION:
subtract(3383, 2512)

GROUND_TRUTH:
subtract(3383, 2512)
====================================================================================================

Generating program...:  17%|█▋        | 86/497 [02:47<12:48,  1.87s/it]

TEST SAMPLE 85:

PREDICTION:
subtract(divide(43.81, 100), 1)

GROUND_TRUTH:
subtract(43.81, 100), divide(#0, 100)
====================================================================================================

Generating program...:  18%|█▊        | 87/497 [03:01<37:30,  5.49s/it]

TEST SAMPLE 86:

PREDICTION:
subtract(25017, 22764), divide(#0, 22764), multiply(#1, 100)

GROUND_TRUTH:
subtract(25017, 22764), divide(#0, 22764)
====================================================================================================

Generating program...:  18%|█▊        | 88/497 [03:04<32:28,  4.76s/it]

TEST SAMPLE 87:

PREDICTION:
divide(57100, 163000)

GROUND_TRUTH:
divide(57800, 163000)
====================================================================================================

Generating program...:  18%|█▊        | 89/497 [03:13<39:53,  5.87s/it]

TEST SAMPLE 88:

PREDICTION:
table_sum(Lỗ toàn diện khác lũy kế, none)

GROUND_TRUTH:
table_sum(Lỗ toàn diện khác lũy kế, none)
====================================================================================================

Generating program...:  18%|█▊        | 90/497 [03:13<29:20,  4.33s/it]

TEST SAMPLE 89:

PREDICTION:
subtract(20.4, 19.2)

GROUND_TRUTH:
subtract(19.2, 20.4), divide(#0, 20.4)
====================================================================================================

Generating program...:  18%|█▊        | 91/497 [03:14<22:12,  3.28s/it]

TEST SAMPLE 90:

PREDICTION:
subtract(32662, 29710), divide(#0, 29710), multiply(#1, 100)

GROUND_TRUTH:
subtract(32662, 29710), divide(#0, 29710)
====================================================================================================

Generating program...:  19%|█▊        | 92/497 [03:16<19:18,  2.86s/it]

TEST SAMPLE 91:

PREDICTION:
subtract(1.6, 2.3), divide(#0, 2.3), multiply(#1, 100)

GROUND_TRUTH:
subtract(1.6, 2.3), divide(#0, 2.3)
====================================================================================================

Generating program...:  19%|█▊        | 93/497 [03:17<14:47,  2.20s/it]

TEST SAMPLE 92:

PREDICTION:
divide(137.4, 559.3)

GROUND_TRUTH:
divide(137.4, 559.3)
====================================================================================================

Generating program...:  19%|█▉        | 94/497 [03:17<11:27,  1.71s/it]

TEST SAMPLE 93:

PREDICTION:
add(278418, 3286158)

GROUND_TRUTH:
add(278418, 3286158)
====================================================================================================

Generating program...:  19%|█▉        | 95/497 [03:18<09:15,  1.38s/it]

TEST SAMPLE 94:

PREDICTION:
subtract(5829, 5735), divide(#0, 5735)

GROUND_TRUTH:
subtract(5829, 5735), divide(#0, 5735)
====================================================================================================

Generating program...:  19%|█▉        | 96/497 [03:19<07:51,  1.18s/it]

TEST SAMPLE 95:

PREDICTION:
subtract(48.78, 23.13)

GROUND_TRUTH:
divide(48.78, 100), subtract(#0, 23.1%)
====================================================================================================

Generating program...:  20%|█▉        | 97/497 [03:19<06:46,  1.02s/it]

TEST SAMPLE 96:

PREDICTION:
28032

GROUND_TRUTH:
multiply(56064, 0.5)
====================================================================================================

Generating program...:  20%|█▉        | 98/497 [03:22<10:20,  1.56s/it]

TEST SAMPLE 97:

PREDICTION:
subtract(28207, 16337)

GROUND_TRUTH:
subtract(28207, 16337)
====================================================================================================

Generating program...:  20%|█▉        | 99/497 [03:23<08:47,  1.32s/it]

TEST SAMPLE 98:

PREDICTION:
subtract(1368, 1050)

GROUND_TRUTH:
subtract(1368, 1050)
====================================================================================================

Generating program...:  20%|██        | 100/497 [03:24<07:40,  1.16s/it]

TEST SAMPLE 99:

PREDICTION:
subtract(6750, 4953), divide(#0, 4953)

GROUND_TRUTH:
subtract(6750, 4953), divide(#0, 4953)
====================================================================================================

Generating program...:  20%|██        | 101/497 [03:25<07:59,  1.21s/it]

TEST SAMPLE 100:

PREDICTION:
subtract(33255, 33250)

GROUND_TRUTH:
subtract(33250, 33255)
====================================================================================================

Generating program...:  21%|██        | 102/497 [03:26<07:10,  1.09s/it]

TEST SAMPLE 101:

PREDICTION:
add(64001, 289581)

GROUND_TRUTH:
add(64001, 289581)
====================================================================================================

Generating program...:  21%|██        | 103/497 [03:29<11:47,  1.79s/it]

TEST SAMPLE 102:

PREDICTION:
table_sum("West Gate Park", none), table_sum("Tổng giá trị các dự án", none), divide(#0, #1), multiply(#2, 100)

GROUND_TRUTH:
divide(362344, 3286158)
====================================================================================================

Generating program...:  21%|██        | 104/497 [03:30<09:19,  1.42s/it]

TEST SAMPLE 103:

PREDICTION:
add(67373, 80848)

GROUND_TRUTH:
add(67373, 80848)
====================================================================================================

Generating program...:  21%|██        | 105/497 [03:31<08:35,  1.31s/it]

TEST SAMPLE 104:

PREDICTION:
table_max(Lợi nhuận trước dự phòng, none)

GROUND_TRUTH:
table_max(Lợi nhuận trước dự phòng, none)
====================================================================================================

Generating program...:  21%|██▏       | 106/497 [03:32<07:32,  1.16s/it]

TEST SAMPLE 105:

PREDICTION:
subtract(48.8, 44)

GROUND_TRUTH:
subtract(48.8%, 44%)
====================================================================================================

Generating program...:  22%|██▏       | 107/497 [03:33<06:54,  1.06s/it]

TEST SAMPLE 106:

PREDICTION:
table_average(Biên lãi gộp (%), none)

GROUND_TRUTH:
table_average(Biên lãi gộp (%), none)
====================================================================================================

Generating program...:  22%|██▏       | 108/497 [03:34<06:49,  1.05s/it]

TEST SAMPLE 107:

PREDICTION:
divide(172.8, 50.9)

GROUND_TRUTH:
divide(172.8, 50.9)
====================================================================================================

Generating program...:  22%|██▏       | 109/497 [03:35<06:51,  1.06s/it]

TEST SAMPLE 108:

PREDICTION:
divide(613, 1178), multiply(#0, 100)

GROUND_TRUTH:
divide(613, 1178)
====================================================================================================

Generating program...:  22%|██▏       | 110/497 [03:35<05:59,  1.08it/s]

TEST SAMPLE 109:

PREDICTION:
add(32, 38)

GROUND_TRUTH:
add(32, 38), multiply(#0, 1000000)
====================================================================================================

Generating program...:  22%|██▏       | 111/497 [03:37<07:01,  1.09s/it]

TEST SAMPLE 110:

PREDICTION:
add(2408, 1364)

GROUND_TRUTH:
add(2408, 1364)
====================================================================================================

Generating program...:  23%|██▎       | 112/497 [03:40<11:10,  1.74s/it]

TEST SAMPLE 111:

PREDICTION:
multiply(2590898, 22.08), divide(#0, 1000000)

GROUND_TRUTH:
multiply(2590898, 22.08), divide(#0, 1000000)
====================================================================================================

Generating program...:  23%|██▎       | 113/497 [03:41<09:06,  1.42s/it]

TEST SAMPLE 112:

PREDICTION:
subtract(4434, 3975)

GROUND_TRUTH:
subtract(4434, 3975)
====================================================================================================

Generating program...:  23%|██▎       | 114/497 [03:47<18:28,  2.89s/it]

TEST SAMPLE 113:

PREDICTION:
divide(17944, 22885), multiply(#0, 100)

GROUND_TRUTH:
divide(17944, 22885)
====================================================================================================

Generating program...:  23%|██▎       | 115/497 [04:37<1:48:32, 17.05s/it]

TEST SAMPLE 114:

PREDICTION:
subtract(235.63, 104.23)

GROUND_TRUTH:
subtract(235.63, 104.23), divide(#0, 104.23)
====================================================================================================

Generating program...:  23%|██▎       | 116/497 [04:38<1:17:33, 12.21s/it]

TEST SAMPLE 115:

PREDICTION:
subtract(2371, 1945), divide(#0, 1945), multiply(#1, 100)

GROUND_TRUTH:
subtract(2371, 1945), divide(#0, 1945)
====================================================================================================

Generating program...:  24%|██▎       | 117/497 [04:39<55:49,  8.81s/it]

TEST SAMPLE 116:

PREDICTION:
subtract(5738, 5687), divide(#0, 5687), multiply(#1, 100)

GROUND_TRUTH:
subtract(5738, 5687), divide(#0, 5687)
====================================================================================================

Generating program...:  24%|██▎       | 118/497 [04:41<43:10,  6.84s/it]

TEST SAMPLE 117:

PREDICTION:
subtract(72474, 74300), divide(#0, 74300), multiply(#1, 100)

GROUND_TRUTH:
subtract(72474, 74300), divide(#0, 74300)
====================================================================================================

Generating program...:  24%|██▍       | 119/497 [04:42<30:59,  4.92s/it]

TEST SAMPLE 118:

PREDICTION:
table_max(Doanh thu (VNDbn), none)

GROUND_TRUTH:
table_max(Doanh thu (VNDbn), none)
====================================================================================================

Generating program...:  24%|██▍       | 120/497 [04:42<23:06,  3.68s/it]

TEST SAMPLE 119:

PREDICTION:
multiply(1211143, 308.10)

GROUND_TRUTH:
multiply(1211143, 308.10)
====================================================================================================

Generating program...:  24%|██▍       | 121/497 [04:43<17:20,  2.77s/it]

TEST SAMPLE 120:

PREDICTION:
subtract(31.0, 28.8)

GROUND_TRUTH:
subtract(28.8, 31.0), divide(#0, 31.0)
====================================================================================================

Generating program...:  25%|██▍       | 122/497 [04:44<14:33,  2.33s/it]

TEST SAMPLE 121:

PREDICTION:
subtract(15.3, 14.1)

GROUND_TRUTH:
subtract(14.1, 15.3), divide(#0, 15.3)
====================================================================================================

Generating program...:  25%|██▍       | 123/497 [04:45<12:18,  1.98s/it]

TEST SAMPLE 122:

PREDICTION:
multiply(5977, 0.236)

GROUND_TRUTH:
multiply(5977, 0.236)
====================================================================================================

Generating program...:  25%|██▍       | 124/497 [04:50<17:49,  2.87s/it]

TEST SAMPLE 123:

PREDICTION:
subtract(128.16, 100), divide(#0, 100)

GROUND_TRUTH:
divide(128.16, 100)
====================================================================================================

Generating program...:  25%|██▌       | 125/497 [04:52<14:49,  2.39s/it]

TEST SAMPLE 124:

PREDICTION:
subtract(74, 110)

GROUND_TRUTH:
subtract(74, 110)
====================================================================================================

Generating program...:  25%|██▌       | 126/497 [04:54<15:26,  2.50s/it]

TEST SAMPLE 125:

PREDICTION:
subtract(311.81, 198.18)

GROUND_TRUTH:
subtract(198.18, 100), divide(#0, 100), subtract(311.81, 100), divide(#2, 100), subtract(#3, #1)
====================================================================================================

Generating program...:  26%|██▌       | 127/497 [04:56<14:10,  2.30s/it]

TEST SAMPLE 126:

PREDICTION:
subtract(377677, 388669), divide(#0, 388669), multiply(#1, 100)

GROUND_TRUTH:
subtract(377677, 388669), divide(#0, 388669)
====================================================================================================

Generating program...:  26%|██▌       | 128/497 [04:57<11:27,  1.86s/it]

TEST SAMPLE 127:

PREDICTION:
divide(82, 18)

GROUND_TRUTH:
divide(82, 18)
====================================================================================================

Generating program...:  26%|██▌       | 129/497 [04:58<09:45,  1.59s/it]

TEST SAMPLE 128:

PREDICTION:
subtract(1575, 710)

GROUND_TRUTH:
subtract(1575, 710)
====================================================================================================

Generating program...:  26%|██▌       | 130/497 [05:00<10:55,  1.79s/it]

TEST SAMPLE 129:

PREDICTION:
divide(6.2, 10.0), multiply(#0, 100)

GROUND_TRUTH:
divide(6.2, 10)
====================================================================================================

Generating program...:  26%|██▋       | 131/497 [05:01<08:40,  1.42s/it]

TEST SAMPLE 130:

PREDICTION:
subtract(13.3, 11.5)

GROUND_TRUTH:
divide(13.3, 11.5)
====================================================================================================

Generating program...:  27%|██▋       | 132/497 [05:04<11:50,  1.95s/it]

TEST SAMPLE 131:

PREDICTION:
divide(8.6, 10), multiply(#0, 100)

GROUND_TRUTH:
divide(8.6, 10)
====================================================================================================

Generating program...:  27%|██▋       | 133/497 [05:07<13:56,  2.30s/it]

TEST SAMPLE 132:

PREDICTION:
subtract(6.1, 4.5)

GROUND_TRUTH:
subtract(6.1, 4.5)
====================================================================================================

Generating program...:  27%|██▋       | 134/497 [05:08<12:05,  2.00s/it]

TEST SAMPLE 133:

PREDICTION:
subtract(2108, 1814), divide(#0, 1814)

GROUND_TRUTH:
subtract(2108, 1814), divide(#0, 1814)
====================================================================================================

Generating program...:  27%|██▋       | 135/497 [05:09<09:38,  1.60s/it]

TEST SAMPLE 134:

PREDICTION:
subtract(412, 361)

GROUND_TRUTH:
subtract(412, 361)
====================================================================================================

Generating program...:  27%|██▋       | 136/497 [05:24<33:14,  5.53s/it]

TEST SAMPLE 135:

PREDICTION:
subtract(16.9, 14.9), divide(#0, 14.9), multiply(#1, 100)

GROUND_TRUTH:
subtract(-16.9, -14.9), divide(2, 14.9)
====================================================================================================

Generating program...:  28%|██▊       | 137/497 [05:25<25:23,  4.23s/it]

TEST SAMPLE 136:

PREDICTION:
divide(1014, 5993), multiply(#0, 100)

GROUND_TRUTH:
divide(1014, 5993)
====================================================================================================

Generating program...:  28%|██▊       | 138/497 [05:26<18:55,  3.16s/it]

TEST SAMPLE 137:

PREDICTION:
subtract(34619, 21785)

GROUND_TRUTH:
subtract(34619, 21785)
====================================================================================================

Generating program...:  28%|██▊       | 139/497 [05:28<18:12,  3.05s/it]

TEST SAMPLE 138:

PREDICTION:
subtract(336.5, 368.6)

GROUND_TRUTH:
subtract(336.5, 368.6)
====================================================================================================

Generating program...:  28%|██▊       | 140/497 [05:38<30:19,  5.10s/it]

TEST SAMPLE 139:

PREDICTION:
add(955, 1000), add(#0, 182), divide(4925, #1), multiply(#2, 100)

GROUND_TRUTH:
divide(955, 4925)
====================================================================================================

Generating program...:  28%|██▊       | 141/497 [05:40<23:39,  3.99s/it]

TEST SAMPLE 140:

PREDICTION:
add(13.7, 12.8), add(#0, 11.5)

GROUND_TRUTH:
multiply(1.3, 3)
====================================================================================================

Generating program...:  29%|██▊       | 142/497 [05:56<45:20,  7.66s/it]

TEST SAMPLE 141:

PREDICTION:
subtract(16404, 11963)

GROUND_TRUTH:
subtract(16404, 11963)
====================================================================================================

Generating program...:  29%|██▉       | 143/497 [05:57<32:53,  5.58s/it]

TEST SAMPLE 142:

PREDICTION:
subtract(23.83, 23.13)

GROUND_TRUTH:
subtract(23.83, 23.13)
====================================================================================================

Generating program...:  29%|██▉       | 144/497 [05:58<25:20,  4.31s/it]

TEST SAMPLE 143:

PREDICTION:
subtract(323.7, 335.9), divide(#0, 335.9), multiply(#1, 100)

GROUND_TRUTH:
subtract(323.7, 335.9), divide(#0, 335.9)
====================================================================================================

Generating program...:  29%|██▉       | 145/497 [05:59<19:14,  3.28s/it]

TEST SAMPLE 144:

PREDICTION:
table_max(Lãi ròng, none)

GROUND_TRUTH:
table_max(Lãi ròng, none)
====================================================================================================

Generating program...:  29%|██▉       | 146/497 [06:00<15:23,  2.63s/it]

TEST SAMPLE 145:

PREDICTION:
subtract(9151, 8754), divide(#0, 8754), multiply(#1, 100)

GROUND_TRUTH:
subtract(9151, 8754), divide(#0, 8754)
====================================================================================================

Generating program...:  30%|██▉       | 147/497 [06:02<13:40,  2.34s/it]

TEST SAMPLE 146:

PREDICTION:
add(0.7, 0.7), add(#0, 1.7), add(#1, 1.2), add(#2, 1.1), add(#3, 1.4), divide(#4, 6)

GROUND_TRUTH:
table_average(P/B (x), none)
====================================================================================================

Generating program...:  30%|██▉       | 148/497 [06:04<13:02,  2.24s/it]

TEST SAMPLE 147:

PREDICTION:
add(894791, 869758), add(#0, 392303)

GROUND_TRUTH:
add(894791, 869758), add(#0, 362344)
====================================================================================================

Generating program...:  30%|██▉       | 149/497 [06:05<10:39,  1.84s/it]

TEST SAMPLE 148:

PREDICTION:
table_max(LNST (VNDbn), none)

GROUND_TRUTH:
table_max(LNST (VNDbn), none)
====================================================================================================

Generating program...:  30%|███       | 150/497 [06:10<15:57,  2.76s/it]

TEST SAMPLE 149:

PREDICTION:
table_sum(sản phẩm chưng cất, none)

GROUND_TRUTH:
table_sum(sản phẩm chưng cất, none)
====================================================================================================

Generating program...:  30%|███       | 151/497 [06:10<12:30,  2.17s/it]

TEST SAMPLE 150:

PREDICTION:
add(640, 668), add(#0, 810), add(#1, 927)

GROUND_TRUTH:
add(640, 668), add(#0, 810), add(#1, 927)
====================================================================================================

Generating program...:  31%|███       | 152/497 [06:27<36:51,  6.41s/it]

TEST SAMPLE 151:

PREDICTION:
subtract(26.8, 18.7)

GROUND_TRUTH:
subtract(26.8%, 21.9%)
====================================================================================================

Generating program...:  31%|███       | 153/497 [06:28<28:16,  4.93s/it]

TEST SAMPLE 152:

PREDICTION:
add(987, 1490)

GROUND_TRUTH:
add(987, 1490)
====================================================================================================

Generating program...:  31%|███       | 154/497 [06:31<24:03,  4.21s/it]

TEST SAMPLE 153:

PREDICTION:
subtract(156, 15), divide(#0, 15), multiply(#1, 100)

GROUND_TRUTH:
subtract(156, 15), divide(#0, 15)
====================================================================================================

Generating program...:  31%|███       | 155/497 [06:32<18:30,  3.25s/it]

TEST SAMPLE 154:

PREDICTION:
subtract(349, 294), divide(#0, 294), multiply(#1, 100)

GROUND_TRUTH:
subtract(349, 294), divide(#0, 294)
====================================================================================================

Generating program...:  31%|███▏      | 156/497 [06:33<15:12,  2.68s/it]

TEST SAMPLE 155:

PREDICTION:
add(14.8, 18.3), add(#0, 20.9), add(#1, 16.1), add(#2, 9.8), divide(#3, 5)

GROUND_TRUTH:
add(14.8, 18.3), add(#0, 20.9), add(#1, 16.1), add(#2, 9.8), divide(#3, 5)
====================================================================================================

Generating program...:  32%|███▏      | 157/497 [06:34<12:28,  2.20s/it]

TEST SAMPLE 156:

PREDICTION:
table_max(LNHĐKD, none)

GROUND_TRUTH:
table_max(LNHĐKD, none)
====================================================================================================

Generating program...:  32%|███▏      | 158/497 [06:38<14:37,  2.59s/it]

TEST SAMPLE 157:

PREDICTION:
subtract(438, -291), divide(#0, -291), multiply(#1, 100)

GROUND_TRUTH:
subtract(438, -291), divide(#0, 291)
====================================================================================================

Generating program...:  32%|███▏      | 159/497 [06:38<11:28,  2.04s/it]

TEST SAMPLE 158:

PREDICTION:
table_min(LNST (VNDbn), none)

GROUND_TRUTH:
table_min(LNST (VNDbn), none)
====================================================================================================

Generating program...:  32%|███▏      | 160/497 [06:40<11:03,  1.97s/it]

TEST SAMPLE 159:

PREDICTION:
add(1708928, 3629455), divide(3629455, #0)

GROUND_TRUTH:
add(1708928, 3629455), divide(3629455, #0)
====================================================================================================

Generating program...:  32%|███▏      | 161/497 [06:41<09:02,  1.61s/it]

TEST SAMPLE 160:

PREDICTION:
add(1506, 1490)

GROUND_TRUTH:
add(1506, 1490)
====================================================================================================

Generating program...:  33%|███▎      | 162/497 [06:42<08:07,  1.45s/it]

TEST SAMPLE 161:

PREDICTION:
subtract(25.2, 6.1), divide(#0, 6.1), multiply(#1, 100)

GROUND_TRUTH:
subtract(25.2, 6.1), divide(#0, 6.1)
====================================================================================================

Generating program...:  33%|███▎      | 163/497 [06:43<07:23,  1.33s/it]

TEST SAMPLE 162:

PREDICTION:
add(2.89, 2.89), add(#0, 3.0), divide(#1, 3)

GROUND_TRUTH:
add(2.89, 2.89), add(#0, 3), divide(#1, 3)
====================================================================================================

Generating program...:  33%|███▎      | 164/497 [06:44<07:22,  1.33s/it]

TEST SAMPLE 163:

PREDICTION:
multiply(4929, 63.1), divide(#0, 100)

GROUND_TRUTH:
multiply(4929, 0.631)
====================================================================================================

Generating program...:  33%|███▎      | 165/497 [06:49<13:40,  2.47s/it]

TEST SAMPLE 164:

PREDICTION:
add(27345, 28032)

GROUND_TRUTH:
add(27345, 28032), divide(#0, 2)
====================================================================================================

Generating program...:  33%|███▎      | 166/497 [07:01<28:26,  5.16s/it]

TEST SAMPLE 165:

PREDICTION:
table_max(2003, none), table_min(2003, none), subtract(#0, #1), subtract(#2, #2)

GROUND_TRUTH:
subtract(31, 30)
====================================================================================================

Generating program...:  34%|███▎      | 167/497 [07:02<21:00,  3.82s/it]

TEST SAMPLE 166:

PREDICTION:
add(1724, 2680), add(#0, 3501), add(#1, 3885)

GROUND_TRUTH:
table_sum(EPS, none)
====================================================================================================

Generating program...:  34%|███▍      | 168/497 [07:03<16:10,  2.95s/it]

TEST SAMPLE 167:

PREDICTION:
subtract(5327, 4864)

GROUND_TRUTH:
subtract(4864, 5327)
====================================================================================================

Generating program...:  34%|███▍      | 169/497 [07:04<13:47,  2.52s/it]

TEST SAMPLE 168:

PREDICTION:
table_min(P/E (x), none)

GROUND_TRUTH:
table_min(P/E (x), none)
====================================================================================================

Generating program...:  34%|███▍      | 170/497 [07:20<35:23,  6.49s/it]

TEST SAMPLE 169:

PREDICTION:
table_sum(tổng trái phiếu chuyển tiếp có bảo đảm cao cấp, none), divide(#0, 1000)

GROUND_TRUTH:
add(353, 6), subtract(#0, 32)
====================================================================================================

Generating program...:  34%|███▍      | 171/497 [07:21<25:51,  4.76s/it]

TEST SAMPLE 170:

PREDICTION:
subtract(3252, 2856), divide(#0, 2856)

GROUND_TRUTH:
subtract(3252, 2856), divide(#0, 2856)
====================================================================================================

Generating program...:  35%|███▍      | 172/497 [07:30<33:55,  6.26s/it]

TEST SAMPLE 171:

PREDICTION:
subtract(43.81, 74.57)

GROUND_TRUTH:
subtract(43.81, 100), divide(#0, 100), subtract(74.57, 100), divide(#2, 100), subtract(#0, #2)
====================================================================================================

Generating program...:  35%|███▍      | 173/497 [07:34<29:47,  5.52s/it]

TEST SAMPLE 172:

PREDICTION:
multiply(9, 26.79)

GROUND_TRUTH:
multiply(9, 26.79)
====================================================================================================

Generating program...:  35%|███▌      | 174/497 [07:35<22:55,  4.26s/it]

TEST SAMPLE 173:

PREDICTION:
subtract(182, 181)

GROUND_TRUTH:
subtract(182, 181)
====================================================================================================

Generating program...:  35%|███▌      | 175/497 [07:37<17:51,  3.33s/it]

TEST SAMPLE 174:

PREDICTION:
divide(4250, 9241), multiply(#0, 100)

GROUND_TRUTH:
divide(4250, 9241)
====================================================================================================

Generating program...:  35%|███▌      | 176/497 [07:37<13:58,  2.61s/it]

TEST SAMPLE 175:

PREDICTION:
subtract(2147, 1430), divide(#0, 1430), multiply(#1, 100)

GROUND_TRUTH:
subtract(2147, 1430), divide(#0, 1430)
====================================================================================================

Generating program...:  36%|███▌      | 177/497 [07:38<10:39,  2.00s/it]

TEST SAMPLE 176:

PREDICTION:
add(95, 264), add(#0, 136)

GROUND_TRUTH:
add(95, 264), add(#0, 136)
====================================================================================================

Generating program...:  36%|███▌      | 178/497 [07:40<10:25,  1.96s/it]

TEST SAMPLE 177:

PREDICTION:
divide(1962822, 4333146), multiply(#0, 100)

GROUND_TRUTH:
divide(1962822, 4333146)
====================================================================================================

Generating program...:  36%|███▌      | 179/497 [07:43<11:47,  2.22s/it]

TEST SAMPLE 178:

PREDICTION:
divide(26400, 95362), multiply(#0, 100)

GROUND_TRUTH:
divide(26400, 95362)
====================================================================================================

Generating program...:  36%|███▌      | 180/497 [07:44<09:46,  1.85s/it]

TEST SAMPLE 179:

PREDICTION:
divide(2140954, 151945)

GROUND_TRUTH:
divide(2140954, 151945)
====================================================================================================

Generating program...:  36%|███▋      | 181/497 [07:45<08:05,  1.54s/it]

TEST SAMPLE 180:

PREDICTION:
subtract(19296, 18511), divide(#0, 18511)

GROUND_TRUTH:
subtract(19296, 18511), divide(#0, 18511)
====================================================================================================

Generating program...:  37%|███▋      | 182/497 [07:46<08:21,  1.59s/it]

TEST SAMPLE 181:

PREDICTION:
subtract(160.62, 100), divide(#0, 100)

GROUND_TRUTH:
divide(160.62, 100)
====================================================================================================

Generating program...:  37%|███▋      | 183/497 [07:48<09:04,  1.73s/it]

TEST SAMPLE 182:

PREDICTION:
table_max(nợ phái sinh ròng theo các thỏa thuận song phương, none)

GROUND_TRUTH:
table_max(nợ phái sinh ròng theo các thỏa thuận song phương, none)
====================================================================================================

Generating program...:  37%|███▋      | 184/497 [07:49<07:27,  1.43s/it]

TEST SAMPLE 183:

PREDICTION:
add(27453, 33283), add(#0, 46162), add(#1, 55836), add(#2, 63658)

GROUND_TRUTH:
add(27453, 33283), add(#0, 46162), add(#1, 55836), add(#2, 63658)
====================================================================================================

Generating program...:  37%|███▋      | 185/497 [07:51<08:36,  1.65s/it]

TEST SAMPLE 184:

PREDICTION:
subtract(79.0, 53.9), divide(#0, 79.0), multiply(#1, 100)

GROUND_TRUTH:
subtract(53.9, 79.0), divide(#0, 79.0)
====================================================================================================

Generating program...:  37%|███▋      | 186/497 [08:01<21:18,  4.11s/it]

TEST SAMPLE 185:

PREDICTION:
add(64, 0)

GROUND_TRUTH:
subtract(3.7, 2.8), divide(#0, 2.8)
====================================================================================================

Generating program...:  38%|███▊      | 187/497 [08:02<15:56,  3.08s/it]

TEST SAMPLE 186:

PREDICTION:
subtract(18171, 17282)

GROUND_TRUTH:
subtract(18171, 17282)
====================================================================================================

Generating program...:  38%|███▊      | 188/497 [08:03<13:39,  2.65s/it]

TEST SAMPLE 187:

PREDICTION:
divide(15, 345.6), multiply(#0, 100)

GROUND_TRUTH:
divide(15, 345.6)
====================================================================================================

Generating program...:  38%|███▊      | 189/497 [08:08<16:42,  3.25s/it]

TEST SAMPLE 188:

PREDICTION:
add(12.3, 0), add(37.7, 0)

GROUND_TRUTH:
subtract(37.7, 12.3)
====================================================================================================

Generating program...:  38%|███▊      | 190/497 [08:13<19:30,  3.81s/it]

TEST SAMPLE 189:

PREDICTION:
multiply(750000, 12), divide(#0, 1000)

GROUND_TRUTH:
multiply(12, 1000000), multiply(750000, #0), divide(#1, 1000000000)
====================================================================================================

Generating program...:  38%|███▊      | 191/497 [08:14<15:11,  2.98s/it]

TEST SAMPLE 190:

PREDICTION:
table_average(Lợi nhuận HĐKD ( tỷ đồng), none)

GROUND_TRUTH:
table_average(Lợi nhuận HĐKD ( tỷ đồng), none)
====================================================================================================

Generating program...:  39%|███▊      | 192/497 [08:16<13:22,  2.63s/it]

TEST SAMPLE 191:

PREDICTION:
subtract(168, 224), divide(#0, 224), multiply(#1, 100)

GROUND_TRUTH:
subtract(168, 224), divide(#0, 224)
====================================================================================================

Generating program...:  39%|███▉      | 193/497 [08:17<10:37,  2.10s/it]

TEST SAMPLE 192:

PREDICTION:
table_min(đầu tư thay thế, none)

GROUND_TRUTH:
table_min(đầu tư thay thế, none)
====================================================================================================

Generating program...:  39%|███▉      | 194/497 [08:18<08:36,  1.70s/it]

TEST SAMPLE 193:

PREDICTION:
subtract(29710, 28212), divide(#0, 28212), multiply(#1, 100)

GROUND_TRUTH:
subtract(29710, 28212), divide(#0, 28212)
====================================================================================================

Generating program...:  39%|███▉      | 195/497 [08:19<08:33,  1.70s/it]

TEST SAMPLE 194:

PREDICTION:
divide(96, 1717), multiply(#0, 100)

GROUND_TRUTH:
divide(96, 1717)
====================================================================================================

Generating program...:  39%|███▉      | 196/497 [08:20<06:49,  1.36s/it]

TEST SAMPLE 195:

PREDICTION:
subtract(2512, 2045)

GROUND_TRUTH:
subtract(2512, 2045)
====================================================================================================

Generating program...:  40%|███▉      | 197/497 [08:21<05:50,  1.17s/it]

TEST SAMPLE 196:

PREDICTION:
subtract(155, 148), divide(#0, 148)

GROUND_TRUTH:
subtract(155, 148), divide(#0, 148)
====================================================================================================

Generating program...:  40%|███▉      | 198/497 [08:21<05:03,  1.01s/it]

TEST SAMPLE 197:

PREDICTION:
subtract(38207, 34732), divide(#0, 34732)

GROUND_TRUTH:
subtract(38207, 34732), divide(#0, 34732)
====================================================================================================

Generating program...:  40%|████      | 199/497 [08:27<11:31,  2.32s/it]

TEST SAMPLE 198:

PREDICTION:
subtract(224.65, 100.00), divide(#0, 100.00), multiply(#1, 100)

GROUND_TRUTH:
subtract(224.65, 100), divide(#0, 100)
====================================================================================================

Generating program...:  40%|████      | 200/497 [08:28<09:37,  1.94s/it]

TEST SAMPLE 199:

PREDICTION:
subtract(776, 748)

GROUND_TRUTH:
subtract(776, 748), divide(#0, 748)
====================================================================================================

Generating program...:  40%|████      | 201/497 [08:29<08:27,  1.71s/it]

TEST SAMPLE 200:

PREDICTION:
table_average(ROE (%), none)

GROUND_TRUTH:
table_average(ROE (%), none)
====================================================================================================

Generating program...:  41%|████      | 202/497 [08:30<07:38,  1.55s/it]

TEST SAMPLE 201:

PREDICTION:
divide(3321, 8124), multiply(#0, 100)

GROUND_TRUTH:
divide(3321, 8124)
====================================================================================================

Generating program...:  41%|████      | 203/497 [08:31<06:42,  1.37s/it]

TEST SAMPLE 202:

PREDICTION:
subtract(1983, 1667), divide(#0, 1667), multiply(#1, 100)

GROUND_TRUTH:
subtract(1983, 1667), divide(#0, 1667)
====================================================================================================

Generating program...:  41%|████      | 204/497 [08:32<05:36,  1.15s/it]

TEST SAMPLE 203:

PREDICTION:
subtract(8368, 7874)

GROUND_TRUTH:
subtract(8368, 7874)
====================================================================================================

Generating program...:  41%|████      | 205/497 [08:32<04:49,  1.01it/s]

TEST SAMPLE 204:

PREDICTION:
table_min(Lãi ròng, none)

GROUND_TRUTH:
table_min(Lãi ròng, none)
====================================================================================================

Generating program...:  41%|████▏     | 206/497 [08:33<04:36,  1.05it/s]

TEST SAMPLE 205:

PREDICTION:
table_min(Tỷ lệ thu nhập lãi cận biên (NIM)*, none)

GROUND_TRUTH:
table_min(Tỷ lệ thu nhập lãi cận biên (NIM)*, none)
====================================================================================================

Generating program...:  42%|████▏     | 207/497 [08:34<04:36,  1.05it/s]

TEST SAMPLE 206:

PREDICTION:
subtract(1.11, 1.08), divide(#0, 1.08), multiply(#1, 100)

GROUND_TRUTH:
add(1.11, 1.08), divide(#0, 1.08)
====================================================================================================

Generating program...:  42%|████▏     | 208/497 [08:35<04:20,  1.11it/s]

TEST SAMPLE 207:

PREDICTION:
divide(30000, 7162)

GROUND_TRUTH:
divide(30000, 7162)
====================================================================================================

Generating program...:  42%|████▏     | 209/497 [08:36<03:57,  1.21it/s]

TEST SAMPLE 208:

PREDICTION:
divide(391, 2115)

GROUND_TRUTH:
divide(391, 2115)
====================================================================================================

Generating program...:  42%|████▏     | 210/497 [08:36<03:32,  1.35it/s]

TEST SAMPLE 209:

PREDICTION:
add(74, 110), divide(#0, 2)

GROUND_TRUTH:
add(74, 110), divide(#0, 2)
====================================================================================================

Generating program...:  42%|████▏     | 211/497 [08:39<07:08,  1.50s/it]

TEST SAMPLE 210:

PREDICTION:
divide(4107, 29710), multiply(#0, 100)

GROUND_TRUTH:
divide(4107, 29710)
====================================================================================================

Generating program...:  43%|████▎     | 212/497 [08:40<05:43,  1.20s/it]

TEST SAMPLE 211:

PREDICTION:
add(8756, 14510)

GROUND_TRUTH:
add(8756, 14510)
====================================================================================================

Generating program...:  43%|████▎     | 213/497 [08:41<05:39,  1.20s/it]

TEST SAMPLE 212:

PREDICTION:
divide(5758, 7975), multiply(#0, 100)

GROUND_TRUTH:
divide(5758, 7975)
====================================================================================================

Generating program...:  43%|████▎     | 214/497 [08:42<05:02,  1.07s/it]

TEST SAMPLE 213:

PREDICTION:
divide(1246, 5424)

GROUND_TRUTH:
divide(1246, 5424)
====================================================================================================

Generating program...:  43%|████▎     | 215/497 [08:45<07:52,  1.68s/it]

TEST SAMPLE 214:

PREDICTION:
add(505, 165), add(#0, 501)

GROUND_TRUTH:
add(505, 165)
====================================================================================================

Generating program...:  43%|████▎     | 216/497 [08:47<09:00,  1.92s/it]

TEST SAMPLE 215:

PREDICTION:
add(79, 91)

GROUND_TRUTH:
add(79, 91)
====================================================================================================

Generating program...:  44%|████▎     | 217/497 [08:53<13:42,  2.94s/it]

TEST SAMPLE 216:

PREDICTION:
add(900, 1000), divide(#0, 2)

GROUND_TRUTH:
add(900, 1000), divide(#0, 2)
====================================================================================================

Generating program...:  44%|████▍     | 218/497 [09:12<35:58,  7.74s/it]

TEST SAMPLE 217:

PREDICTION:
divide(10.3, 250)

GROUND_TRUTH:
subtract(500.0, 240.9), divide(#0, 240.9)
====================================================================================================

Generating program...:  44%|████▍     | 219/497 [09:12<25:38,  5.54s/it]

TEST SAMPLE 218:

PREDICTION:
subtract(107, 73)

GROUND_TRUTH:
subtract(107, 73)
====================================================================================================

Generating program...:  44%|████▍     | 220/497 [09:13<19:28,  4.22s/it]

TEST SAMPLE 219:

PREDICTION:
table_sum(Giá trị cổ phiếu (VND), none)

GROUND_TRUTH:
table_sum(Giá trị cổ phiếu (VND), none)
====================================================================================================

Generating program...:  44%|████▍     | 221/497 [09:15<16:27,  3.58s/it]

TEST SAMPLE 220:

PREDICTION:
table_max(P/E (x), none)

GROUND_TRUTH:
table_max(P/E (x), none)
====================================================================================================

Generating program...:  45%|████▍     | 222/497 [09:16<13:06,  2.86s/it]

TEST SAMPLE 221:

PREDICTION:
divide(309, 1675)

GROUND_TRUTH:
divide(309, 1675)
====================================================================================================

Generating program...:  45%|████▍     | 223/497 [09:17<10:23,  2.28s/it]

TEST SAMPLE 222:

PREDICTION:
subtract(553, 345), divide(#0, 345), multiply(#1, 100)

GROUND_TRUTH:
subtract(553, 345), divide(#0, 345)
====================================================================================================

Generating program...:  45%|████▌     | 224/497 [09:18<08:36,  1.89s/it]

TEST SAMPLE 223:

PREDICTION:
add(6.3, 11.4), add(#0, 12.4), add(#1, 11.3), add(#2, 15.7), divide(#3, 5)

GROUND_TRUTH:
table_average(Biên lãi hoạt động (%), none)
====================================================================================================

Generating program...:  45%|████▌     | 225/497 [09:20<07:37,  1.68s/it]

TEST SAMPLE 224:

PREDICTION:
divide(1, 20)

GROUND_TRUTH:
divide(100, 20)
====================================================================================================

Generating program...:  45%|████▌     | 226/497 [09:20<05:59,  1.33s/it]

TEST SAMPLE 225:

PREDICTION:
add(8000, 8000), add(#0, 8000)

GROUND_TRUTH:
add(8000, 8000), add(#0, 8000)
====================================================================================================

Generating program...:  46%|████▌     | 227/497 [09:21<05:27,  1.21s/it]

TEST SAMPLE 226:

PREDICTION:
subtract(4250, 2360), divide(#0, 2360)

GROUND_TRUTH:
subtract(4250, 2360), divide(#0, 2360)
====================================================================================================

Generating program...:  46%|████▌     | 228/497 [09:24<07:35,  1.69s/it]

TEST SAMPLE 227:

PREDICTION:
subtract(802, 711), divide(#0, 802), multiply(#1, 100)

GROUND_TRUTH:
subtract(711, 802), divide(#0, 802)
====================================================================================================

Generating program...:  46%|████▌     | 229/497 [09:47<36:05,  8.08s/it]

TEST SAMPLE 228:

PREDICTION:
divide(4278, 41567), multiply(#0, 100)

GROUND_TRUTH:
divide(40859, 138930)
====================================================================================================

Generating program...:  46%|████▋     | 230/497 [09:47<25:59,  5.84s/it]

TEST SAMPLE 229:

PREDICTION:
subtract(16, 10)

GROUND_TRUTH:
subtract(16, 10), divide(#0, 10)
====================================================================================================

Generating program...:  46%|████▋     | 231/497 [09:53<25:08,  5.67s/it]

TEST SAMPLE 230:

PREDICTION:
add(240, 1060)

GROUND_TRUTH:
add(240, 1060)
====================================================================================================

Generating program...:  47%|████▋     | 232/497 [09:53<18:22,  4.16s/it]

TEST SAMPLE 231:

PREDICTION:
multiply(3885, 9.8)

GROUND_TRUTH:
multiply(3885, 9.8)
====================================================================================================

Generating program...:  47%|████▋     | 233/497 [09:54<13:52,  3.15s/it]

TEST SAMPLE 232:

PREDICTION:
add(11219, 2648), divide(2648, #0)

GROUND_TRUTH:
add(11219, 2648), divide(2648, #0)
====================================================================================================

Generating program...:  47%|████▋     | 234/497 [09:55<10:50,  2.47s/it]

TEST SAMPLE 233:

PREDICTION:
divide(27.47, 13.64)

GROUND_TRUTH:
divide(27.47, 13.64)
====================================================================================================

Generating program...:  47%|████▋     | 235/497 [09:56<08:27,  1.94s/it]

TEST SAMPLE 234:

PREDICTION:
subtract(931.3, 973.7), divide(#0, 973.7)

GROUND_TRUTH:
subtract(931.3, 973.7), divide(#0, 973.7)
====================================================================================================

Generating program...:  47%|████▋     | 236/497 [09:57<07:22,  1.70s/it]

TEST SAMPLE 235:

PREDICTION:
subtract(2500, 2115), divide(#0, 2115), multiply(#1, 100)

GROUND_TRUTH:
subtract(2500, 2115), divide(#0, 2115)
====================================================================================================

Generating program...:  48%|████▊     | 237/497 [09:57<05:56,  1.37s/it]

TEST SAMPLE 236:

PREDICTION:
table_max(EPS (VND), none)

GROUND_TRUTH:
table_max(EPS (VND), none)
====================================================================================================

Generating program...:  48%|████▊     | 238/497 [09:58<05:00,  1.16s/it]

TEST SAMPLE 237:

PREDICTION:
add(44.72, 34.25), divide(#0, 2)

GROUND_TRUTH:
add(44.72, 34.25), divide(#0, 2)
====================================================================================================

Generating program...:  48%|████▊     | 239/497 [09:59<04:21,  1.01s/it]

TEST SAMPLE 238:

PREDICTION:
subtract(12, 10)

GROUND_TRUTH:
subtract(12, 10)
====================================================================================================

Generating program...:  48%|████▊     | 240/497 [10:00<05:03,  1.18s/it]

TEST SAMPLE 239:

PREDICTION:
divide(8.1, 56.0), multiply(#0, 100)

GROUND_TRUTH:
divide(8.1, 56.0)
====================================================================================================

Generating program...:  48%|████▊     | 241/497 [10:01<04:33,  1.07s/it]

TEST SAMPLE 240:

PREDICTION:
add(4.5, 9.1), add(#0, 7.8), add(#1, 7.5), divide(#2, 4)

GROUND_TRUTH:
table_average(ROE (%), none)
====================================================================================================

Generating program...:  49%|████▊     | 242/497 [10:08<11:44,  2.76s/it]

TEST SAMPLE 241:

PREDICTION:
multiply(90000, 149.28)

GROUND_TRUTH:
multiply(90000, 149.28)
====================================================================================================

Generating program...:  49%|████▉     | 243/497 [10:09<09:54,  2.34s/it]

TEST SAMPLE 242:

PREDICTION:
add(27453, 33283), add(#0, 46162), add(#1, 55836), add(#2, 63658), divide(#3, 5)

GROUND_TRUTH:
table_average(Doanh thu, none)
====================================================================================================

Generating program...:  49%|████▉     | 244/497 [10:10<08:11,  1.94s/it]

TEST SAMPLE 243:

PREDICTION:
table_average(doanh thu thuần, none)

GROUND_TRUTH:
table_average(doanh thu thuần, none)
====================================================================================================

Generating program...:  49%|████▉     | 245/497 [10:12<07:21,  1.75s/it]

TEST SAMPLE 244:

PREDICTION:
table_average(Giá trị sổ sách / cổ phần (đồng), none)

GROUND_TRUTH:
table_average(Giá trị sổ sách / cổ phần (đồng), none)
====================================================================================================

Generating program...:  49%|████▉     | 246/497 [10:17<12:35,  3.01s/it]

TEST SAMPLE 245:

PREDICTION:
divide(2900, 900.1)

GROUND_TRUTH:
divide(2.9, 900.1)
====================================================================================================

Generating program...:  50%|████▉     | 247/497 [10:18<09:30,  2.28s/it]

TEST SAMPLE 246:

PREDICTION:
multiply(14050, 1.2)

GROUND_TRUTH:
multiply(14050, 1.2)
====================================================================================================

Generating program...:  50%|████▉     | 248/497 [10:19<07:28,  1.80s/it]

TEST SAMPLE 247:

PREDICTION:
add(14583, 4953)

GROUND_TRUTH:
add(14583, 4953)
====================================================================================================

Generating program...:  50%|█████     | 249/497 [10:24<11:26,  2.77s/it]

TEST SAMPLE 248:

PREDICTION:
subtract(99.02, 100)

GROUND_TRUTH:
subtract(99.02, 100), divide(#0, 100)
====================================================================================================

Generating program...:  50%|█████     | 250/497 [10:26<10:12,  2.48s/it]

TEST SAMPLE 249:

PREDICTION:
subtract(24296, 29002), divide(#0, 29002), multiply(#1, 100)

GROUND_TRUTH:
subtract(24296, 29002), divide(#0, 29002)
====================================================================================================

Generating program...:  51%|█████     | 251/497 [10:42<27:35,  6.73s/it]

TEST SAMPLE 250:

PREDICTION:
subtract(1328, 176)

GROUND_TRUTH:
subtract(1328, 176)
====================================================================================================

Generating program...:  51%|█████     | 252/497 [10:43<20:37,  5.05s/it]

TEST SAMPLE 251:

PREDICTION:
divide(2435, 9475), multiply(#0, 100)

GROUND_TRUTH:
divide(2435, 9475)
====================================================================================================

Generating program...:  51%|█████     | 253/497 [10:47<19:23,  4.77s/it]

TEST SAMPLE 252:

PREDICTION:
subtract(107.76, 100.00), divide(#0, 100.00), multiply(#1, 100)

GROUND_TRUTH:
subtract(107.76, 100), divide(#0, 100)
====================================================================================================

Generating program...:  51%|█████     | 254/497 [10:50<17:08,  4.23s/it]

TEST SAMPLE 253:

PREDICTION:
divide(2.8, 15.2), multiply(#0, 100)

GROUND_TRUTH:
divide(2.8, 15.2)
====================================================================================================

Generating program...:  51%|█████▏    | 255/497 [10:52<13:14,  3.28s/it]

TEST SAMPLE 254:

PREDICTION:
subtract(10015, 7528), divide(#0, 7528), multiply(#1, 100)

GROUND_TRUTH:
subtract(10015, 7528), divide(#0, 7528)
====================================================================================================

Generating program...:  52%|█████▏    | 256/497 [10:53<11:22,  2.83s/it]

TEST SAMPLE 255:

PREDICTION:
divide(947, 3786), multiply(#0, 100)

GROUND_TRUTH:
divide(947, 3786)
====================================================================================================

Generating program...:  52%|█████▏    | 257/497 [10:54<08:52,  2.22s/it]

TEST SAMPLE 256:

PREDICTION:
divide(3639, 39632)

GROUND_TRUTH:
divide(3639, 39632)
====================================================================================================

Generating program...:  52%|█████▏    | 258/497 [10:56<08:45,  2.20s/it]

TEST SAMPLE 257:

PREDICTION:
divide(861, 9379)

GROUND_TRUTH:
divide(861, 9379)
====================================================================================================

Generating program...:  52%|█████▏    | 259/497 [10:57<07:11,  1.81s/it]

TEST SAMPLE 258:

PREDICTION:
subtract(10015, 7528), divide(#0, 7528), multiply(#1, 100)

GROUND_TRUTH:
subtract(10015, 7528), divide(#0, 7528)
====================================================================================================

Generating program...:  52%|█████▏    | 260/497 [10:58<06:08,  1.56s/it]

TEST SAMPLE 259:

PREDICTION:
subtract(1.19, 1.46)

GROUND_TRUTH:
subtract(1.19, 1.46)
====================================================================================================

Generating program...:  53%|█████▎    | 261/497 [10:59<05:24,  1.38s/it]

TEST SAMPLE 260:

PREDICTION:
table_max(Lãi hoạt động (VND tỷ), none)

GROUND_TRUTH:
table_max(Lãi hoạt động (VND tỷ), none)
====================================================================================================

Generating program...:  53%|█████▎    | 262/497 [11:04<09:09,  2.34s/it]

TEST SAMPLE 261:

PREDICTION:
subtract(186, 26), divide(#0, 26), multiply(#1, 100)

GROUND_TRUTH:
subtract(186, 26), divide(#0, 26)
====================================================================================================

Generating program...:  53%|█████▎    | 263/497 [11:05<07:49,  2.01s/it]

TEST SAMPLE 262:

PREDICTION:
subtract(1135, 1016), divide(#0, 1016), multiply(#1, 100)

GROUND_TRUTH:
subtract(1135, 1016), divide(#0, 1016)
====================================================================================================

Generating program...:  53%|█████▎    | 264/497 [11:06<06:31,  1.68s/it]

TEST SAMPLE 263:

PREDICTION:
divide(217692, 139255)

GROUND_TRUTH:
divide(217692, 139255)
====================================================================================================

Generating program...:  53%|█████▎    | 265/497 [11:07<06:18,  1.63s/it]

TEST SAMPLE 264:

PREDICTION:
divide(362344, 4000000)

GROUND_TRUTH:
divide(362344, 4000000)
====================================================================================================

Generating program...:  54%|█████▎    | 266/497 [11:08<05:07,  1.33s/it]

TEST SAMPLE 265:

PREDICTION:
subtract(35.0, 13.7)

GROUND_TRUTH:
subtract(35.0%, 13.7%)
====================================================================================================

Generating program...:  54%|█████▎    | 267/497 [11:09<05:01,  1.31s/it]

TEST SAMPLE 266:

PREDICTION:
add(342.9, 78.5), divide(342.9, #0), multiply(#1, 100)

GROUND_TRUTH:
add(342.9, 78.5), divide(342.9, #0)
====================================================================================================

Generating program...:  54%|█████▍    | 268/497 [11:10<04:22,  1.15s/it]

TEST SAMPLE 267:

PREDICTION:
subtract(3786, 1506)

GROUND_TRUTH:
subtract(3786, 1506)
====================================================================================================

Generating program...:  54%|█████▍    | 269/497 [11:11<03:40,  1.04it/s]

TEST SAMPLE 268:

PREDICTION:
add(11963, 27789), divide(#0, 2)

GROUND_TRUTH:
multiply(11963, 0.7), multiply(27789, 0.3), add(#0, #1)
====================================================================================================

Generating program...:  54%|█████▍    | 270/497 [11:11<03:35,  1.05it/s]

TEST SAMPLE 269:

PREDICTION:
subtract(14583, 11219), divide(#0, 11219), multiply(#1, 100)

GROUND_TRUTH:
subtract(14583, 11219), divide(#0, 11219)
====================================================================================================

Generating program...:  55%|█████▍    | 271/497 [11:14<05:18,  1.41s/it]

TEST SAMPLE 270:

PREDICTION:
add(6469, 6001), add(#0, 5441), divide(#1, 3)

GROUND_TRUTH:
table_average(cuối năm, none)
====================================================================================================

Generating program...:  55%|█████▍    | 272/497 [11:15<04:50,  1.29s/it]

TEST SAMPLE 271:

PREDICTION:
subtract(45.3, 48.1)

GROUND_TRUTH:
subtract(45.3, 48.1)
====================================================================================================

Generating program...:  55%|█████▍    | 273/497 [11:16<04:21,  1.17s/it]

TEST SAMPLE 272:

PREDICTION:
subtract(34732, 28538), divide(#0, 28538), multiply(#1, 100)

GROUND_TRUTH:
subtract(34732, 28538), divide(#0, 28538)
====================================================================================================

Generating program...:  55%|█████▌    | 274/497 [11:17<04:45,  1.28s/it]

TEST SAMPLE 273:

PREDICTION:
subtract(107551, 28114)

GROUND_TRUTH:
subtract(107551, 28114)
====================================================================================================

Generating program...:  55%|█████▌    | 275/497 [11:18<04:04,  1.10s/it]

TEST SAMPLE 274:

PREDICTION:
subtract(4481, 1994)

GROUND_TRUTH:
subtract(4481, 1994)
====================================================================================================

Generating program...:  56%|█████▌    | 276/497 [11:19<03:42,  1.01s/it]

TEST SAMPLE 275:

PREDICTION:
subtract(52.04, 23.83)

GROUND_TRUTH:
subtract(52.04, 23.83)
====================================================================================================

Generating program...:  56%|█████▌    | 277/497 [11:20<04:13,  1.15s/it]

TEST SAMPLE 276:

PREDICTION:
subtract(37.7, -13.75)

GROUND_TRUTH:
subtract(37.70, -13.75)
====================================================================================================

Generating program...:  56%|█████▌    | 278/497 [11:21<03:41,  1.01s/it]

TEST SAMPLE 277:

PREDICTION:
subtract(3972, 2829), divide(#0, 2829)

GROUND_TRUTH:
subtract(3.972, 2.829), divide(#0, 2.829)
====================================================================================================

Generating program...:  56%|█████▌    | 279/497 [11:22<03:21,  1.08it/s]

TEST SAMPLE 278:

PREDICTION:
subtract(4913, 4646)

GROUND_TRUTH:
subtract(4646, 4913)
====================================================================================================

Generating program...:  56%|█████▋    | 280/497 [11:22<02:56,  1.23it/s]

TEST SAMPLE 279:

PREDICTION:
subtract(3885, 3501)

GROUND_TRUTH:
subtract(3885, 3501)
====================================================================================================

Generating program...:  57%|█████▋    | 281/497 [11:23<03:11,  1.13it/s]

TEST SAMPLE 280:

PREDICTION:
add(7783, 8687), add(#0, 9052), add(#1, 8310), add(#2, 5977), add(#3, 7205)

GROUND_TRUTH:
table_sum(Doanh thu, none)
====================================================================================================

Generating program...:  57%|█████▋    | 282/497 [11:25<03:48,  1.06s/it]

TEST SAMPLE 281:

PREDICTION:
divide(743, 3871), multiply(#0, 100)

GROUND_TRUTH:
divide(743, 3871)
====================================================================================================

Generating program...:  57%|█████▋    | 283/497 [11:33<11:20,  3.18s/it]

TEST SAMPLE 282:

PREDICTION:
divide(541, 2859), multiply(#0, 100)

GROUND_TRUTH:
divide(541, 2859)
====================================================================================================

Generating program...:  57%|█████▋    | 284/497 [11:34<08:42,  2.45s/it]

TEST SAMPLE 283:

PREDICTION:
table_min(Doanh thu, none)

GROUND_TRUTH:
table_min(Doanh thu, none)
====================================================================================================

Generating program...:  57%|█████▋    | 285/497 [11:35<07:30,  2.13s/it]

TEST SAMPLE 284:

PREDICTION:
subtract(3.38, 2.7)

GROUND_TRUTH:
subtract(3.38, 2.7)
====================================================================================================

Generating program...:  58%|█████▊    | 286/497 [11:38<08:02,  2.29s/it]

TEST SAMPLE 285:

PREDICTION:
subtract(21.2, 19.2)

GROUND_TRUTH:
subtract(21.2%, 19.2%)
====================================================================================================

Generating program...:  58%|█████▊    | 287/497 [11:44<12:25,  3.55s/it]

TEST SAMPLE 286:

PREDICTION:
divide(14.9, 546.5), multiply(#0, 100)

GROUND_TRUTH:
divide(14.9, 546.5)
====================================================================================================

Generating program...:  58%|█████▊    | 288/497 [11:45<09:31,  2.74s/it]

TEST SAMPLE 287:

PREDICTION:
subtract(5474, 4929), divide(#0, 4929), multiply(#1, 100)

GROUND_TRUTH:
subtract(5474, 4929), divide(#0, 4929)
====================================================================================================

Generating program...:  58%|█████▊    | 289/497 [11:46<07:47,  2.25s/it]

TEST SAMPLE 288:

PREDICTION:
table_average(Tỷ lệ LNHĐKD (%), none)

GROUND_TRUTH:
table_average(Tỷ lệ LNHĐKD (%), none)
====================================================================================================

Generating program...:  58%|█████▊    | 290/497 [11:47<06:14,  1.81s/it]

TEST SAMPLE 289:

PREDICTION:
add(6.05, 6.46), divide(#0, 2)

GROUND_TRUTH:
add(6.05, 6.46), divide(#0, 2)
====================================================================================================

Generating program...:  59%|█████▊    | 291/497 [11:49<06:44,  1.97s/it]

TEST SAMPLE 290:

PREDICTION:
divide(35.9, 426.6), multiply(#0, 100)

GROUND_TRUTH:
divide(35.9, 426.6)
====================================================================================================

Generating program...:  59%|█████▉    | 292/497 [11:52<07:35,  2.22s/it]

TEST SAMPLE 291:

PREDICTION:
subtract(366, 234)

GROUND_TRUTH:
table_max(Lợi nhuận HĐKD (VNDbn), none), table_min(Lợi nhuận HĐKD (VNDbn), none), subtract(#0, #1)
====================================================================================================

Generating program...:  59%|█████▉    | 293/497 [11:53<06:01,  1.77s/it]

TEST SAMPLE 292:

PREDICTION:
divide(24700, 101500)

GROUND_TRUTH:
divide(24700, 101500)
====================================================================================================

Generating program...:  59%|█████▉    | 294/497 [11:57<08:39,  2.56s/it]

TEST SAMPLE 293:

PREDICTION:
add(650, 0)

GROUND_TRUTH:
divide(172, 26.4%)
====================================================================================================

Generating program...:  59%|█████▉    | 295/497 [12:05<14:08,  4.20s/it]

TEST SAMPLE 294:

PREDICTION:
add(1, 0.409), multiply(1386, #0)

GROUND_TRUTH:
add(1, 0.409), multiply(1386, #0)
====================================================================================================

Generating program...:  60%|█████▉    | 296/497 [12:06<10:43,  3.20s/it]

TEST SAMPLE 295:

PREDICTION:
subtract(2600, 2487), divide(#0, 2487), multiply(#1, 100)

GROUND_TRUTH:
subtract(2600, 2487), divide(#0, 2487)
====================================================================================================

Generating program...:  60%|█████▉    | 297/497 [12:07<08:21,  2.51s/it]

TEST SAMPLE 296:

PREDICTION:
subtract(18.9, 15.5), divide(#0, 15.5), multiply(#1, 100)

GROUND_TRUTH:
subtract(18.9, 15.5), divide(#0, 15.5)
====================================================================================================

Generating program...:  60%|█████▉    | 298/497 [12:07<06:17,  1.90s/it]

TEST SAMPLE 297:

PREDICTION:
table_max(Tỷ suất cổ tức (%), none)

GROUND_TRUTH:
table_max(Tỷ suất cổ tức (%), none)
====================================================================================================

Generating program...:  60%|██████    | 299/497 [12:11<07:46,  2.36s/it]

TEST SAMPLE 298:

PREDICTION:
subtract(23.6, 20.5)

GROUND_TRUTH:
divide(23.6, 20.5)
====================================================================================================

Generating program...:  60%|██████    | 300/497 [12:12<06:03,  1.84s/it]

TEST SAMPLE 299:

PREDICTION:
add(5758, 3838)

GROUND_TRUTH:
add(5758, 3838)
====================================================================================================

Generating program...:  61%|██████    | 301/497 [12:13<05:30,  1.69s/it]

TEST SAMPLE 300:

PREDICTION:
divide(159, 898), multiply(#0, 100)

GROUND_TRUTH:
divide(159, 898)
====================================================================================================

Generating program...:  61%|██████    | 302/497 [12:13<04:27,  1.37s/it]

TEST SAMPLE 301:

PREDICTION:
divide(2902, 14773)

GROUND_TRUTH:
divide(2902, 14773)
====================================================================================================

Generating program...:  61%|██████    | 303/497 [12:17<06:38,  2.06s/it]

TEST SAMPLE 302:

PREDICTION:
none

GROUND_TRUTH:
divide(1423, 59677)
====================================================================================================

Generating program...:  61%|██████    | 304/497 [12:18<05:15,  1.63s/it]

TEST SAMPLE 303:

PREDICTION:
divide(331, 3243)

GROUND_TRUTH:
divide(331, 3243)
====================================================================================================

Generating program...:  61%|██████▏   | 305/497 [12:19<04:27,  1.40s/it]

TEST SAMPLE 304:

PREDICTION:
subtract(5924, 4830), divide(#0, 4830), multiply(#1, 100)

GROUND_TRUTH:
subtract(5924, 4830), divide(#0, 4830)
====================================================================================================

Generating program...:  62%|██████▏   | 306/497 [12:19<03:39,  1.15s/it]

TEST SAMPLE 305:

PREDICTION:
multiply(2175, 5.5)

GROUND_TRUTH:
multiply(2175, 5.5)
====================================================================================================

Generating program...:  62%|██████▏   | 307/497 [12:20<03:33,  1.12s/it]

TEST SAMPLE 306:

PREDICTION:
divide(733, 1284), multiply(#0, 100)

GROUND_TRUTH:
divide(733, 1284)
====================================================================================================

Generating program...:  62%|██████▏   | 308/497 [12:22<04:18,  1.37s/it]

TEST SAMPLE 307:

PREDICTION:
divide(15, 766), multiply(#0, 100)

GROUND_TRUTH:
divide(15, 766)
====================================================================================================

Generating program...:  62%|██████▏   | 309/497 [12:23<03:52,  1.24s/it]

TEST SAMPLE 308:

PREDICTION:
subtract(9.8, 8.1)

GROUND_TRUTH:
subtract(9.8, 8.1)
====================================================================================================

Generating program...:  62%|██████▏   | 310/497 [12:24<03:35,  1.15s/it]

TEST SAMPLE 309:

PREDICTION:
divide(2360, 6596), multiply(#0, 100)

GROUND_TRUTH:
divide(2360, 6596)
====================================================================================================

Generating program...:  63%|██████▎   | 311/497 [12:25<03:24,  1.10s/it]

TEST SAMPLE 310:

PREDICTION:
add(136, 132), add(#0, 137)

GROUND_TRUTH:
add(136, 132), add(#0, 137)
====================================================================================================

Generating program...:  63%|██████▎   | 312/497 [12:26<03:02,  1.01it/s]

TEST SAMPLE 311:

PREDICTION:
subtract(182, 134), divide(#0, 134)

GROUND_TRUTH:
subtract(182, 134), divide(#0, 134)
====================================================================================================

Generating program...:  63%|██████▎   | 313/497 [12:26<02:35,  1.18it/s]

TEST SAMPLE 312:

PREDICTION:
subtract(2494125, 1070451)

GROUND_TRUTH:
subtract(2494125, 1070451)
====================================================================================================

Generating program...:  63%|██████▎   | 314/497 [12:28<03:18,  1.08s/it]

TEST SAMPLE 313:

PREDICTION:
subtract(151, 136), divide(#0, 136), multiply(#1, 100)

GROUND_TRUTH:
subtract(151, 136), divide(#0, 136)
====================================================================================================

Generating program...:  63%|██████▎   | 315/497 [12:29<03:35,  1.19s/it]

TEST SAMPLE 314:

PREDICTION:
divide(4630, 51410), multiply(#0, 100)

GROUND_TRUTH:
divide(4630, 46780)
====================================================================================================

Generating program...:  64%|██████▎   | 316/497 [12:31<03:45,  1.24s/it]

TEST SAMPLE 315:

PREDICTION:
subtract(21.81, 10.04), divide(#0, 10.04), multiply(#1, 100)

GROUND_TRUTH:
subtract(21.81, 10.04), divide(#0, 10.04)
====================================================================================================

Generating program...:  64%|██████▍   | 317/497 [12:31<03:10,  1.06s/it]

TEST SAMPLE 316:

PREDICTION:
subtract(1659, 1242)

GROUND_TRUTH:
subtract(1659, 1242)
====================================================================================================

Generating program...:  64%|██████▍   | 318/497 [12:32<03:04,  1.03s/it]

TEST SAMPLE 317:

PREDICTION:
subtract(917491, 783031), divide(#0, 783031), multiply(#1, 100)

GROUND_TRUTH:
subtract(917491, 783031), divide(#0, 783031)
====================================================================================================

Generating program...:  64%|██████▍   | 319/497 [12:33<03:01,  1.02s/it]

TEST SAMPLE 318:

PREDICTION:
subtract(95362, 63658), divide(#0, 63658), multiply(#1, 100)

GROUND_TRUTH:
subtract(95362, 63658), divide(#0, 63658)
====================================================================================================

Generating program...:  64%|██████▍   | 320/497 [12:35<03:49,  1.30s/it]

TEST SAMPLE 319:

PREDICTION:
subtract(139549, 201808)

GROUND_TRUTH:
subtract(139549, 201808)
====================================================================================================

Generating program...:  65%|██████▍   | 321/497 [12:36<03:13,  1.10s/it]

TEST SAMPLE 320:

PREDICTION:
add(1884, 2162), add(#0, 2497), add(#1, 2856), add(#2, 3252)

GROUND_TRUTH:
add(1884, 2162), add(#0, 2497), add(#1, 2856), add(#2, 3252)
====================================================================================================

Generating program...:  65%|██████▍   | 322/497 [12:37<03:01,  1.04s/it]

TEST SAMPLE 321:

PREDICTION:
table_min(ROE (%), none)

GROUND_TRUTH:
table_min(ROE (%), none)
====================================================================================================

Generating program...:  65%|██████▍   | 323/497 [12:39<03:47,  1.31s/it]

TEST SAMPLE 322:

PREDICTION:
divide(14.9, 546.5), multiply(#0, 100)

GROUND_TRUTH:
divide(14.9, 546.5)
====================================================================================================

Generating program...:  65%|██████▌   | 324/497 [12:43<06:18,  2.19s/it]

TEST SAMPLE 323:

PREDICTION:
multiply(25017, 100), divide(#0, 23.1)

GROUND_TRUTH:
divide(25017, 23.1%)
====================================================================================================

Generating program...:  65%|██████▌   | 325/497 [12:44<05:05,  1.78s/it]

TEST SAMPLE 324:

PREDICTION:
divide(30.7, 47.9), multiply(#0, 100)

GROUND_TRUTH:
divide(30.7, 47.9)
====================================================================================================

Generating program...:  66%|██████▌   | 326/497 [12:45<04:27,  1.56s/it]

TEST SAMPLE 325:

PREDICTION:
add(6304, 1685)

GROUND_TRUTH:
add(170, 7819)
====================================================================================================

Generating program...:  66%|██████▌   | 327/497 [12:46<03:43,  1.31s/it]

TEST SAMPLE 326:

PREDICTION:
subtract(35.0, 32.9)

GROUND_TRUTH:
subtract(35%, 32.9%)
====================================================================================================

Generating program...:  66%|██████▌   | 328/497 [12:47<03:53,  1.38s/it]

TEST SAMPLE 327:

PREDICTION:
subtract(108.11, 118.09), divide(#0, 118.09)

GROUND_TRUTH:
subtract(108.11, 118.09), divide(#0, 118.09)
====================================================================================================

Generating program...:  66%|██████▌   | 329/497 [12:49<04:16,  1.53s/it]

TEST SAMPLE 328:

PREDICTION:
subtract(3.9, 7.6)

GROUND_TRUTH:
subtract(3.9, 7.6), divide(#0, 7.6)
====================================================================================================

Generating program...:  66%|██████▋   | 330/497 [12:50<04:02,  1.45s/it]

TEST SAMPLE 329:

PREDICTION:
subtract(2115, 2345), divide(#0, 2345), multiply(#1, 100)

GROUND_TRUTH:
subtract(2115, 2345), divide(#0, 2345)
====================================================================================================

Generating program...:  67%|██████▋   | 331/497 [12:52<03:57,  1.43s/it]

TEST SAMPLE 330:

PREDICTION:
divide(671, 2147), multiply(#0, 100)

GROUND_TRUTH:
divide(671, 2147)
====================================================================================================

Generating program...:  67%|██████▋   | 332/497 [12:53<03:44,  1.36s/it]

TEST SAMPLE 331:

PREDICTION:
subtract(0.6, 0.5)

GROUND_TRUTH:
subtract(0.6, 0.5)
====================================================================================================

Generating program...:  67%|██████▋   | 333/497 [12:57<06:16,  2.29s/it]

TEST SAMPLE 332:

PREDICTION:
greater(217.56, 296.67)

GROUND_TRUTH:
greater(217.56, 296.67)
====================================================================================================

Generating program...:  67%|██████▋   | 334/497 [12:59<05:53,  2.17s/it]

TEST SAMPLE 333:

PREDICTION:
divide(604.2, 12067.3), multiply(#0, 100)

GROUND_TRUTH:
divide(604.2, 8290.6)
====================================================================================================

Generating program...:  67%|██████▋   | 335/497 [13:00<05:07,  1.90s/it]

TEST SAMPLE 334:

PREDICTION:
add(127.1, 70.4)

GROUND_TRUTH:
subtract(127.1, 70.4)
====================================================================================================

Generating program...:  68%|██████▊   | 336/497 [13:03<05:16,  1.96s/it]

TEST SAMPLE 335:

PREDICTION:
subtract(6608, 6770), divide(#0, 6770)

GROUND_TRUTH:
subtract(6608, 6770), divide(#0, 6770)
====================================================================================================

Generating program...:  68%|██████▊   | 337/497 [13:04<04:35,  1.72s/it]

TEST SAMPLE 336:

PREDICTION:
subtract(86.42, 80.20), divide(#0, 80.20)

GROUND_TRUTH:
subtract(86.42, 80.20), divide(#0, 80.20)
====================================================================================================

Generating program...:  68%|██████▊   | 338/497 [13:05<03:53,  1.47s/it]

TEST SAMPLE 337:

PREDICTION:
subtract(1430, 927), divide(#0, 927), multiply(#1, 100)

GROUND_TRUTH:
subtract(1430, 927), divide(#0, 927)
====================================================================================================

Generating program...:  68%|██████▊   | 339/497 [13:06<03:39,  1.39s/it]

TEST SAMPLE 338:

PREDICTION:
subtract(307, 309), divide(#0, 309), multiply(#1, 100)

GROUND_TRUTH:
subtract(307, 309), divide(#0, 309)
====================================================================================================

Generating program...:  68%|██████▊   | 340/497 [13:13<08:01,  3.06s/it]

TEST SAMPLE 339:

PREDICTION:
add(165.7, 73.8), add(617.9, 184.7), divide(#0, #1), multiply(#2, 100)

GROUND_TRUTH:
divide(239.5, 802.6)
====================================================================================================

Generating program...:  69%|██████▊   | 341/497 [13:14<06:19,  2.43s/it]

TEST SAMPLE 340:

PREDICTION:
add(34, 23), add(#0, 13)

GROUND_TRUTH:
add(34, 23), add(13, #0)
====================================================================================================

Generating program...:  69%|██████▉   | 342/497 [13:16<06:09,  2.39s/it]

TEST SAMPLE 341:

PREDICTION:
divide(53, 5070), multiply(#0, 100)

GROUND_TRUTH:
divide(86, 5070)
====================================================================================================

Generating program...:  69%|██████▉   | 343/497 [13:17<05:04,  1.98s/it]

TEST SAMPLE 342:

PREDICTION:
add(762.6, 808.4), add(#0, 895.2), divide(#1, 3)

GROUND_TRUTH:
table_average(thu nhập hoạt động, none)
====================================================================================================

Generating program...:  69%|██████▉   | 344/497 [13:18<04:01,  1.58s/it]

TEST SAMPLE 343:

PREDICTION:
subtract(20.18, 16.01)

GROUND_TRUTH:
subtract(20.18, 16.01)
====================================================================================================

Generating program...:  69%|██████▉   | 345/497 [13:20<04:47,  1.89s/it]

TEST SAMPLE 344:

PREDICTION:
table_max(Revenue (VNDbn), none)

GROUND_TRUTH:
table_max(Revenue (VNDbn), none)
====================================================================================================

Generating program...:  70%|██████▉   | 346/497 [13:22<04:53,  1.95s/it]

TEST SAMPLE 345:

PREDICTION:
4.16

GROUND_TRUTH:
divide(1041, 25017)
====================================================================================================

Generating program...:  70%|██████▉   | 347/497 [13:23<04:02,  1.62s/it]

TEST SAMPLE 346:

PREDICTION:
subtract(2266, 79)

GROUND_TRUTH:
subtract(2266, 79)
====================================================================================================

Generating program...:  70%|███████   | 348/497 [13:26<04:37,  1.87s/it]

TEST SAMPLE 347:

PREDICTION:
subtract(1331, 1039), divide(#0, 1039), multiply(#1, 100)

GROUND_TRUTH:
subtract(1.331, 1.039), divide(#0, 1.039)
====================================================================================================

Generating program...:  70%|███████   | 349/497 [13:27<04:25,  1.79s/it]

TEST SAMPLE 348:

PREDICTION:
table_max(Lợi nhuận sau thuế (tỷ đồng), none), table_min(Lợi nhuận sau thuế (tỷ đồng), none), subtract(#0, #1)

GROUND_TRUTH:
table_max(Lợi nhuận sau thuế (tỷ đồng), none), table_min(Lợi nhuận sau thuế (tỷ đồng), none), subtract(#0, #1)
====================================================================================================

Generating program...:  70%|███████   | 350/497 [13:28<03:40,  1.50s/it]

TEST SAMPLE 349:

PREDICTION:
add(36609, 41879), add(#0, 47268)

GROUND_TRUTH:
add(36609, 41879), add(#0, 47268)
====================================================================================================

Generating program...:  71%|███████   | 351/497 [13:30<03:51,  1.59s/it]

TEST SAMPLE 350:

PREDICTION:
divide(5978, 1217121), multiply(#0, 100)

GROUND_TRUTH:
divide(5978, 1217121)
====================================================================================================

Generating program...:  71%|███████   | 352/497 [13:31<03:11,  1.32s/it]

TEST SAMPLE 351:

PREDICTION:
add(54821, 22402)

GROUND_TRUTH:
add(54821, 22402)
====================================================================================================

Generating program...:  71%|███████   | 353/497 [13:31<02:45,  1.15s/it]

TEST SAMPLE 352:

PREDICTION:
subtract(457, 125)

GROUND_TRUTH:
subtract(457, 125)
====================================================================================================

Generating program...:  71%|███████   | 354/497 [13:32<02:18,  1.03it/s]

TEST SAMPLE 353:

PREDICTION:
subtract(5685, 4249)

GROUND_TRUTH:
subtract(5685, 4249)
====================================================================================================

Generating program...:  71%|███████▏  | 355/497 [13:33<02:09,  1.09it/s]

TEST SAMPLE 354:

PREDICTION:
add(28207, 32634)

GROUND_TRUTH:
add(28207, 32634)
====================================================================================================

Generating program...:  72%|███████▏  | 356/497 [13:33<01:59,  1.18it/s]

TEST SAMPLE 355:

PREDICTION:
divide(16.4, 13.2)

GROUND_TRUTH:
divide(16.4, 13.2)
====================================================================================================

Generating program...:  72%|███████▏  | 357/497 [13:34<01:45,  1.33it/s]

TEST SAMPLE 356:

PREDICTION:
table_max(Lãi ròng, none)

GROUND_TRUTH:
table_max(Lãi ròng, none)
====================================================================================================

Generating program...:  72%|███████▏  | 358/497 [13:36<02:53,  1.25s/it]

TEST SAMPLE 357:

PREDICTION:
add(10543, 83), divide(#0, 1000)

GROUND_TRUTH:
add(424, 10202)
====================================================================================================

Generating program...:  72%|███████▏  | 359/497 [13:38<02:58,  1.30s/it]

TEST SAMPLE 358:

PREDICTION:
multiply(3252, 0.84)

GROUND_TRUTH:
multiply(3252, 0.84)
====================================================================================================

Generating program...:  72%|███████▏  | 360/497 [13:48<09:15,  4.05s/it]

TEST SAMPLE 359:

PREDICTION:
subtract(217.56, 100)

GROUND_TRUTH:
subtract(217.56, 100), divide(#0, 100)
====================================================================================================

Generating program...:  73%|███████▎  | 361/497 [13:50<07:42,  3.40s/it]

TEST SAMPLE 360:

PREDICTION:
subtract(434814, 382739), divide(#0, 382739), multiply(#1, 100)

GROUND_TRUTH:
subtract(434814, 382739), divide(#0, 382739)
====================================================================================================

Generating program...:  73%|███████▎  | 362/497 [13:51<05:54,  2.63s/it]

TEST SAMPLE 361:

PREDICTION:
1.5

GROUND_TRUTH:
divide(28800, 18765)
====================================================================================================

Generating program...:  73%|███████▎  | 363/497 [13:52<04:54,  2.20s/it]

TEST SAMPLE 362:

PREDICTION:
divide(55300, 1.396)

GROUND_TRUTH:
add(1, 0.396), divide(55300, #0)
====================================================================================================

Generating program...:  73%|███████▎  | 364/497 [14:03<10:30,  4.74s/it]

TEST SAMPLE 363:

PREDICTION:
subtract(588701, 685645)

GROUND_TRUTH:
subtract(685645, 588701)
====================================================================================================

Generating program...:  73%|███████▎  | 365/497 [14:04<07:46,  3.54s/it]

TEST SAMPLE 364:

PREDICTION:
add(22.5, 22.5)

GROUND_TRUTH:
add(22.5, 22.5)
====================================================================================================

Generating program...:  74%|███████▎  | 366/497 [14:08<08:22,  3.83s/it]

TEST SAMPLE 365:

PREDICTION:
table_sum(trừ phần ngắn hạn, none), subtract(0, #0)

GROUND_TRUTH:
divide(1336, 42546)
====================================================================================================

Generating program...:  74%|███████▍  | 367/497 [14:13<09:12,  4.25s/it]

TEST SAMPLE 366:

PREDICTION:
add(14.6, -5.2), add(18.1, -6.3), subtract(#1, #0), divide(#2, #0), multiply(#3, 100)

GROUND_TRUTH:
subtract(18.1, 6.3), subtract(14.6, 5.2), subtract(#0, #1), divide(#2, #1)
====================================================================================================

Generating program...:  74%|███████▍  | 368/497 [14:16<08:27,  3.93s/it]

TEST SAMPLE 367:

PREDICTION:
add(6324, 10580), divide(#0, 1000)

GROUND_TRUTH:
add(13.3, 5.4)
====================================================================================================

Generating program...:  74%|███████▍  | 369/497 [14:17<06:17,  2.95s/it]

TEST SAMPLE 368:

PREDICTION:
multiply(11.5, 9743)

GROUND_TRUTH:
multiply(11.5, 9743)
====================================================================================================

Generating program...:  74%|███████▍  | 370/497 [14:18<05:00,  2.37s/it]

TEST SAMPLE 369:

PREDICTION:
subtract(6113, 3520), divide(#0, 3520), multiply(#1, 100)

GROUND_TRUTH:
subtract(6113, 3520), divide(#0, 3520)
====================================================================================================

Generating program...:  75%|███████▍  | 371/497 [14:19<03:53,  1.85s/it]

TEST SAMPLE 370:

PREDICTION:
subtract(16711, 16700)

GROUND_TRUTH:
subtract(16711, 16700)
====================================================================================================

Generating program...:  75%|███████▍  | 372/497 [14:21<04:03,  1.95s/it]

TEST SAMPLE 371:

PREDICTION:
subtract(27789, 16711)

GROUND_TRUTH:
subtract(16700, 27789)
====================================================================================================

Generating program...:  75%|███████▌  | 373/497 [14:22<03:15,  1.58s/it]

TEST SAMPLE 372:

PREDICTION:
subtract(33.9, 32.9)

GROUND_TRUTH:
subtract(33.9, 32.9)
====================================================================================================

Generating program...:  75%|███████▌  | 374/497 [14:23<03:14,  1.58s/it]

TEST SAMPLE 373:

PREDICTION:
divide(35324, 72474), multiply(#0, 100)

GROUND_TRUTH:
divide(35324, 72474)
====================================================================================================

Generating program...:  75%|███████▌  | 375/497 [14:24<02:43,  1.34s/it]

TEST SAMPLE 374:

PREDICTION:
divide(61600, 32800)

GROUND_TRUTH:
divide(61600, 32800)
====================================================================================================

Generating program...:  76%|███████▌  | 376/497 [14:25<02:28,  1.23s/it]

TEST SAMPLE 375:

PREDICTION:
subtract(109669, 112824), divide(#0, 112824), multiply(#1, 100)

GROUND_TRUTH:
subtract(109669, 112824), divide(#0, 112824)
====================================================================================================

Generating program...:  76%|███████▌  | 377/497 [14:27<02:54,  1.46s/it]

TEST SAMPLE 376:

PREDICTION:
subtract(158578, 118314)

GROUND_TRUTH:
subtract(158578, 118314)
====================================================================================================

Generating program...:  76%|███████▌  | 378/497 [14:28<02:32,  1.28s/it]

TEST SAMPLE 377:

PREDICTION:
subtract(1.5, 1.5)

GROUND_TRUTH:
subtract(1.5, 1.5)
====================================================================================================

Generating program...:  76%|███████▋  | 379/497 [14:34<05:34,  2.84s/it]

TEST SAMPLE 378:

PREDICTION:
none

GROUND_TRUTH:
multiply(1125734, 10.91)
====================================================================================================

Generating program...:  76%|███████▋  | 380/497 [14:35<04:09,  2.13s/it]

TEST SAMPLE 379:

PREDICTION:
subtract(8581, 6113)

GROUND_TRUTH:
subtract(8581, 6113), divide(#0, 6113)
====================================================================================================

Generating program...:  77%|███████▋  | 381/497 [14:36<03:23,  1.76s/it]

TEST SAMPLE 380:

PREDICTION:
add(84, 73), add(#0, 65), divide(#1, 3)

GROUND_TRUTH:
table_average(biến động dự kiến, none)
====================================================================================================

Generating program...:  77%|███████▋  | 382/497 [14:37<03:14,  1.69s/it]

TEST SAMPLE 381:

PREDICTION:
table_average(biến động dự kiến, none)

GROUND_TRUTH:
add(24.0, 28.8), add(41.7, #0), divide(#1, 3)
====================================================================================================

Generating program...:  77%|███████▋  | 383/497 [14:42<05:05,  2.68s/it]

TEST SAMPLE 382:

PREDICTION:
add(488935, 96395), divide(83539, #0), multiply(#1, 100)

GROUND_TRUTH:
divide(83539, 1000), divide(#0, 585.3)
====================================================================================================

Generating program...:  77%|███████▋  | 384/497 [14:44<04:21,  2.31s/it]

TEST SAMPLE 383:

PREDICTION:
divide(199, 946), multiply(#0, 100)

GROUND_TRUTH:
divide(199, 946)
====================================================================================================

Generating program...:  77%|███████▋  | 385/497 [14:45<03:28,  1.86s/it]

TEST SAMPLE 384:

PREDICTION:
add(14.0, 15.9), add(#0, 17.7), add(#1, 18.5), add(#2, 17.2), divide(#3, 5)

GROUND_TRUTH:
table_average(ROE (%), none)
====================================================================================================

Generating program...:  78%|███████▊  | 386/497 [14:46<03:12,  1.74s/it]

TEST SAMPLE 385:

PREDICTION:
subtract(553, 345), divide(#0, 345), multiply(#1, 100)

GROUND_TRUTH:
subtract(553, 345), divide(#0, 345)
====================================================================================================

Generating program...:  78%|███████▊  | 387/497 [14:47<02:40,  1.46s/it]

TEST SAMPLE 386:

PREDICTION:
divide(14850, 818)

GROUND_TRUTH:
divide(14850, 818)
====================================================================================================

Generating program...:  78%|███████▊  | 388/497 [14:47<02:12,  1.22s/it]

TEST SAMPLE 387:

PREDICTION:
subtract(19038.8, 9445.09)

GROUND_TRUTH:
subtract(19038.80, 9445.09)
====================================================================================================

Generating program...:  78%|███████▊  | 389/497 [14:50<02:55,  1.62s/it]

TEST SAMPLE 388:

PREDICTION:
subtract(7205, 5977), divide(#0, 5977), multiply(#1, 100)

GROUND_TRUTH:
subtract(7205, 5977), divide(#0, 5977)
====================================================================================================

Generating program...:  78%|███████▊  | 390/497 [14:52<02:51,  1.60s/it]

TEST SAMPLE 389:

PREDICTION:
subtract(32634, 28207), divide(#0, 28207), multiply(#1, 100)

GROUND_TRUTH:
subtract(32634, 28207), divide(#0, 28207)
====================================================================================================

Generating program...:  79%|███████▊  | 391/497 [14:55<03:48,  2.16s/it]

TEST SAMPLE 390:

PREDICTION:
subtract(7205, 8310), divide(#0, 8310), multiply(#1, 100)

GROUND_TRUTH:
subtract(7205, 8310), divide(#0, 8310)
====================================================================================================

Generating program...:  79%|███████▉  | 392/497 [15:01<05:47,  3.31s/it]

TEST SAMPLE 391:

PREDICTION:
subtract(296.67, 100), divide(#0, 100), multiply(#1, 100)

GROUND_TRUTH:
subtract(296.67, 100), divide(#0, 100)
====================================================================================================

Generating program...:  79%|███████▉  | 393/497 [15:02<04:32,  2.62s/it]

TEST SAMPLE 392:

PREDICTION:
subtract(2703, 2319), divide(#0, 2319), multiply(#1, 100)

GROUND_TRUTH:
subtract(2703, 2319), divide(#0, 2319)
====================================================================================================

Generating program...:  79%|███████▉  | 394/497 [15:03<03:28,  2.02s/it]

TEST SAMPLE 393:

PREDICTION:
add(78227, 81808)

GROUND_TRUTH:
add(78227, 81808)
====================================================================================================

Generating program...:  79%|███████▉  | 395/497 [15:03<02:48,  1.65s/it]

TEST SAMPLE 394:

PREDICTION:
add(2.49, 27.47)

GROUND_TRUTH:
add(2.49, 27.47)
====================================================================================================

Generating program...:  80%|███████▉  | 396/497 [15:04<02:14,  1.33s/it]

TEST SAMPLE 395:

PREDICTION:
subtract(5119, 4929)

GROUND_TRUTH:
subtract(4929, 5119)
====================================================================================================

Generating program...:  80%|███████▉  | 397/497 [15:05<02:00,  1.20s/it]

TEST SAMPLE 396:

PREDICTION:
subtract(2371, 1945), divide(#0, 1945), multiply(#1, 100)

GROUND_TRUTH:
subtract(2371, 1945), divide(#0, 1945)
====================================================================================================

Generating program...:  80%|████████  | 398/497 [15:06<01:59,  1.21s/it]

TEST SAMPLE 397:

PREDICTION:
divide(80, 322), multiply(#0, 100)

GROUND_TRUTH:
divide(80, 322)
====================================================================================================

Generating program...:  80%|████████  | 399/497 [15:08<02:22,  1.45s/it]

TEST SAMPLE 398:

PREDICTION:
divide(563220, 3063816), multiply(#0, 100)

GROUND_TRUTH:
divide(563220, 3063816)
====================================================================================================

Generating program...:  80%|████████  | 400/497 [15:09<02:02,  1.26s/it]

TEST SAMPLE 399:

PREDICTION:
table_max(tỷ lệ xu hướng cuối cùng, none)

GROUND_TRUTH:
table_max(tỷ lệ xu hướng cuối cùng, none)
====================================================================================================

Generating program...:  81%|████████  | 401/497 [15:11<02:34,  1.61s/it]

TEST SAMPLE 400:

PREDICTION:
subtract(92975, 80848), divide(#0, 80848), multiply(#1, 100)

GROUND_TRUTH:
subtract(92975, 80848), divide(#0, 80848)
====================================================================================================

Generating program...:  81%|████████  | 402/497 [15:12<01:59,  1.26s/it]

TEST SAMPLE 401:

PREDICTION:
add(37150, 35324)

GROUND_TRUTH:
add(37150, 35324)
====================================================================================================

Generating program...:  81%|████████  | 403/497 [15:13<01:43,  1.10s/it]

TEST SAMPLE 402:

PREDICTION:
subtract(23.4, 22.7)

GROUND_TRUTH:
subtract(23.4, 22.7)
====================================================================================================

Generating program...:  81%|████████▏ | 404/497 [15:13<01:29,  1.04it/s]

TEST SAMPLE 403:

PREDICTION:
subtract(13.8, 9.9)

GROUND_TRUTH:
subtract(9.9, 13.8)
====================================================================================================

Generating program...:  81%|████████▏ | 405/497 [15:14<01:16,  1.21it/s]

TEST SAMPLE 404:

PREDICTION:
subtract(56064, 54690)

GROUND_TRUTH:
subtract(56064, 54690)
====================================================================================================

Generating program...:  82%|████████▏ | 406/497 [15:15<01:39,  1.09s/it]

TEST SAMPLE 405:

PREDICTION:
subtract(55377, 55300)

GROUND_TRUTH:
subtract(55377, 55300)
====================================================================================================

Generating program...:  82%|████████▏ | 407/497 [15:19<02:55,  1.95s/it]

TEST SAMPLE 406:

PREDICTION:
divide(849, 5424), multiply(#0, 100)

GROUND_TRUTH:
divide(849, 5424)
====================================================================================================

Generating program...:  82%|████████▏ | 408/497 [15:40<11:09,  7.52s/it]

TEST SAMPLE 407:

PREDICTION:
subtract(57.4, 51.8)

GROUND_TRUTH:
subtract(57.4, 51.8)
====================================================================================================

Generating program...:  82%|████████▏ | 409/497 [15:41<08:24,  5.73s/it]

TEST SAMPLE 408:

PREDICTION:
divide(45410, 179633), multiply(#0, 100)

GROUND_TRUTH:
divide(45410, 179633)
====================================================================================================

Generating program...:  82%|████████▏ | 410/497 [15:42<06:08,  4.23s/it]

TEST SAMPLE 409:

PREDICTION:
subtract(1840, 1730), divide(#0, 1730)

GROUND_TRUTH:
subtract(1840, 1730), divide(#0, 1730)
====================================================================================================

Generating program...:  83%|████████▎ | 411/497 [15:43<04:30,  3.15s/it]

TEST SAMPLE 410:

PREDICTION:
subtract(17.80, 9.42)

GROUND_TRUTH:
subtract(17.80, 9.42), divide(#0, 9.42)
====================================================================================================

Generating program...:  83%|████████▎ | 412/497 [15:43<03:22,  2.38s/it]

TEST SAMPLE 411:

PREDICTION:
subtract(38077.60, 31483.64)

GROUND_TRUTH:
subtract(38077.60, 31483.64)
====================================================================================================

Generating program...:  83%|████████▎ | 413/497 [15:44<02:44,  1.96s/it]

TEST SAMPLE 412:

PREDICTION:
subtract(4.1, 2.2)

GROUND_TRUTH:
subtract(2.2, 4.1), divide(#0, 4.1)
====================================================================================================

Generating program...:  83%|████████▎ | 414/497 [15:46<02:22,  1.72s/it]

TEST SAMPLE 413:

PREDICTION:
divide(38, 129), multiply(#0, 100)

GROUND_TRUTH:
divide(38, 129)
====================================================================================================

Generating program...:  84%|████████▎ | 415/497 [15:46<01:55,  1.41s/it]

TEST SAMPLE 414:

PREDICTION:
subtract(408164, 391555)

GROUND_TRUTH:
subtract(408164, 391555)
====================================================================================================

Generating program...:  84%|████████▎ | 416/497 [15:50<03:02,  2.26s/it]

TEST SAMPLE 415:

PREDICTION:
subtract(258.6, 250.0), subtract(#0, 1.4)

GROUND_TRUTH:
subtract(258.6, 250.0), subtract(#0, 1.4)
====================================================================================================

Generating program...:  84%|████████▍ | 417/497 [15:52<02:38,  1.98s/it]

TEST SAMPLE 416:

PREDICTION:
subtract(136, 133), divide(#0, 133), multiply(#1, 100)

GROUND_TRUTH:
subtract(136, 133), divide(#0, 133)
====================================================================================================

Generating program...:  84%|████████▍ | 418/497 [15:52<02:03,  1.57s/it]

TEST SAMPLE 417:

PREDICTION:
subtract(50461, 29870)

GROUND_TRUTH:
subtract(50461, 29870)
====================================================================================================

Generating program...:  84%|████████▍ | 419/497 [15:58<03:43,  2.86s/it]

TEST SAMPLE 418:

PREDICTION:
add(-5536, -38519), multiply(#0, -1)

GROUND_TRUTH:
add(5536, 38519)
====================================================================================================

Generating program...:  85%|████████▍ | 420/497 [16:00<03:19,  2.59s/it]

TEST SAMPLE 419:

PREDICTION:
subtract(911507, 938555)

GROUND_TRUTH:
subtract(938555, 911507)
====================================================================================================

Generating program...:  85%|████████▍ | 421/497 [16:01<02:32,  2.00s/it]

TEST SAMPLE 420:

PREDICTION:
add(27345, 28032)

GROUND_TRUTH:
add(27345, 28032)
====================================================================================================

Generating program...:  85%|████████▍ | 422/497 [16:02<02:10,  1.74s/it]

TEST SAMPLE 421:

PREDICTION:
table_max(EPS (VND), none), table_min(EPS (VND), none), subtract(#0, #1)

GROUND_TRUTH:
subtract(5685, 3495)
====================================================================================================

Generating program...:  85%|████████▌ | 423/497 [16:04<02:09,  1.75s/it]

TEST SAMPLE 422:

PREDICTION:
divide(182, 1430), multiply(#0, 100)

GROUND_TRUTH:
divide(182, 1430)
====================================================================================================

Generating program...:  85%|████████▌ | 424/497 [16:05<01:48,  1.48s/it]

TEST SAMPLE 423:

PREDICTION:
subtract(3971, 3888), divide(#0, 3888), multiply(#1, 100)

GROUND_TRUTH:
subtract(3971, 3888), divide(#0, 3888)
====================================================================================================

Generating program...:  86%|████████▌ | 425/497 [16:06<01:38,  1.36s/it]

TEST SAMPLE 424:

PREDICTION:
subtract(18.7, 23.3), divide(#0, 23.3), multiply(#1, 100)

GROUND_TRUTH:
subtract(18.7, 23.3), divide(#0, 23.3)
====================================================================================================

Generating program...:  86%|████████▌ | 426/497 [16:06<01:21,  1.15s/it]

TEST SAMPLE 425:

PREDICTION:
divide(1070451, 2494125)

GROUND_TRUTH:
divide(1070451, 2494125)
====================================================================================================

Generating program...:  86%|████████▌ | 427/497 [16:07<01:10,  1.01s/it]

TEST SAMPLE 426:

PREDICTION:
table_min(EPS (VND), none)

GROUND_TRUTH:
table_min(EPS (VND), none)
====================================================================================================

Generating program...:  86%|████████▌ | 428/497 [16:08<01:15,  1.10s/it]

TEST SAMPLE 427:

PREDICTION:
divide(217692, 139255)

GROUND_TRUTH:
divide(217692, 139255)
====================================================================================================

Generating program...:  86%|████████▋ | 429/497 [16:09<01:10,  1.03s/it]

TEST SAMPLE 428:

PREDICTION:
add(19.2, 20.5), add(#0, 18.0), add(#1, 18.2), add(#2, 19.3), divide(#3, 5)

GROUND_TRUTH:
table_average(OP Margin (%), none)
====================================================================================================

Generating program...:  87%|████████▋ | 430/497 [16:27<06:36,  5.92s/it]

TEST SAMPLE 429:

PREDICTION:
subtract(203.87, 161.9)

GROUND_TRUTH:
subtract(203.87, 161.90)
====================================================================================================

Generating program...:  87%|████████▋ | 431/497 [16:29<05:28,  4.98s/it]

TEST SAMPLE 430:

PREDICTION:
divide(173000, 503000), multiply(#0, 100)

GROUND_TRUTH:
divide(173000, 503000)
====================================================================================================

Generating program...:  87%|████████▋ | 432/497 [16:32<04:29,  4.15s/it]

TEST SAMPLE 431:

PREDICTION:
subtract(7800, 7767)

GROUND_TRUTH:
subtract(7800, 7767)
====================================================================================================

Generating program...:  87%|████████▋ | 433/497 [16:38<05:05,  4.78s/it]

TEST SAMPLE 432:

PREDICTION:
subtract(1487, 1373)

GROUND_TRUTH:
subtract(875, 848)
====================================================================================================

Generating program...:  87%|████████▋ | 434/497 [16:46<05:59,  5.70s/it]

TEST SAMPLE 433:

PREDICTION:
divide(5, 6.2)

GROUND_TRUTH:
divide(5, 6.2)
====================================================================================================

Generating program...:  88%|████████▊ | 435/497 [16:46<04:22,  4.23s/it]

TEST SAMPLE 434:

PREDICTION:
add(5.3, 7.2), divide(#0, 2)

GROUND_TRUTH:
table_average(Các công cụ cho vay thương mại có cấu trúc, none)
====================================================================================================

Generating program...:  88%|████████▊ | 436/497 [16:51<04:27,  4.39s/it]

TEST SAMPLE 435:

PREDICTION:
multiply(9.5, 33), divide(#0, 100)

GROUND_TRUTH:
multiply(9.5, 0.33)
====================================================================================================

Generating program...:  88%|████████▊ | 437/497 [16:52<03:17,  3.29s/it]

TEST SAMPLE 436:

PREDICTION:
add(1597, 816)

GROUND_TRUTH:
add(1597, 816)
====================================================================================================

Generating program...:  88%|████████▊ | 438/497 [16:58<04:06,  4.17s/it]

TEST SAMPLE 437:

PREDICTION:
add(57, 26), add(#0, 22), add(#1, 19), add(#2, 9), add(#3, 8), add(#4, 7), add(#5, 63), add(#6, 81), divide(19, #7)

GROUND_TRUTH:
add(63, 81), divide(19, #0)
====================================================================================================

Generating program...:  88%|████████▊ | 439/497 [16:59<03:02,  3.14s/it]

TEST SAMPLE 438:

PREDICTION:
add(1344, 1282), add(#0, 1018), divide(#1, 3)

GROUND_TRUTH:
table_average(lợi nhuận hoạt động, none)
====================================================================================================

Generating program...:  89%|████████▊ | 440/497 [17:00<02:20,  2.47s/it]

TEST SAMPLE 439:

PREDICTION:
subtract(3971, 3888), divide(#0, 3888), multiply(#1, 100)

GROUND_TRUTH:
subtract(3971, 3888), divide(#0, 3888)
====================================================================================================

Generating program...:  89%|████████▊ | 441/497 [17:00<01:45,  1.89s/it]

TEST SAMPLE 440:

PREDICTION:
multiply(4063, 0.404)

GROUND_TRUTH:
multiply(4063, 0.404)
====================================================================================================

Generating program...:  89%|████████▉ | 442/497 [17:01<01:30,  1.64s/it]

TEST SAMPLE 441:

PREDICTION:
divide(22, 158), multiply(#0, 100)

GROUND_TRUTH:
divide(22, 158)
====================================================================================================

Generating program...:  89%|████████▉ | 443/497 [17:02<01:11,  1.33s/it]

TEST SAMPLE 442:

PREDICTION:
subtract(63658, 7528)

GROUND_TRUTH:
subtract(63658, 7528)
====================================================================================================

Generating program...:  89%|████████▉ | 444/497 [17:04<01:26,  1.64s/it]

TEST SAMPLE 443:

PREDICTION:
subtract(101.88, 93.21), divide(#0, 101.88), multiply(#1, 100)

GROUND_TRUTH:
subtract(101.88, 93.21), divide(#0, 93.21)
====================================================================================================

Generating program...:  90%|████████▉ | 445/497 [17:05<01:10,  1.35s/it]

TEST SAMPLE 444:

PREDICTION:
subtract(52.04, 22.29)

GROUND_TRUTH:
subtract(52, 22.3)
====================================================================================================

Generating program...:  90%|████████▉ | 446/497 [17:06<01:01,  1.21s/it]

TEST SAMPLE 445:

PREDICTION:
subtract(1781, 1328)

GROUND_TRUTH:
subtract(1781, 1328)
====================================================================================================

Generating program...:  90%|████████▉ | 447/497 [17:07<00:55,  1.11s/it]

TEST SAMPLE 446:

PREDICTION:
subtract(2872, 1713)

GROUND_TRUTH:
subtract(2872, 1713)
====================================================================================================

Generating program...:  90%|█████████ | 448/497 [17:08<00:49,  1.01s/it]

TEST SAMPLE 447:

PREDICTION:
table_min(OP Margin (%), none)

GROUND_TRUTH:
table_min(OP Margin (%), none)
====================================================================================================

Generating program...:  90%|█████████ | 449/497 [17:10<01:03,  1.32s/it]

TEST SAMPLE 448:

PREDICTION:
subtract(572.93, 527.37), divide(#0, 527.37), multiply(#1, 100)

GROUND_TRUTH:
subtract(572.93, 527.37), divide(#0, 527.37)
====================================================================================================

Generating program...:  91%|█████████ | 450/497 [17:11<01:01,  1.32s/it]

TEST SAMPLE 449:

PREDICTION:
subtract(29.9, 13.5), divide(#0, 13.5), multiply(#1, 100)

GROUND_TRUTH:
subtract(29.9, 13.5), divide(#0, 13.5)
====================================================================================================

Generating program...:  91%|█████████ | 451/497 [17:12<00:57,  1.24s/it]

TEST SAMPLE 450:

PREDICTION:
subtract(1781, 1675), divide(#0, 1675), multiply(#1, 100)

GROUND_TRUTH:
subtract(1781, 1675), divide(#0, 1675)
====================================================================================================

Generating program...:  91%|█████████ | 452/497 [17:13<00:46,  1.04s/it]

TEST SAMPLE 451:

PREDICTION:
subtract(201, 100)

GROUND_TRUTH:
subtract(201, 100)
====================================================================================================

Generating program...:  91%|█████████ | 453/497 [17:13<00:42,  1.03it/s]

TEST SAMPLE 452:

PREDICTION:
table_max(Lợi nhuận hoạt động (tỷ đồng), none)

GROUND_TRUTH:
table_max(Lợi nhuận hoạt động (tỷ đồng), none)
====================================================================================================

Generating program...:  91%|█████████▏| 454/497 [17:14<00:37,  1.14it/s]

TEST SAMPLE 453:

PREDICTION:
subtract(12.4, 10.6)

GROUND_TRUTH:
subtract(10.6, 12.4), divide(#0, 12.4)
====================================================================================================

Generating program...:  92%|█████████▏| 455/497 [17:21<01:58,  2.82s/it]

TEST SAMPLE 454:

PREDICTION:
multiply(13, 26.93), multiply(11, 33.32), subtract(#1, #0)

GROUND_TRUTH:
multiply(11, 33.32), multiply(13, 26.93), subtract(#0, #1)
====================================================================================================

Generating program...:  92%|█████████▏| 456/497 [17:22<01:33,  2.29s/it]

TEST SAMPLE 455:

PREDICTION:
subtract(309, 307), divide(#0, 309), multiply(#1, 100)

GROUND_TRUTH:
subtract(307, 309), divide(#0, 309)
====================================================================================================

Generating program...:  92%|█████████▏| 457/497 [17:23<01:15,  1.88s/it]

TEST SAMPLE 456:

PREDICTION:
subtract(458, 342), divide(#0, 342), multiply(#1, 100)

GROUND_TRUTH:
subtract(458, 342), divide(#0, 342)
====================================================================================================

Generating program...:  92%|█████████▏| 458/497 [17:24<01:04,  1.65s/it]

TEST SAMPLE 457:

PREDICTION:
divide(57, 70)

GROUND_TRUTH:
divide(57, 70)
====================================================================================================

Generating program...:  92%|█████████▏| 459/497 [17:43<04:15,  6.72s/it]

TEST SAMPLE 458:

PREDICTION:
subtract(3871, 3786), divide(#0, 3786), multiply(#1, 100)

GROUND_TRUTH:
subtract(3871, 3786), divide(#0, 3786)
====================================================================================================

Generating program...:  93%|█████████▎| 460/497 [17:44<03:05,  5.01s/it]

TEST SAMPLE 459:

PREDICTION:
table_average(OP (VNDbn), none)

GROUND_TRUTH:
table_average(OP (VNDbn), none)
====================================================================================================

Generating program...:  93%|█████████▎| 461/497 [17:49<03:00,  5.02s/it]

TEST SAMPLE 460:

PREDICTION:
divide(28383, 0.66), divide(12099, 0.40), subtract(#1, #0), divide(#2, #0), multiply(#3, 100)

GROUND_TRUTH:
multiply(66%, 28383), multiply(40%, 12099), subtract(#0, #1), divide(#2, #1)
====================================================================================================

Generating program...:  93%|█████████▎| 462/497 [17:51<02:24,  4.13s/it]

TEST SAMPLE 461:

PREDICTION:
subtract(2355, 1781), divide(#0, 1781), multiply(#1, 100)

GROUND_TRUTH:
subtract(2355, 1781), divide(#0, 1781)
====================================================================================================

Generating program...:  93%|█████████▎| 463/497 [17:52<01:45,  3.10s/it]

TEST SAMPLE 462:

PREDICTION:
divide(61535, 54533)

GROUND_TRUTH:
divide(61535, 54533)
====================================================================================================

Generating program...:  93%|█████████▎| 464/497 [17:53<01:20,  2.45s/it]

TEST SAMPLE 463:

PREDICTION:
add(2786, 2546), add(#0, 1899)

GROUND_TRUTH:
table_sum(chi phí phát triển phát sinh trong kỳ, none)
====================================================================================================

Generating program...:  94%|█████████▎| 465/497 [17:53<01:01,  1.93s/it]

TEST SAMPLE 464:

PREDICTION:
subtract(1843, 1149)

GROUND_TRUTH:
subtract(1843, 1149)
====================================================================================================

Generating program...:  94%|█████████▍| 466/497 [17:54<00:48,  1.57s/it]

TEST SAMPLE 465:

PREDICTION:
subtract(29.9, 13.5)

GROUND_TRUTH:
subtract(29.9 , 13.5 )
====================================================================================================

Generating program...:  94%|█████████▍| 467/497 [17:55<00:42,  1.40s/it]

TEST SAMPLE 466:

PREDICTION:
subtract(14.7, 9.5), divide(#0, 14.7), multiply(#1, 100)

GROUND_TRUTH:
subtract(9.5, 14.7), divide(#0, 14.7)
====================================================================================================

Generating program...:  94%|█████████▍| 468/497 [17:56<00:36,  1.27s/it]

TEST SAMPLE 467:

PREDICTION:
subtract(29.7, 21.0), divide(#0, 21.0), multiply(#1, 100)

GROUND_TRUTH:
subtract(29.7, 21.0), divide(#0, 21.0)
====================================================================================================

Generating program...:  94%|█████████▍| 469/497 [17:57<00:33,  1.21s/it]

TEST SAMPLE 468:

PREDICTION:
subtract(22.97, 22)

GROUND_TRUTH:
subtract(22.97, 22)
====================================================================================================

Generating program...:  95%|█████████▍| 470/497 [18:04<01:21,  3.00s/it]

TEST SAMPLE 469:

PREDICTION:
divide(21, 14.6)

GROUND_TRUTH:
divide(21, 14.6)
====================================================================================================

Generating program...:  95%|█████████▍| 471/497 [18:05<00:59,  2.29s/it]

TEST SAMPLE 470:

PREDICTION:
subtract(25, 21.1)

GROUND_TRUTH:
subtract(25, 21.1)
====================================================================================================

Generating program...:  95%|█████████▍| 472/497 [18:06<00:45,  1.81s/it]

TEST SAMPLE 471:

PREDICTION:
table_max(LNST ( tỷ đồng), none)

GROUND_TRUTH:
table_max(LNST ( tỷ đồng), none)
====================================================================================================

Generating program...:  95%|█████████▌| 473/497 [18:11<01:11,  2.97s/it]

TEST SAMPLE 472:

PREDICTION:
subtract(3885, 1724), divide(#0, 1724), multiply(#1, 100)

GROUND_TRUTH:
subtract(3885, 1724), divide(#0, 1724)
====================================================================================================

Generating program...:  95%|█████████▌| 474/497 [18:19<01:41,  4.43s/it]

TEST SAMPLE 473:

PREDICTION:
divide(1784, 0.32)

GROUND_TRUTH:
divide(1784, 0.32)
====================================================================================================

Generating program...:  96%|█████████▌| 475/497 [18:20<01:13,  3.34s/it]

TEST SAMPLE 474:

PREDICTION:
add(40000, 28000)

GROUND_TRUTH:
add(40000, 28000)
====================================================================================================

Generating program...:  96%|█████████▌| 476/497 [18:21<00:53,  2.56s/it]

TEST SAMPLE 475:

PREDICTION:
divide(5.3, 17.7)

GROUND_TRUTH:
divide(5.3, 17.7)
====================================================================================================

Generating program...:  96%|█████████▌| 477/497 [18:21<00:39,  1.97s/it]

TEST SAMPLE 476:

PREDICTION:
multiply(18304, 1.72)

GROUND_TRUTH:
multiply(18304, 1.72)
====================================================================================================

Generating program...:  96%|█████████▌| 478/497 [18:22<00:32,  1.70s/it]

TEST SAMPLE 477:

PREDICTION:
divide(1751, 25017), multiply(#0, 100)

GROUND_TRUTH:
divide(1751, 25017)
====================================================================================================

Generating program...:  96%|█████████▋| 479/497 [18:24<00:30,  1.70s/it]

TEST SAMPLE 478:

PREDICTION:
divide(1095.6, 2719.3), multiply(#0, 100)

GROUND_TRUTH:
divide(1095.6, 2719.3)
====================================================================================================

Generating program...:  97%|█████████▋| 480/497 [18:25<00:23,  1.38s/it]

TEST SAMPLE 479:

PREDICTION:
subtract(8756, 9554)

GROUND_TRUTH:
subtract(8756, 9554)
====================================================================================================

Generating program...:  97%|█████████▋| 481/497 [18:26<00:21,  1.33s/it]

TEST SAMPLE 480:

PREDICTION:
divide(3698, 7034), multiply(#0, 100)

GROUND_TRUTH:
divide(3698, 7034)
====================================================================================================

Generating program...:  97%|█████████▋| 482/497 [18:31<00:34,  2.28s/it]

TEST SAMPLE 481:

PREDICTION:
subtract(46, 9.9)

GROUND_TRUTH:
subtract(46, 9.9)
====================================================================================================

Generating program...:  97%|█████████▋| 483/497 [18:38<00:53,  3.79s/it]

TEST SAMPLE 482:

PREDICTION:
divide(242, 177947), multiply(#0, 100)

GROUND_TRUTH:
add(242, 177947), divide(242, #0)
====================================================================================================

Generating program...:  97%|█████████▋| 484/497 [18:49<01:16,  5.90s/it]

TEST SAMPLE 483:

PREDICTION:
add(40, 0)

GROUND_TRUTH:
divide(40000, 1843)
====================================================================================================

Generating program...:  98%|█████████▊| 485/497 [18:50<00:53,  4.44s/it]

TEST SAMPLE 484:

PREDICTION:
subtract(6113, 3520), divide(#0, 3520), multiply(#1, 100)

GROUND_TRUTH:
subtract(6113, 3520), divide(#0, 3520)
====================================================================================================

Generating program...:  98%|█████████▊| 486/497 [18:50<00:36,  3.34s/it]

TEST SAMPLE 485:

PREDICTION:
add(3608, 3783), add(#0, 4063), add(#1, 3888)

GROUND_TRUTH:
add(3608, 3783), add(#0, 4063), add(#1, 3888)
====================================================================================================

Generating program...:  98%|█████████▊| 487/497 [18:53<00:31,  3.10s/it]

TEST SAMPLE 486:

PREDICTION:
subtract(39.2, 28.2), divide(#0, 28.2), multiply(#1, 100)

GROUND_TRUTH:
subtract(39.2, 28.2), divide(#0, 28.2)
====================================================================================================

Generating program...:  98%|█████████▊| 488/497 [18:55<00:23,  2.63s/it]

TEST SAMPLE 487:

PREDICTION:
divide(239.5, 802.6), multiply(#0, 100)

GROUND_TRUTH:
divide(239.5, 802.6)
====================================================================================================

Generating program...:  98%|█████████▊| 489/497 [18:55<00:16,  2.03s/it]

TEST SAMPLE 488:

PREDICTION:
subtract(705.4, 696.3), divide(#0, 696.3)

GROUND_TRUTH:
subtract(705.4, 696.3), divide(#0, 696.3)
====================================================================================================

Generating program...:  99%|█████████▊| 490/497 [18:57<00:12,  1.81s/it]

TEST SAMPLE 489:

PREDICTION:
divide(341, 3971), multiply(#0, 100)

GROUND_TRUTH:
divide(341, 3971)
====================================================================================================

Generating program...:  99%|█████████▉| 491/497 [18:57<00:08,  1.46s/it]

TEST SAMPLE 490:

PREDICTION:
subtract(19.3, 18.2)

GROUND_TRUTH:
subtract(19.3, 18.2), divide(#0, 18.2)
====================================================================================================

Generating program...:  99%|█████████▉| 492/497 [19:04<00:15,  3.15s/it]

TEST SAMPLE 491:

PREDICTION:
add(27.0, 37.2), add(#0, 35.8)

GROUND_TRUTH:
add(15.1, 63.1), add(#0, 14.6)
====================================================================================================

Generating program...:  99%|█████████▉| 493/497 [19:06<00:10,  2.67s/it]

TEST SAMPLE 492:

PREDICTION:
divide(131.8, 148.8), multiply(#0, 100)

GROUND_TRUTH:
divide(131.8, 148.8)
====================================================================================================

Generating program...:  99%|█████████▉| 494/497 [19:07<00:06,  2.25s/it]

TEST SAMPLE 493:

PREDICTION:
add(29710, 32662), add(#0, 35374), divide(#1, 3)

GROUND_TRUTH:
add(29710, 32662), add(#0, 35374), divide(#1, 3)
====================================================================================================

Generating program...: 100%|█████████▉| 495/497 [19:08<00:03,  1.81s/it]

TEST SAMPLE 494:

PREDICTION:
subtract(962, 788), divide(#0, 788), multiply(#1, 100)

GROUND_TRUTH:
subtract(962, 788), divide(#0, 788)
====================================================================================================

Generating program...: 100%|█████████▉| 496/497 [19:09<00:01,  1.59s/it]

TEST SAMPLE 495:

PREDICTION:
divide(145, 586), multiply(#0, 100)

GROUND_TRUTH:
divide(145, 586)
====================================================================================================

Generating program...: 100%|██████████| 497/497 [19:11<00:00,  2.32s/it]

TEST SAMPLE 496:

PREDICTION:
multiply(1041, 100), divide(#0, 29.2)

GROUND_TRUTH:
divide(1041, 0.292)
====================================================================================================

In [8]:
import sys
sys.path.insert(0, "../../evaluate")  # fallback: relative path when running locally

from scorer import evaluate_dataframe  # noqa: E402

# scorer.py is the shared ViNumQA evaluator (notebooks/evaluate/scorer.py): it
# ports FinQA's official evaluation protocol (sympy-based symbolic Program
# Accuracy, table-row-lookup-aware Execution Accuracy) instead of a
# hand-rolled parser, and correctly executes table_*(row_name, none) calls by
# looking up the named row in the raw table -- which the previous in-notebook
# parser could not do at all (it treated table_* arguments as raw numbers).

In [9]:
df_scored, summary = evaluate_dataframe(
    df,
    generated_col="generated_program",   # cột bạn đang ghi output model vào
    gold_program_col="program",
    gold_answer_col="answer",
    table_col="table_raw",
)

print(summary)  # {'program_accuracy': ..., 'execution_accuracy': ...}

{'program_accuracy': 0.44668008048289737, 'execution_accuracy': 0.5050301810865191}