In [1]:
import pandas as pd
from pathlib import Path
from tabulate import tabulate

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / ".git").exists() and PROJECT_ROOT != PROJECT_ROOT.parent:
    PROJECT_ROOT = PROJECT_ROOT.parent

df = pd.read_json(PROJECT_ROOT / "datasets" / "ViNumQA" / "test.json")
df.sample(n=5)

,pre_text,table,post_text,id,qa
0,[thuyết minh báo cáo tài chính hợp nhất ( tiếp...,[[các thành phần của ảnh hưởng lũy kế của việc...,[.],HIG/2004/page_140.pdf-3,{'question': 'Sự thay đổi trong thu nhập ròng ...
48,[.],"[[Phương pháp, Giá trị hợp lý mỗi cổ phiếu, Tỉ...","[mặc dù, hiện tại ree đang được giao dịch ở mứ...",masvn/2021/2021132-VNREE_Updatereport_Hold_MAS...,{'question': 'Giá trị lớn nhất trong các số li...
21,[mục lục phần ii mục 5 thị trường vốn cổ phần ...,"[[2012:, cao, thấp], [ngày 1 tháng 1 năm 2012 ...",[.],MKTX/2012/page_42.pdf-3,{'question': 'Giá thấp nhất của cổ phiếu MKTX ...
185,"[năm 2019, hpg đã cung cấp gần 2,8 triệu tấn t...","[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",[.],masvn/2020/2020056-HPG_Companynote_MAS22.05.20...,{'question': 'Dự phóng sản lượng thép xây dựng...
344,"[kết quả kinh doanh 1h19, kqkd 1h19 của dhg ch...","[[FY (Dec.), 2015, 2016, 2017, 2018, 2019F], [...",[.],masvn/2020/2020030-MAS_Pharmaceutical_Industry...,{'question': 'Doanh thu (Revenue) lớn nhất của...

In [2]:
len(df)

497

In [3]:
def formatting_pre_text(sample):
    return "\n".join(sample["pre_text"])

def formatting_table(sample):
    return tabulate(sample["table"][1:], headers=sample["table"][0], tablefmt="github")

def formatting_post_text(sample):
    return "\n".join(sample["post_text"])

def processing_input_question(sample):
    return sample["qa"]["question"]

def processing_program_content(sample):
    return sample["qa"]["program"]

def processing_answer_content(sample):
    return sample["qa"]["exe_ans"]

df["pre_text_processed"] = df.apply(lambda x: formatting_pre_text(x), axis=1)
df["post_text_processed"] = df.apply(lambda x: formatting_post_text(x), axis=1)
df["table_processed"] = df.apply(lambda x: formatting_table(x), axis=1)
df["table_raw"] = df["table"]  # keep raw rows for table_* row-name lookup at eval time
df["input_question"] = df.apply(lambda x: processing_input_question(x), axis=1)
df["program_processed"] = df.apply(lambda x: processing_program_content(x), axis=1)
df["answer_processed"] = df.apply(lambda x: processing_answer_content(x), axis=1)
df.sample(n=5)

,pre_text,table,post_text,id,qa,pre_text_processed,post_text_processed,table_processed,table_raw,input_question,program_processed,answer_processed
56,"[sử dụng phương pháp p/b và rnav để định giá, ...","[[Năm tài chính (31/12), 2018, 2019, 2020 (Dự ...",[.],masvn/2020/2020193-VN_IndustrialRealEstate_Upd...,{'question': 'Tính trung bình biên lãi hoạt độ...,"sử dụng phương pháp p/b và rnav để định giá, c...",.,| Năm tài chính (31/12) | 2018 | 2019 | ...,"[[Năm tài chính (31/12), 2018, 2019, 2020 (Dự ...",Tính trung bình biên lãi hoạt động (%) của BCM...,"table_average(Biên lãi hoạt động (%), none)",27.06667
43,[biểu đồ hiệu suất bảng dưới đây so sánh tổng ...,"[[, 2008, 2009, 2010, 2011, 2012], [masco, $ 5...","[vào tháng 7 năm 2007 , hội đồng quản trị của ...",MAS/2012/page_26.pdf-3,{'question': 'tỷ lệ lợi tức tích lũy phần trăm...,biểu đồ hiệu suất bảng dưới đây so sánh tổng l...,"vào tháng 7 năm 2007 , hội đồng quản trị của c...",| ...,"[[, 2008, 2009, 2010, 2011, 2012], [masco, $ 5...",tỷ lệ lợi tức tích lũy phần trăm của Masco tro...,"subtract(92.49, 100), divide(#0, 100)",-0.0751
254,"[năm 2019, hpg đã cung cấp gần 2,8 triệu tấn t...","[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",[.],masvn/2020/2020056-HPG_Companynote_MAS22.05.20...,{'question': 'Lãi ròng của HPG trong năm 2020 ...,"năm 2019, hpg đã cung cấp gần 2,8 triệu tấn th...",.,| (Tỷ đồng) | FY 2015 | FY 2016 |...,"[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",Lãi ròng của HPG trong năm 2020 dự kiến tăng b...,"subtract(10015, 7528), divide(#0, 7528)",0.33037
248,[biểu đồ hiệu suất hoạt động biểu đồ sau đây s...,"[[, 3/31/2007, 3/31/2008, 3/31/2009, 3/31/2010...",[biểu đồ này không phải là “tài liệu chào mời”...,ABMD/2012/page_41.pdf-4,{'question': 'Tỷ suất lợi nhuận đầu tư (ROI) c...,biểu đồ hiệu suất hoạt động biểu đồ sau đây so...,biểu đồ này không phải là “tài liệu chào mời” ...,| ...,"[[, 3/31/2007, 3/31/2008, 3/31/2009, 3/31/2010...",Tỷ suất lợi nhuận đầu tư (ROI) của khoản đầu t...,"subtract(99.02, 100), divide(#0, 100)",-0.0098
241,[báo cáo thường niên 2018 21 mục 3 : thủ tục p...,"[[kỳ báo cáo, số cổ phiếu đã mua, giá trung bì...",[______________________ k/a : không áp dụng * ...,SNA/2018/page_31.pdf-2,{'question': 'Tổng giá trị cổ phiếu mua vào tr...,báo cáo thường niên 2018 21 mục 3 : thủ tục ph...,______________________ k/a : không áp dụng * c...,| kỳ báo cáo | số cổ phiếu đã mua...,"[[kỳ báo cáo, số cổ phiếu đã mua, giá trung bì...",Tổng giá trị cổ phiếu mua vào trong tháng 10 n...,"multiply(90000, 149.28)",13435200.0

In [4]:
df = df[["pre_text_processed", "table_processed", "table_raw", "post_text_processed", "input_question", "program_processed", "answer_processed"]]
df.columns = ["pre_text", "table", "table_raw", "post_text", "question", "program", "answer"]
df["generated_program"] = ""
df["calculated_program"] = ""
df

,pre_text,table,table_raw,post_text,question,program,answer,generated_program,calculated_program
0,thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,| các thành phần của ảnh hưởng lũy kế của việc...,[[các thành phần của ảnh hưởng lũy kế của việc...,.,Sự thay đổi trong thu nhập ròng từ hiệu ứng tí...,"add(30, 1)",31.0,,
1,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,"Theo dự phóng, doanh thu và lợi nhuận ròng quý...","subtract(9829, 642)",9187.0,,
2,"sử dụng phương pháp p/b và rnav để định giá, c...",| Năm tài chính (31/12) | 2016 | 2017 | ...,"[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",.,IDC có bao nhiêu ha quỹ đất sẵn sàng cho thuê ...,"add(495, 398)",893.0,,
3,27/10/13 26/10/14 25/10/15 30/10/16 29/10/17 2...,| | 27/10/2013 |...,"[[, 27/10/2013, 26/10/2014, 25/10/2015, 30/10/...",.,Tỷ suất lợi nhuận trên đầu tư (ROI) của Applie...,"subtract(96.67, 100), divide(#0, 100)",-0.0333,,
4,thông tin tài chính bổ sung hiệu suất cổ phiếu...,| | 12/26/08 | ...,"[[, 12/26/08, 12/31/09, 12/31/10, 12/31/11, 12...",218 báo cáo thường niên năm 2013 của goldman s...,tỷ lệ lợi nhuận tích lũy tổng cộng theo phần t...,"subtract(248.36, 100), divide(#0, 100)",1.4836,,
...,...,...,...,...,...,...,...,...,...
492,thuyết minh báo cáo tài chính hợp nhất năm 201...,| ...,"[[, 2008, 2007], [Số dư đầu kỳ, $ 134.8, $ 266...",trong tổng số lợi ích thuế chưa được ghi nhận ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575,,
493,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Doanh thu trung bình từ năm tài chính 2017 đến...,"add(29710, 32662), add(#0, 35374), divide(#1, 3)",32582.0,,
494,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Tính phần trăm thay đổi EPS từ năm 2020 đến 2021.,"subtract(962, 788), divide(#0, 788)",0.22081,,
495,"trong quá trình kinh doanh thông thường, dựa t...",| ( đơn vị: nghìn ) | diện tích ròng chưa ph...,"[[( đơn vị: nghìn ), diện tích ròng chưa phát ...",( a ) một giếng khoan thăm dò được lên kế hoạc...,Tỷ lệ phần trăm diện tích đất chưa phát triển ...,"divide(145, 586)",0.24744,,
496,.,| | 1Q18 | 1Q19 | YoY (%...,"[[, 1Q18, 1Q19, YoY (%), Kế hoạch 2019 (%)], [...",doanh thu tăng trưởng trong quý đầu năm có phầ...,"dựa trên kết quả quý 1 năm 2019, lợi nhuận sau...","divide(1041, 0.292)",3565.06849,,

In [5]:
SYSTEM_MESSAGE = """You are a financial analysis AI. Your task is to generate a sequential computation program to answer the question, based on the provided context.

### LIST OF 10 VALID OPERATORS:

1. add(a, b) -> a + b
2. subtract(a, b) -> a - b
3. multiply(a, b) -> a * b
4. divide(a, b) -> a / b
5. exp(a, b) -> a^b
6. greater(a, b) -> 1.0 if a > b, else 0.0
7. table_sum(row_name, none) -> sum of the numeric values in the table row named `row_name`
8. table_average(row_name, none) -> arithmetic mean of the numeric values in the table row named `row_name`
9. table_max(row_name, none) -> maximum of the numeric values in the table row named `row_name`
10. table_min(row_name, none) -> minimum of the numeric values in the table row named `row_name`

### RULES:
- Do not use free-form mathematical symbols ("+", "-", "*", "/") outside of parentheses. Every calculation must use one of the 10 operators above.
- table_* operators take exactly two arguments: the row name (copied exactly as it appears as the first cell of the target row) and the literal `none` (e.g. table_max(Lãi ròng, none)), never a list of numeric values.
- Do not perform mental calculations or provide explanations. The output must contain only the program string.
- Reference the result of a previous step using #0 (step 1), #1 (step 2), etc. Steps are separated by commas.
- Preserve the original number format from the context. If a value is missing, use 'none'."""

USER_MESSAGE_FRAME = """### CONTEXT:
[TEXT BEFORE TABLE]
{pre_text}
 
[TABLE]
{table}
 
[TEXT AFTER TABLE]
{post_text}
 
### QUESTION:
{question}
 
### PROGRAM:"""

# 3 few-shot demonstrations sampled from train.json, one per evidence type
# (Table Only / Text Only / Table & Text), following the ViNumQA task's
# own categorization (see VLSP 2025 NumQA paper, Section 3.3).
# The "table" field of each shot is pre-rendered to the same GitHub-markdown
# format that `formatting_table` produces for the real data, so the few-shot
# demonstrations are formatted identically to the actual queries.
FEW_SHOT_EXAMPLES = [
    {
        # Table Only (train idx 1959): answer is derived purely from two table cells.
        "pre_text": "ph\u1ee5 l\u1ee5c iv ace limited v\u00e0 c\u00e1c c\u00f4ng ty con th\u00f4ng tin b\u1ed5 sung v\u1ec1 ph\u00ed t\u00e1i b\u1ea3o hi\u1ec3m thu \u0111\u01b0\u1ee3c cho c\u00e1c n\u0103m k\u1ebft th\u00fac ng\u00e0y 31 th\u00e1ng 12 n\u0103m 2010, 2009 v\u00e0 2008 (t\u00ednh b\u1eb1ng tri\u1ec7u \u0111\u00f4 la m\u1ef9, ngo\u1ea1i tr\u1eeb t\u1ef7 l\u1ec7 ph\u1ea7n tr\u0103m) s\u1ed1 ti\u1ec1n tr\u1ef1c ti\u1ebfp nh\u01b0\u1ee3ng cho c\u00e1c c\u00f4ng ty nh\u1eadn t\u1eeb c\u00e1c c\u00f4ng ty kh\u00e1c s\u1ed1 ti\u1ec1n r\u00f2ng t\u1ef7 l\u1ec7 ph\u1ea7n tr\u0103m s\u1ed1 ti\u1ec1n nh\u1eadn \u0111\u01b0\u1ee3c tr\u00ean.",
        "table": (
            "|   cho c\u00e1c n\u0103m k\u1ebft th\u00fac ng\u00e0y 31 th\u00e1ng 12 n\u0103m 2010, 2009 v\u00e0 2008 (t\u00ednh b\u1eb1ng tri\u1ec7u \u0111\u00f4 la M\u1ef9, ngo\u1ea1i tr\u1eeb t\u1ef7 l\u1ec7 ph\u1ea7n tr\u0103m) | s\u1ed1 ti\u1ec1n tr\u1ef1c ti\u1ebfp   | nh\u01b0\u1ee3ng cho c\u00e1c c\u00f4ng ty kh\u00e1c   | nh\u1eadn t\u1eeb c\u00e1c c\u00f4ng ty kh\u00e1c   | s\u1ed1 ti\u1ec1n r\u00f2ng   | t\u1ef7 l\u1ec7 ph\u1ea7n tr\u0103m s\u1ed1 ti\u1ec1n nh\u1eadn \u0111\u01b0\u1ee3c tr\u00ean s\u1ed1 ti\u1ec1n r\u00f2ng   |\n"
            "|----------------------------------------------------------------------------------------------------------------------|---------------------|-------------------------------|----------------------------|----------------|-------------------------------------------------------|\n"
            "|                                                                                                                 2010 | $ 15780             | $ 5792                        | $ 3516                     | $ 13504        | 26% ( 26 % )                                          |\n"
            "|                                                                                                                 2009 | $ 15415             | $ 5943                        | $ 3768                     | $ 13240        | 28% ( 28 % )                                          |\n"
            "|                                                                                                                 2008 | $ 16087             | $ 6144                        | $ 3260                     | $ 13203        | 25% ( 25 % )                                          |"
        ),
        "post_text": ".",
        "question": "S\u1ef1 kh\u00e1c bi\u1ec7t gi\u1eefa s\u1ed1 ti\u1ec1n chuy\u1ec3n giao v\u00e0 nh\u1eadn chuy\u1ec3n giao trong n\u0103m 2010 l\u00e0 bao nhi\u00eau?",
        "program": "subtract(5792, 3516)",
    },
    {
        # Text Only (train idx 93): the supplied table (VHM financial summary) is
        # irrelevant to the question; the program only uses numbers from pre_text.
        "pre_text": "h\u1ec7 s\u1ed1 kh\u1ea3 n\u0103ng thanh to\u00e1n l\u00e3i vay c\u0169ng t\u0103ng cao \u0111\u1ea1t m\u1ee9c 13.2 l\u1ea7n, so v\u1edbi ch\u1ec9 10.3 l\u1ea7n c\u00f9ng k\u1ef3.",
        "table": (
            "|                   |   FY 2015 |   FY 2016 |   FY 2017 |   FY 2018 |   FY 2019(F) |\n"
            "|-------------------|-----------|-----------|-----------|-----------|--------------|\n"
            "| Doanh thu (VNDbn) |      4920 |     11217 |     15297 |     38664 |        71115 |\n"
            "| L\u00e3i g\u1ed9p (Vbn)     |       718 |      2420 |      3128 |      7617 |        10983 |"
        ),
        "post_text": ".",
        "question": "H\u1ec7 s\u1ed1 kh\u1ea3 n\u0103ng thanh to\u00e1n l\u00e3i vay t\u0103ng bao nhi\u00eau l\u1ea7n so v\u1edbi c\u00f9ng k\u1ef3 n\u0103m ngo\u00e1i?",
        "program": "subtract(13.2, 10.3)",
    },
    {
        # Table & Text (train idx 1127): must locate the right table row ("N\u1ed9i dung s\u1ed1")
        # across three columns and chain two operators via the #0 reference.
        "pre_text": "t\u1ef7 l\u1ec7 ph\u1ea7n tr\u0103m chi ph\u00ed v\u1ed1n tr\u00ean ph\u1ea7n tr\u0103m t\u1ed5ng t\u00e0i s\u1ea3n c\u1ee7a m\u1ea3ng vi\u1ec5n th\u00f4ng \u0111\u01b0\u1ee3c duy tr\u00ec tr\u00ean 1, cho th\u1ea5y s\u1ef1 t\u1eadp trung ph\u00e2n b\u1ed5 chi ph\u00ed v\u1ed1n v\u00e0o m\u1ea3ng vi\u1ec5n th\u00f4ng c\u1ee7a fpt qua c\u00e1c n\u0103m.\nngo\u00e0i ra, t\u1ef7 l\u1ec7 n\u00e0y c\u1ee7a m\u1ea3ng \u0111\u1ea7u t\u01b0 v\u00e0 gi\u00e1o d\u1ee5c l\u00e0 1,1 v\u00e0o n\u0103m 2018 v\u00e0 0,9 v\u00e0o n\u0103m 2019, kh\u1eb3ng \u0111\u1ecbnh fpt c\u0169ng \u0111ang t\u1eadp trung v\u00e0o ph\u00e1t tri\u1ec3n 2 m\u1ea3ng n\u00e0y trong 2 n\u0103m g\u1ea7n \u0111\u00e2y.",
        "table": (
            "|                     |   2014 |   2015 |   2016 |   2017 |   2018 |   2019 |\n"
            "|---------------------|--------|--------|--------|--------|--------|--------|\n"
            "| Vi\u1ec5n th\u00f4ng          |    1.8 |    2.4 |    1.9 |    1.4 |    1.7 |    1.8 |\n"
            "| N\u1ed9i dung s\u1ed1         |    0.4 |    0.2 |    0.9 |    0.1 |    0.1 |    0.1 |\n"
            "| Ph\u00e1t tri\u1ec3n ph\u1ea7n m\u1ec1m |    2.4 |    1.3 |    3.1 |    1.1 |    0.4 |    0.5 |"
        ),
        "post_text": ".",
        "question": "T\u1ed5ng t\u1ef7 l\u1ec7 c\u1ee7a m\u1ea3ng N\u1ed9i dung s\u1ed1 trong ba n\u0103m t\u1eeb 2014 \u0111\u1ebfn 2016 l\u00e0 bao nhi\u00eau?",
        "program": "add(0.4, 0.2), add(#0, 0.9)",
    },
]

## Batch API generation (few-shot, gpt-5-nano)

Same Batch API approach as the 0-shot batch notebook, but each request's `input`
is a multi-turn conversation: the 3 `FEW_SHOT_EXAMPLES` as alternating user/assistant
turns, followed by the real query. The Responses API accepts a list of role/content
items for `input`, so this mirrors the chat-completions message list used in the
synchronous few-shot notebook.

Reasoning effort is `low`: the 3 demonstrations already show the exact operator
syntax and grounding pattern, so the model needs less deliberation than 0-shot.
If PA comes in lower than expected, bump this to `medium` and re-run.

In [6]:
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# Requires a real OpenAI API key (not the FPT Cloud / third-party BASE_URL used
# by the other notebooks) -- Batch API is an OpenAI-account-level feature.
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
client = OpenAI(api_key=OPENAI_API_KEY)

MODEL = "gpt-5-nano"
REASONING_EFFORT = "medium"  # few-shot: demonstrations already show the target format

In [7]:
import json
from pathlib import Path

BATCH_DIR = Path(f"outputs/fewshot_{MODEL}_batch")
BATCH_DIR.mkdir(parents=True, exist_ok=True)

REQUESTS_PATH = BATCH_DIR / "requests.jsonl"

# Build the fixed few-shot turns once (Responses API input items).
few_shot_turns = []
for shot in FEW_SHOT_EXAMPLES:
    few_shot_turns.append({
        "role": "user",
        "content": USER_MESSAGE_FRAME.format(
            pre_text=shot["pre_text"],
            table=shot["table"],
            post_text=shot["post_text"],
            question=shot["question"],
        ),
    })
    few_shot_turns.append({"role": "assistant", "content": shot["program"]})

def build_request(df_index, values):
    user_msg = USER_MESSAGE_FRAME.format(
        pre_text=values["pre_text"],
        table=values["table"],
        post_text=values["post_text"],
        question=values["question"],
    )
    return {
        "custom_id": str(df_index),
        "method": "POST",
        "url": "/v1/responses",
        "body": {
            "model": MODEL,
            "instructions": SYSTEM_MESSAGE,
            "input": [*few_shot_turns, {"role": "user", "content": user_msg}],
            "reasoning": {"effort": REASONING_EFFORT},
            "max_output_tokens": 2048,
        },
    }

with open(REQUESTS_PATH, "w", encoding="utf-8") as f:
    for df_index, values in df.iterrows():
        f.write(json.dumps(build_request(df_index, values), ensure_ascii=False) + "\n")

print(f"Wrote {len(df)} requests to {REQUESTS_PATH}")

Wrote 497 requests to outputs\fewshot_gpt-5-nano_batch\requests.jsonl

In [8]:
# Submit the batch job. Re-run-safe: if a batch_id was already saved from a
# previous run of this notebook, reuse it instead of submitting a duplicate job.
BATCH_ID_PATH = BATCH_DIR / "batch_id.txt"

if BATCH_ID_PATH.exists():
    batch_id = BATCH_ID_PATH.read_text().strip()
    print(f"Reusing existing batch job: {batch_id}")
else:
    batch_input_file = client.files.create(
        file=open(REQUESTS_PATH, "rb"),
        purpose="batch",
    )
    batch = client.batches.create(
        input_file_id=batch_input_file.id,
        endpoint="/v1/responses",
        completion_window="24h",
        metadata={"description": f"ViNumQA few-shot(3) {MODEL} ({REASONING_EFFORT} effort)"},
    )
    batch_id = batch.id
    BATCH_ID_PATH.write_text(batch_id)
    print(f"Submitted batch job: {batch_id}")

Submitted batch job: batch_6a687e7549c48190956b3fa35764272c

In [9]:
# Poll until the batch completes. Safe to re-run this cell repeatedly --
# it just checks status and returns immediately if not done yet.
import time

TERMINAL_STATUSES = {"completed", "failed", "expired", "cancelled"}

def poll_batch(batch_id, poll_interval_s=30, max_wait_s=None):
    waited = 0
    while True:
        batch = client.batches.retrieve(batch_id)
        counts = batch.request_counts
        print(f"status={batch.status}  completed={counts.completed}/{counts.total}  failed={counts.failed}")
        if batch.status in TERMINAL_STATUSES:
            return batch
        if max_wait_s is not None and waited >= max_wait_s:
            print(f"Stopped polling after {waited}s (still {batch.status}). Re-run this cell later to keep waiting.")
            return batch
        time.sleep(poll_interval_s)
        waited += poll_interval_s

# max_wait_s=None polls indefinitely; set e.g. max_wait_s=600 to check in, then
# stop and resume later (batch jobs can take minutes to ~24h).
batch = poll_batch(batch_id, poll_interval_s=30, max_wait_s=None)

status=validating  completed=0/0  failed=0
status=validating  completed=0/0  failed=0
status=validating  completed=0/0  failed=0
status=in_progress  completed=0/497  failed=0
status=in_progress  completed=0/497  failed=0
status=in_progress  completed=26/497  failed=0
status=in_progress  completed=445/497  failed=0
status=in_progress  completed=479/497  failed=0
status=finalizing  completed=497/497  failed=0
status=completed  completed=497/497  failed=0

In [10]:
# Download and parse the batch output, mapping results back onto df via custom_id.
if batch.status != "completed":
    raise RuntimeError(f"Batch did not complete successfully: status={batch.status}, errors={batch.errors}")

output_file = client.files.content(batch.output_file_id)
OUTPUT_PATH = BATCH_DIR / "results.jsonl"
output_file.write_to_file(OUTPUT_PATH)

n_ok, n_err = 0, 0
with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        df_index = int(record["custom_id"])
        response = record.get("response")
        if response is None or response.get("status_code") != 200:
            n_err += 1
            continue
        body = response["body"]
        output_text = body.get("output_text")
        if output_text is None:
            texts = []
            for item in body.get("output", []):
                for content in item.get("content", []):
                    if content.get("type") == "output_text":
                        texts.append(content["text"])
            output_text = "".join(texts)
        df.at[df_index, "generated_program"] = output_text.strip().strip("\n")
        n_ok += 1

print(f"Parsed {n_ok} successful / {n_err} failed responses out of {n_ok + n_err}.")

Parsed 497 successful / 0 failed responses out of 497.

In [11]:
import sys
sys.path.insert(0, "../../evaluate")  # fallback: relative path when running locally

from scorer import evaluate_dataframe  # noqa: E402

# scorer.py is the shared ViNumQA evaluator (notebooks/evaluate/scorer.py): it
# ports FinQA's official evaluation protocol (sympy-based symbolic Program
# Accuracy, table-row-lookup-aware Execution Accuracy) instead of a
# hand-rolled parser, and correctly executes table_*(row_name, none) calls by
# looking up the named row in the raw table -- which the previous in-notebook
# parser could not do at all (it treated table_* arguments as raw numbers).

In [12]:
df_scored, summary = evaluate_dataframe(
    df,
    generated_col="generated_program",
    gold_program_col="program",
    gold_answer_col="answer",
    table_col="table_raw",
)

print(summary)

{'program_accuracy': 0.317907444668008, 'execution_accuracy': 0.358148893360161}

In [13]:
results_path = BATCH_DIR / "scored_results.csv"
summary_path = BATCH_DIR / "summary.json"

df_scored.to_csv(results_path, index=False)
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump({"model": MODEL, "shot": "few-shot(3)", "reasoning_effort": REASONING_EFFORT, "api": "batch", **summary}, f, ensure_ascii=False, indent=2)

print(f"Saved per-sample results to {results_path}")
print(f"Saved summary to {summary_path}")

Saved per-sample results to outputs\fewshot_gpt-5-nano_batch\scored_results.csv
Saved summary to outputs\fewshot_gpt-5-nano_batch\summary.json