In [10]:
import pandas as pd
from pathlib import Path
from tabulate import tabulate

# Robust to whichever working directory Jupyter starts in (repo root vs.
# the notebook's own folder, which is VSCode's default for .ipynb files).
_CANDIDATES = [
    Path("datasets/ViNumQA/test.json"),
    Path("../../../datasets/ViNumQA/test.json"),
]
DATA_PATH = next((p for p in _CANDIDATES if p.exists()), None)
if DATA_PATH is None:
    raise FileNotFoundError(
        f"Could not find test.json. cwd={Path.cwd()}, tried: {[str(p) for p in _CANDIDATES]}"
    )
print(f"Loading data from: {DATA_PATH.resolve()}")

df = pd.read_json(DATA_PATH)
df.sample(n=5)

Loading data from: C:\Users\DELL\Desktop\NumReasoning4VietnameseFinancialText\datasets\ViNumQA\test.json

,pre_text,table,post_text,id,qa
164,[chúng tôi sử dụng phương pháp chiết khấu dòng...,"[[Phương pháp, Giá trị, Tỷ trọng, Kết quả kèm ...",[.],masvn/2021/2021185-CRE_Q3Update_Buy_MAS_202112...,{'question': 'Tính giá mục tiêu trung bình dựa...
136,[khoản vay đáo hạn năm 2013 liên quan đến đòn ...,[[năm kết thúc ngày 31 tháng 12 (tính bằng tri...,[( a ) thiết bị tại cơ sở khách hàng (“cpe”) b...,CMCSA/2008/page_36.pdf-1,{'question': 'Hạ tầng có thể mở rộng chiếm bao...
485,"[kết quả kinh doanh 1h19, kqkd 1h19 của dhg ch...","[[FY (Dec.), 2015, 2016, 2017, 2018, 2019F], [...",[.],masvn/2020/2020030-MAS_Pharmaceutical_Industry...,{'question': 'Tổng doanh thu từ năm 2015 đến n...
210,[chúng tôi sử dụng phương pháp so sánh để định...,"[[FY (Dec), FY 2015, FY 2016, FY 2017, FY 2018...",[.],masvn/2020/2020029-POW_FlashNote1H2019/page_1_QA5,"{'question': 'Dựa trên doanh thu và lãi gộp, b..."
481,[.],"[[, 1Q18, 1Q19, YoY (%), Kế hoạch 2019 (%)], [...",[doanh thu tăng trưởng trong quý đầu năm có ph...,masvn/2020/2020013-VN_18042019MWGShortNote_TV_...,{'question': 'Tốc độ tăng trưởng doanh thu quý...

In [11]:
len(df)

497

In [12]:
def formatting_pre_text(sample):
    return "\n".join(sample["pre_text"])

def formatting_table(sample):
    return tabulate(sample["table"][1:], headers=sample["table"][0], tablefmt="github")

def formatting_post_text(sample):
    return "\n".join(sample["post_text"])

def processing_input_question(sample):
    return sample["qa"]["question"]

def processing_program_content(sample):
    return sample["qa"]["program"]

def processing_answer_content(sample):
    return sample["qa"]["exe_ans"]

df["pre_text_processed"] = df.apply(lambda x: formatting_pre_text(x), axis=1)
df["post_text_processed"] = df.apply(lambda x: formatting_post_text(x), axis=1)
df["table_processed"] = df.apply(lambda x: formatting_table(x), axis=1)
df["table_raw"] = df["table"]  # keep raw rows for table_* row-name lookup at eval time
df["input_question"] = df.apply(lambda x: processing_input_question(x), axis=1)
df["program_processed"] = df.apply(lambda x: processing_program_content(x), axis=1)
df["answer_processed"] = df.apply(lambda x: processing_answer_content(x), axis=1)
df.sample(n=5)

,pre_text,table,post_text,id,qa,pre_text_processed,post_text_processed,table_processed,table_raw,input_question,program_processed,answer_processed
147,[chúng tôi đánh giá công ty cổ phần đầu tư và ...,"[[Tên dự án, Giá trị hiện tại thuần (triệu đồn...",[.],masvn/2020/2020044-CTCP_a__utu_va_Pha_ttrie__n...,{'question': 'Tổng giá trị hiện tại thuần của ...,chúng tôi đánh giá công ty cổ phần đầu tư và p...,.,| Tên dự án | Giá trị hiện t...,"[[Tên dự án, Giá trị hiện tại thuần (triệu đồn...",Tổng giá trị hiện tại thuần của ba dự án có gi...,"add(894791, 869758), add(#0, 362344)",2126893.0
129,"[jpmorgan chase & co., / báo cáo thường niên 2...","[[năm kết thúc ngày 31 tháng 12,, 2008, 2007, ...","[phát hành công ty đã phát hành 6,0 tỷ đô la v...",JPM/2008/page_87.pdf-1,{'question': 'Tính đến ngày 31 tháng 12 năm 20...,jpmorgan chase & co.\n/ báo cáo thường niên 20...,"phát hành công ty đã phát hành 6,0 tỷ đô la và...","| năm kết thúc ngày 31 tháng 12, | 20...","[[năm kết thúc ngày 31 tháng 12,, 2008, 2007, ...","Tính đến ngày 31 tháng 12 năm 2008, tỷ lệ phần...","divide(6.2, 10)",0.62
176,"[sử dụng phương pháp p/b và rnav để định giá, ...","[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",[.],masvn/2020/2020193-VN_IndustrialRealEstate_Upd...,{'question': 'Tổng diện tích đất (ha) sẵn sàng...,"sử dụng phương pháp p/b và rnav để định giá, c...",.,| Năm tài chính (31/12) | 2016 | 2017 | ...,"[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",Tổng diện tích đất (ha) sẵn sàng cho thuê từ c...,"add(95, 264), add(#0, 136)",495.0
329,"[định giá và khuyến nghị, chúng tôi nâng khuyế...","[[Năm tài chính (31/12), 2015, 2016, 2017, 201...",[.],masvn/2020/2020164-DIG_Q3Update_Tradingbuy_MAS...,{'question': 'tỷ lệ thay đổi doanh thu từ năm ...,định giá và khuyến nghị\nchúng tôi nâng khuyến...,.,| Năm tài chính (31/12) | 2015 | 2016 | ...,"[[Năm tài chính (31/12), 2015, 2016, 2017, 201...",tỷ lệ thay đổi doanh thu từ năm 2018 đến năm 2...,"subtract(2115, 2345), divide(#0, 2345)",-0.09808
22,[thuyết minh báo cáo tài chính hợp nhất tập đo...,"[[triệu đô la, 2016, 2015, 2014], [sản phẩm nô...",[mặc dù doanh thu của chúng tôi chủ yếu đến từ...,UNP/2016/page_52.pdf-4,{'question': 'Phạm vi toán học của doanh thu m...,thuyết minh báo cáo tài chính hợp nhất tập đoà...,mặc dù doanh thu của chúng tôi chủ yếu đến từ ...,| triệu đô la | 2016 | ...,"[[triệu đô la, 2016, 2015, 2014], [sản phẩm nô...",Phạm vi toán học của doanh thu mảng hóa chất t...,"subtract(3664, 3474)",190.0

In [13]:
df = df[["pre_text_processed", "table_processed", "table_raw", "post_text_processed", "input_question", "program_processed", "answer_processed"]]
# NOTE: use a flat list here, not [[...]] — the double brackets create a
# MultiIndex column (each name becomes a 1-tuple like ('question',)), which
# silently breaks boolean filtering like df["generated_program"] == "" later
# (df["col"] returns a 1-column DataFrame instead of a Series in that case).
df.columns = ["pre_text", "table", "table_raw", "post_text", "question", "program", "answer"]
df["generated_program"] = ""
df["calculated_program"] = ""
df

,pre_text,table,table_raw,post_text,question,program,answer,generated_program,calculated_program
0,thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,| các thành phần của ảnh hưởng lũy kế của việc...,[[các thành phần của ảnh hưởng lũy kế của việc...,.,Sự thay đổi trong thu nhập ròng từ hiệu ứng tí...,"add(30, 1)",31.0,,
1,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,"Theo dự phóng, doanh thu và lợi nhuận ròng quý...","subtract(9829, 642)",9187.0,,
2,"sử dụng phương pháp p/b và rnav để định giá, c...",| Năm tài chính (31/12) | 2016 | 2017 | ...,"[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",.,IDC có bao nhiêu ha quỹ đất sẵn sàng cho thuê ...,"add(495, 398)",893.0,,
3,27/10/13 26/10/14 25/10/15 30/10/16 29/10/17 2...,| | 27/10/2013 |...,"[[, 27/10/2013, 26/10/2014, 25/10/2015, 30/10/...",.,Tỷ suất lợi nhuận trên đầu tư (ROI) của Applie...,"subtract(96.67, 100), divide(#0, 100)",-0.0333,,
4,thông tin tài chính bổ sung hiệu suất cổ phiếu...,| | 12/26/08 | ...,"[[, 12/26/08, 12/31/09, 12/31/10, 12/31/11, 12...",218 báo cáo thường niên năm 2013 của goldman s...,tỷ lệ lợi nhuận tích lũy tổng cộng theo phần t...,"subtract(248.36, 100), divide(#0, 100)",1.4836,,
...,...,...,...,...,...,...,...,...,...
492,thuyết minh báo cáo tài chính hợp nhất năm 201...,| ...,"[[, 2008, 2007], [Số dư đầu kỳ, $ 134.8, $ 266...",trong tổng số lợi ích thuế chưa được ghi nhận ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575,,
493,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Doanh thu trung bình từ năm tài chính 2017 đến...,"add(29710, 32662), add(#0, 35374), divide(#1, 3)",32582.0,,
494,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Tính phần trăm thay đổi EPS từ năm 2020 đến 2021.,"subtract(962, 788), divide(#0, 788)",0.22081,,
495,"trong quá trình kinh doanh thông thường, dựa t...",| ( đơn vị: nghìn ) | diện tích ròng chưa ph...,"[[( đơn vị: nghìn ), diện tích ròng chưa phát ...",( a ) một giếng khoan thăm dò được lên kế hoạc...,Tỷ lệ phần trăm diện tích đất chưa phát triển ...,"divide(145, 586)",0.24744,,
496,.,| | 1Q18 | 1Q19 | YoY (%...,"[[, 1Q18, 1Q19, YoY (%), Kế hoạch 2019 (%)], [...",doanh thu tăng trưởng trong quý đầu năm có phầ...,"dựa trên kết quả quý 1 năm 2019, lợi nhuận sau...","divide(1041, 0.292)",3565.06849,,

In [14]:
SYSTEM_MESSAGE = """You are a financial analysis AI. Your task is to generate a sequential computation program to answer the question, based on the provided context.

### LIST OF 10 VALID OPERATORS:

1. add(a, b) -> a + b
2. subtract(a, b) -> a - b
3. multiply(a, b) -> a * b
4. divide(a, b) -> a / b
5. exp(a, b) -> a^b
6. greater(a, b) -> 1.0 if a > b, else 0.0
7. table_sum(row_name, none) -> sum of the numeric values in the table row named `row_name`
8. table_average(row_name, none) -> arithmetic mean of the numeric values in the table row named `row_name`
9. table_max(row_name, none) -> maximum of the numeric values in the table row named `row_name`
10. table_min(row_name, none) -> minimum of the numeric values in the table row named `row_name`

### RULES:
- Do not use free-form mathematical symbols ("+", "-", "*", "/") outside of parentheses. Every calculation must use one of the 10 operators above.
- table_* operators take exactly two arguments: the row name (copied exactly as it appears as the first cell of the target row) and the literal `none` (e.g. table_max(Lãi ròng, none)), never a list of numeric values.
- Do not perform mental calculations or provide explanations. The output must contain only the program string.
- Reference the result of a previous step using #0 (step 1), #1 (step 2), etc. Steps are separated by commas.
- Preserve the original number format from the context. If a value is missing, use 'none'."""

USER_MESSAGE_FRAME = """### CONTEXT:
[TEXT BEFORE TABLE]
{pre_text}
 
[TABLE]
{table}
 
[TEXT AFTER TABLE]
{post_text}
 
### QUESTION:
{question}
 
### PROGRAM:"""

In [15]:
import base64
import requests
import io
import os
from io import BytesIO
from PIL import Image
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.environ["API_KEY"]
BASE_URL = os.environ["BASE_URL"]
MODEL = "gpt-oss-120b" # Llama-3.3-70B-Instruct; DeepSeek-V4-Flash; GLM-5.1

client = OpenAI(api_key=API_KEY, base_url=BASE_URL)

In [16]:
# Reasoning-model detection.
# Reasoning models (DeepSeek-R1 style, "...-Thinking", QwQ, o1/o3, etc.) emit an
# internal chain-of-thought before the final program string, so they need a much
# larger token budget than a plain instruct model or the response gets truncated
# (content=None / empty string, as happened in the earlier run of this notebook).
REASONING_MODEL_KEYWORDS = ["r1", "thinking", "reasoner", "qwq", "o1", "o3", "reasoning"]

def is_reasoning_model(model_name: str) -> bool:
    name = model_name.lower()
    return any(kw in name for kw in REASONING_MODEL_KEYWORDS)

IS_REASONING = is_reasoning_model(MODEL)

# Override: verified empirically (see the probe cell below) that
# "DeepSeek-V4-Flash" DOES return a separate reasoning_content field even
# though its name doesn't match the keyword heuristic above. Force it here.
if MODEL == "DeepSeek-V4-Flash":
    IS_REASONING = True

MAX_TOKENS = 8192 if IS_REASONING else 512

print(f"Model: {MODEL} | reasoning_model={IS_REASONING} | max_tokens={MAX_TOKENS}")

Model: gpt-oss-120b | reasoning_model=False | max_tokens=512

In [17]:
# Empirical check (more reliable than name-guessing): make one real call and
# inspect the raw response. Reasoning-model APIs (DeepSeek-R1 style) return the
# chain-of-thought in a separate `reasoning_content` field on the message,
# distinct from the final `content`. If that field is present and non-empty,
# it IS a reasoning model regardless of what IS_REASONING guessed from the name.
_probe = client.chat.completions.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user", "content": USER_MESSAGE_FRAME.format(
            pre_text="Doanh thu năm 2023 là 914, năm 2022 là 391.",
            table="", post_text="",
            question="Doanh thu năm 2023 gấp bao nhiêu lần năm 2022?"
        )},
    ],
    temperature=0.0,
    max_tokens=MAX_TOKENS,
)
_msg = _probe.choices[0].message
_reasoning_field = getattr(_msg, "reasoning_content", None)

print("finish_reason:", _probe.choices[0].finish_reason)
print("content:", repr(_msg.content))
print("reasoning_content present:", _reasoning_field is not None and bool(str(_reasoning_field).strip()))
if _reasoning_field:
    print("reasoning_content (first 300 chars):", str(_reasoning_field)[:300])

finish_reason: stop
content: 'divide(914, 391)'
reasoning_content present: False

In [18]:
import time
from pathlib import Path
from tqdm import tqdm

# Checkpointed, retrying generation loop.
# - Retries on transient errors / empty responses instead of crashing the whole run.
# - Saves progress to CSV every CHECKPOINT_EVERY samples and resumes from it,
#   so a crash (like the AttributeError at sample 483 in the first run) doesn't
#   throw away already-generated predictions.
CHECKPOINT_PATH = Path(f"outputs/0shot_{MODEL}_checkpoint.csv")
CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
CHECKPOINT_EVERY = 20

if CHECKPOINT_PATH.exists():
    ckpt = pd.read_csv(CHECKPOINT_PATH).fillna("")
    df.loc[ckpt.index, "generated_program"] = ckpt["generated_program"].values
    print(f"Resumed {(df['generated_program'] != '').sum()} / {len(df)} samples from checkpoint.")

def call_model(pre_text, table, post_text, question, max_retries=3):
    user_msg = USER_MESSAGE_FRAME.format(
        pre_text=pre_text, table=table, post_text=post_text, question=question
    )
    for attempt in range(1, max_retries + 1):
        try:
            resp = client.chat.completions.create(
                model=MODEL,
                messages=[
                    {"role": "system", "content": SYSTEM_MESSAGE},
                    {"role": "user", "content": user_msg},
                ],
                temperature=0.0,
                max_tokens=MAX_TOKENS,
                stream=False,
            )
            choice = resp.choices[0]
            content = choice.message.content
            # A reasoning model can burn its whole token budget on the hidden
            # chain-of-thought and get cut off (finish_reason == "length")
            # before finishing (or even starting) the final program string.
            if content is not None and content.strip() and choice.finish_reason != "length":
                return content.strip().strip("\n")
        except Exception as e:
            if attempt == max_retries:
                print(f"[row failed after {max_retries} attempts] {e}")
                return ""
        if attempt < max_retries:
            time.sleep(2 * attempt)
    return ""

todo_idx = df.index[df["generated_program"] == ""]
for i, df_index in enumerate(tqdm(todo_idx, desc="Generating program...")):
    values = df.loc[df_index]
    output = call_model(values["pre_text"], values["table"], values["post_text"], values["question"])
    df.at[df_index, "generated_program"] = output

    if (i + 1) % CHECKPOINT_EVERY == 0:
        df.to_csv(CHECKPOINT_PATH, index=False)

df.to_csv(CHECKPOINT_PATH, index=False)
print(f"Done. {(df['generated_program'] != '').sum()} / {len(df)} samples generated.")

Generating program...: 100%|██████████| 497/497 [1:19:01<00:00,  9.54s/it]

Done. 416 / 497 samples generated.

In [19]:
import sys
sys.path.insert(0, "../../evaluate")  # fallback: relative path when running locally

from scorer import evaluate_dataframe  # noqa: E402

# scorer.py is the shared ViNumQA evaluator (notebooks/evaluate/scorer.py): it
# ports FinQA's official evaluation protocol (sympy-based symbolic Program
# Accuracy, table-row-lookup-aware Execution Accuracy) instead of a
# hand-rolled parser, and correctly executes table_*(row_name, none) calls by
# looking up the named row in the raw table -- which the previous in-notebook
# parser could not do at all (it treated table_* arguments as raw numbers).

In [20]:
df_scored, summary = evaluate_dataframe(
    df,
    generated_col="generated_program",   # cột bạn đang ghi output model vào
    gold_program_col="program",
    gold_answer_col="answer",
    table_col="table_raw",
)

print(summary)  # {'program_accuracy': ..., 'execution_accuracy': ...}

{'program_accuracy': 0.317907444668008, 'execution_accuracy': 0.3561368209255533}

In [21]:
import json

results_path = Path(f"outputs/0shot_{MODEL}_results.csv")
summary_path = Path(f"outputs/0shot_{MODEL}_summary.json")

df_scored.to_csv(results_path, index=False)
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump({"model": MODEL, "shot": "0-shot", "max_tokens": MAX_TOKENS, **summary}, f, ensure_ascii=False, indent=2)

print(f"Saved per-sample results to {results_path}")
print(f"Saved summary to {summary_path}")

Saved per-sample results to outputs\0shot_gpt-oss-120b_results.csv
Saved summary to outputs\0shot_gpt-oss-120b_summary.json