In [1]:
import pandas as pd
from tabulate import tabulate

df = pd.read_json('/kaggle/input/datasets/ntphuc149x2/vlsp2025-vinumqa/test.json')
df.sample(n=5)

,pre_text,table,post_text,id,qa
85,[biểu đồ hiệu suất cổ phiếu biểu đồ được mô tả...,"[[, ngày 27 tháng 7 năm 2000, ngày 29 tháng 12...",[.],ILMN/2003/page_58.pdf-1,{'question': 'tỷ lệ lợi tức tích lũy tổng cộng...
371,[chúng tôi khuyến nghị mua với cổ phiếu ctcp t...,"[[Valuation 2020, , P/E (x), EV/EBITDA (x), P/...",[.],masvn/2020/2020077-V1_VN_Galvanized-steel-Outl...,{'question': 'So sánh giá trị cổ phiếu HSG the...
450,[kqkd 9m19 của pme đã ghi nhận chứng kiến về t...,"[[FY (Dec.), 12/15, 12/16, 12/17, 12/18, 12/19...",[.],masvn/2020/2020036-MAS_VN_PME_Initiate_Nov_14/...,{'question': 'Doanh thu của PME tăng bao nhiêu...
42,[đánh giá quý 1: phương pháp quản trị thận trọ...,"[[Năm tài chính (31/12), 12/16, 12/17, 12/18, ...",[.],masvn/2020/2020053-200427_VCB_1Q20_review_vn/p...,{'question': 'tính tỷ lệ lợi nhuận trước dự ph...
141,[chúng tôi khuyến nghị mua với cổ phiếu ctcp t...,"[[Valuation 2020, , P/E (x), EV/EBITDA (x), P/...",[.],masvn/2020/2020077-V1_VN_Galvanized-steel-Outl...,{'question': 'Giá trị cổ phiếu tính theo phươn...

In [2]:
len(df)

497

In [3]:
def formatting_pre_text(sample):
    return "\n".join(sample["pre_text"])

def formatting_table(sample):
    return tabulate(sample["table"][1:], headers=sample["table"][0], tablefmt="github")

def formatting_post_text(sample):
    return "\n".join(sample["post_text"])

def processing_input_question(sample):
    return sample["qa"]["question"]

def processing_program_content(sample):
    return sample["qa"]["program"]

def processing_answer_content(sample):
    return sample["qa"]["exe_ans"]

df["pre_text_processed"] = df.apply(lambda x: formatting_pre_text(x), axis=1)
df["post_text_processed"] = df.apply(lambda x: formatting_post_text(x), axis=1)
df["table_processed"] = df.apply(lambda x: formatting_table(x), axis=1)
df["input_question"] = df.apply(lambda x: processing_input_question(x), axis=1)
df["program_processed"] = df.apply(lambda x: processing_program_content(x), axis=1)
df["answer_processed"] = df.apply(lambda x: processing_answer_content(x), axis=1)
df.sample(n=5)

,pre_text,table,post_text,id,qa,pre_text_processed,post_text_processed,table_processed,input_question,program_processed,answer_processed
42,[đánh giá quý 1: phương pháp quản trị thận trọ...,"[[Năm tài chính (31/12), 12/16, 12/17, 12/18, ...",[.],masvn/2020/2020053-200427_VCB_1Q20_review_vn/p...,{'question': 'tính tỷ lệ lợi nhuận trước dự ph...,đánh giá quý 1: phương pháp quản trị thận trọn...,.,| Năm tài chính (31/12) | 12/16 ...,tính tỷ lệ lợi nhuận trước dự phòng trên tổng ...,"add(43408, 17573), divide(39763, #0)",0.65206
244,[đánh giá quý 1: phương pháp quản trị thận trọ...,"[[Năm tài chính (31/12), 12/16, 12/17, 12/18, ...",[.],masvn/2020/2020053-200427_VCB_1Q20_review_vn/p...,{'question': 'giá trị sổ sách trung bình trên ...,đánh giá quý 1: phương pháp quản trị thận trọn...,.,| Năm tài chính (31/12) | 12/16 ...,giá trị sổ sách trung bình trên mỗi cổ phiếu (...,table_average(Giá trị sổ sách / cổ phần (đồng)...,22381.57143
53,"[sử dụng phương pháp p/b và rnav để định giá, ...","[[Năm tài chính (31/12), 2018, 2019, 2020 (Dự ...",[.],masvn/2020/2020193-VN_IndustrialRealEstate_Upd...,{'question': 'Giá đóng cửa của cổ phiếu BCM ng...,"sử dụng phương pháp p/b và rnav để định giá, c...",.,| Năm tài chính (31/12) | 2018 | 2019 | ...,Giá đóng cửa của cổ phiếu BCM ngày 11/12/2020 ...,"add(1, 0.244), divide(50000, #0)",40192.92605
199,"[tại nhà máy lọc dầu catlettsburg, kentucky, m...","[[( nghìn thùng mỗi ngày ), 2003, 2002, 2001],...",[map bán xăng tái chế ở một số khu vực trong l...,MRO/2003/page_45.pdf-3,{'question': 'Tăng trưởng sản lượng xăng dầu c...,"tại nhà máy lọc dầu catlettsburg, kentucky, ma...",map bán xăng tái chế ở một số khu vực trong lã...,| ( nghìn thùng mỗi ngày ) ...,Tăng trưởng sản lượng xăng dầu của MAP trong 3...,"subtract(776, 748), divide(#0, 748)",0.03743
492,[thuyết minh báo cáo tài chính hợp nhất năm 20...,"[[, 2008, 2007], [Số dư đầu kỳ, $ 134.8, $ 266...",[trong tổng số lợi ích thuế chưa được ghi nhận...,IPG/2008/page_72.pdf-1,{'question': 'Tỷ lệ phần trăm lợi ích thuế chư...,thuyết minh báo cáo tài chính hợp nhất năm 201...,trong tổng số lợi ích thuế chưa được ghi nhận ...,| ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575

In [4]:
df = df[["pre_text_processed", "table_processed", "post_text_processed", "input_question", "program_processed", "answer_processed"]]
# NOTE: use a flat list here, not [[...]] — the double brackets create a
# MultiIndex column (each name becomes a 1-tuple like ('question',)), which
# silently breaks boolean filtering like df["generated_program"] == "" later
# (df["col"] returns a 1-column DataFrame instead of a Series in that case).
df.columns = ["pre_text", "table", "post_text", "question", "program", "answer"]
df["generated_program"] = ""
df["calculated_program"] = ""
df

,pre_text,table,post_text,question,program,answer,generated_program,calculated_program
0,thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,| các thành phần của ảnh hưởng lũy kế của việc...,.,Sự thay đổi trong thu nhập ròng từ hiệu ứng tí...,"add(30, 1)",31.0,,
1,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,.,"Theo dự phóng, doanh thu và lợi nhuận ròng quý...","subtract(9829, 642)",9187.0,,
2,"sử dụng phương pháp p/b và rnav để định giá, c...",| Năm tài chính (31/12) | 2016 | 2017 | ...,.,IDC có bao nhiêu ha quỹ đất sẵn sàng cho thuê ...,"add(495, 398)",893.0,,
3,27/10/13 26/10/14 25/10/15 30/10/16 29/10/17 2...,| | 27/10/2013 |...,.,Tỷ suất lợi nhuận trên đầu tư (ROI) của Applie...,"subtract(96.67, 100), divide(#0, 100)",-0.0333,,
4,thông tin tài chính bổ sung hiệu suất cổ phiếu...,| | 12/26/08 | ...,218 báo cáo thường niên năm 2013 của goldman s...,tỷ lệ lợi nhuận tích lũy tổng cộng theo phần t...,"subtract(248.36, 100), divide(#0, 100)",1.4836,,
...,...,...,...,...,...,...,...,...
492,thuyết minh báo cáo tài chính hợp nhất năm 201...,| ...,trong tổng số lợi ích thuế chưa được ghi nhận ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575,,
493,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,.,Doanh thu trung bình từ năm tài chính 2017 đến...,"add(29710, 32662), add(#0, 35374), divide(#1, 3)",32582.0,,
494,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,.,Tính phần trăm thay đổi EPS từ năm 2020 đến 2021.,"subtract(962, 788), divide(#0, 788)",0.22081,,
495,"trong quá trình kinh doanh thông thường, dựa t...",| ( đơn vị: nghìn ) | diện tích ròng chưa ph...,( a ) một giếng khoan thăm dò được lên kế hoạc...,Tỷ lệ phần trăm diện tích đất chưa phát triển ...,"divide(145, 586)",0.24744,,
496,.,| | 1Q18 | 1Q19 | YoY (%...,doanh thu tăng trưởng trong quý đầu năm có phầ...,"dựa trên kết quả quý 1 năm 2019, lợi nhuận sau...","divide(1041, 0.292)",3565.06849,,

In [5]:
import gc
import os
import torch
import pandas as pd
from tqdm import tqdm
from datasets import load_dataset
from huggingface_hub import login
from transformers import AutoModelForCausalLM, AutoTokenizer

# Read the HF token from an environment variable / Kaggle Secret instead of
# hardcoding it in the notebook. On Kaggle: Add-ons > Secrets > add "HF_TOKEN",
# then attach it to this notebook. Locally: set HF_TOKEN in your shell or .env.
try:
    from kaggle_secrets import UserSecretsClient
    HF_TOKEN = UserSecretsClient().get_secret("HF_KEY_READ")
except Exception:
    HF_TOKEN = os.environ.get("HF_KEY_READ")

if not HF_TOKEN:
    raise RuntimeError(
        "HF_TOKEN not found. Add it as a Kaggle Secret (Add-ons > Secrets) "
        "or set the HF_TOKEN environment variable before running this notebook."
    )

login(HF_TOKEN)

In [6]:
model_name = "Qwen/Qwen3-4B"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="cuda:0"
)

model.generation_config.temperature = 0.7
model.generation_config.top_p = 0.8
model.generation_config.top_k = 20
model.generation_config.min_p = 0.0

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

In [7]:
SYSTEM_MESSAGE = """You are a financial analysis AI. Your task is to generate a sequential computation program to answer the question, based on the provided context.
 
### LIST OF 10 VALID OPERATORS:
 
1. add(a, b) -> a + b
2. subtract(a, b) -> a - b
3. multiply(a, b) -> a * b
4. divide(a, b) -> a / b
5. exp(a, b) -> a^b
6. greater(a, b) -> 1.0 if a > b, else 0.0
7. table_sum(val1, val2, val3, ...) -> sum of the values
8. table_average(val1, val2, val3, ...) -> arithmetic mean of the values
9. table_max(val1, val2, val3, ...) -> maximum of the values
10. table_min(val1, val2, val3, ...) -> minimum of the values
 
### RULES:
- Do not use free-form mathematical symbols ("+", "-", "*", "/") outside of parentheses. Every calculation must use one of the 10 operators above.
- Do not use square brackets `[]` inside table-type functions (e.g. write table_max(1, 2, 3), not table_max([1, 2, 3])).
- Do not perform mental calculations or provide explanations. The output must contain only the program string.
- Reference the result of a previous step using #0 (step 1), #1 (step 2), etc. Steps are separated by commas.
- Preserve the original number format from the context. If a value is missing, use 'none'."""

USER_MESSAGE_FRAME = """### CONTEXT:
[TEXT BEFORE TABLE]
{pre_text}
 
[TABLE]
{table}
 
[TEXT AFTER TABLE]
{post_text}
 
### QUESTION:
{question}
 
### PROGRAM:"""

# One-shot exemplar (from Figure 1 of the VLSP 2025 NumQA paper): a single
# worked Table-Only example prepended as a user/assistant turn before the
# real query, so the model sees one demonstration of the expected input
# format and output format (bare program string, no explanation).
ONE_SHOT_EXAMPLE_TABLE = tabulate(
    [["Net revenue", "391", "914"], ["Gross profit", "163", "513"]],
    headers=["Metric (VND billion)", "2022", "2023"],
    tablefmt="github",
)

ONE_SHOT_EXAMPLE_USER = USER_MESSAGE_FRAME.format(
    pre_text=(
        "hệ số nợ trên vốn chủ sở hữu (d/e) của công ty cổ phần phát triển đô thị "
        "từ liêm là 0.1 lần và thường xuyên ở mức thấp, tránh rủi ro thanh khoản "
        "cho doanh nghiệp."
    ),
    table=ONE_SHOT_EXAMPLE_TABLE,
    post_text=".",
    question="Doanh thu thuần năm 2023 gấp bao nhiêu lần doanh thu thuần năm 2022?",
)
ONE_SHOT_EXAMPLE_ASSISTANT = "divide(914, 391)"

In [8]:
from pathlib import Path

# Checkpointed generation loop.
# The original 0-shot version had no checkpointing and took 2h38m for 497
# samples with zero fault tolerance -- a Kaggle session timeout/crash midway
# would lose everything. This saves progress every CHECKPOINT_EVERY samples
# and resumes from it on re-run.
CHECKPOINT_PATH = Path("outputs/1shot_qwen3-4b_checkpoint.csv")
CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
CHECKPOINT_EVERY = 20

if CHECKPOINT_PATH.exists():
    ckpt = pd.read_csv(CHECKPOINT_PATH).fillna("")
    df.loc[ckpt.index, "generated_program"] = ckpt["generated_program"].values
    print(f"Resumed {(df['generated_program'] != '').sum()} / {len(df)} samples from checkpoint.")

todo_idx = df.index[df["generated_program"] == ""]
for i, df_index in enumerate(tqdm(todo_idx, desc="Generating program...")):
    values = df.loc[df_index]
    pre_text = values["pre_text"]
    table = values["table"]
    post_text = values["post_text"]
    question = values["question"]

    USER_MESSAGE = USER_MESSAGE_FRAME.format(
        pre_text=pre_text,
        table=table,
        post_text=post_text,
        question=question
    )

    messages = [
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user", "content": ONE_SHOT_EXAMPLE_USER},
        {"role": "assistant", "content": ONE_SHOT_EXAMPLE_ASSISTANT},
        {"role": "user", "content": USER_MESSAGE},
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=512
    )
    output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist()

    try:
        index = len(output_ids) - output_ids[::-1].index(151668)
    except ValueError:
        index = 0

    output = tokenizer.decode(
        output_ids[index:], skip_special_tokens=True
    )

    df.at[df_index, "generated_program"] = output.strip()

    gc.collect()
    torch.cuda.empty_cache()

    if (i + 1) % CHECKPOINT_EVERY == 0:
        df.to_csv(CHECKPOINT_PATH, index=False)

df.to_csv(CHECKPOINT_PATH, index=False)
print(f"Done. {(df['generated_program'] != '').sum()} / {len(df)} samples generated.")

Generating program...: 100%|██████████| 497/497 [1:28:31<00:00, 10.69s/it]

Done. 497 / 497 samples generated.

In [9]:
"""
Parser + evaluation utilities for FinQA/VLSP-2025 style computation programs.

Program string format (as seen in the dataset / notebook), e.g.:
    "add(30, 1)"
    "subtract(9829, 642), divide(#0, 642)"
    "table_sum(-54, 30, 1), table_sum(-23, 292)"

- Steps are separated by top-level commas (commas NOT inside parentheses).
- Each step is `operator(arg1, arg2, ...)`.
- An arg can be a literal number, or a reference to a previous step's
  result using `#0`, `#1`, ... (0-indexed).
- `none` is treated as a missing/undefined value.
- A literal ending in `%` (e.g. "16.63%") represents a percentage and is
  converted to its decimal fraction (16.63% -> 0.1663), matching how the
  dataset's gold programs and exe_ans values are computed.

Two metrics are provided, matching the paper's definitions:
- Program Accuracy (PA): structural match between the generated program
  and the gold program (operator sequence + normalized numeric args).
- Execution Accuracy (EA): whether executing the generated program
  produces the same final numeric value as the gold answer.

NOTE on PA: FinQA-style datasets often have multiple valid gold programs
for the same question (see `program_re` in the paper). This implementation
only compares against a single gold program string. If you have alternative
gold programs available, run `compute_program_accuracy` against each and
take the max.
"""

import re
from typing import List, Tuple, Union, Optional


VALID_OPERATORS = {
    "add", "subtract", "multiply", "divide", "exp", "greater",
    "table_sum", "table_average", "table_max", "table_min",
}

_BINARY_OPS = {"add", "subtract", "multiply", "divide", "exp", "greater"}
_TABLE_OPS = {"table_sum", "table_average", "table_max", "table_min"}

_NUM_RE = re.compile(r"^-?\d+(\.\d+)?$")
_REF_RE = re.compile(r"^#(\d+)$")


def _parse_numeric_literal(raw: str) -> float:
    """
    Clean and parse a numeric literal, correctly handling a trailing '%' by
    dividing by 100 (a plain string-strip of '%' silently produces a value
    100x too large, e.g. treating "16.63%" as 16.63 instead of 0.1663 --
    which breaks execution/comparison against exe_ans, which is always a
    plain decimal fraction).
    Raises ValueError if the cleaned string isn't a valid number.
    """
    cleaned = raw.replace(",", "").replace("$", "").strip()
    is_percent = cleaned.endswith("%")
    if is_percent:
        cleaned = cleaned[:-1].strip()
    if not _NUM_RE.match(cleaned):
        raise ValueError(f"Cannot parse numeric argument: '{raw}'")
    value = float(cleaned)
    return value / 100.0 if is_percent else value


# --------------------------------------------------------------------------
# 1. Extraction: pull a program string out of raw (possibly messy) model output
# --------------------------------------------------------------------------

def extract_program(raw_text: str) -> str:
    """
    Extract a clean program string from raw LLM output that may contain
    markdown fences, extra prose, or trailing whitespace/newlines.

    Strategy: find all substrings matching `operator(...)` for the 10 known
    operators (no nested parens expected within a single step) and join them
    with ", " in the order they appear. Falls back to the stripped raw text
    if no operator call is found.
    """
    text = raw_text.strip()
    text = re.sub(r"```[a-zA-Z]*", "", text)
    text = text.replace("```", "").strip()

    op_names = "|".join(sorted(VALID_OPERATORS, key=len, reverse=True))
    pattern = rf"\b(?:{op_names})\([^()]*\)"
    matches = re.findall(pattern, text)

    if matches:
        return ", ".join(m.strip() for m in matches)
    return text


# --------------------------------------------------------------------------
# 2. Parsing: program string -> list of (operator, [args])
# --------------------------------------------------------------------------

def _split_top_level(s: str, sep: str = ",") -> List[str]:
    """Split a string on `sep`, but only at depth 0 (i.e. outside parens)."""
    parts = []
    depth = 0
    current = []
    for ch in s:
        if ch == "(":
            depth += 1
            current.append(ch)
        elif ch == ")":
            depth -= 1
            current.append(ch)
        elif ch == sep and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current))
    return [p.strip() for p in parts if p.strip() != ""]


def parse_program(program_str: str) -> List[Tuple[str, List[str]]]:
    """
    Parse a program string into a list of (operator, raw_args) steps.
    Raises ValueError if the string is malformed or uses an unknown operator.
    """
    program_str = program_str.strip().rstrip(",").strip()
    if not program_str:
        raise ValueError("Empty program string.")

    steps_raw = _split_top_level(program_str, sep=",")

    # Steps are comma-separated at top level, but each step itself is
    # "op(args...)" where args are also comma separated -> the naive split
    # above would break "op(a, b)" into "op(a" and " b)". So instead we
    # scan for complete `name(...)` chunks directly.
    steps: List[Tuple[str, List[str]]] = []
    call_pattern = re.compile(r"\s*([a-zA-Z_]+)\(([^()]*)\)\s*")
    pos = 0
    text = program_str
    while pos < len(text):
        m = call_pattern.match(text, pos)
        if not m:
            raise ValueError(f"Malformed program near: '{text[pos:pos+30]}...'")
        op = m.group(1).strip()
        if op not in VALID_OPERATORS:
            raise ValueError(f"Unknown operator: '{op}'")
        args = _split_top_level(m.group(2), sep=",")
        steps.append((op, args))
        pos = m.end()
        if pos < len(text) and text[pos] == ",":
            pos += 1

    if not steps:
        raise ValueError("No valid steps parsed.")
    return steps


# --------------------------------------------------------------------------
# 3. Execution: resolve args (numbers or #N references) and run each step
# --------------------------------------------------------------------------

def _resolve_arg(arg: str, results: List[float]) -> Optional[float]:
    arg = arg.strip()

    ref_match = _REF_RE.match(arg)
    if ref_match:
        idx = int(ref_match.group(1))
        if idx >= len(results):
            raise ValueError(f"Reference #{idx} used before step {idx} was computed.")
        return results[idx]

    if arg.lower() == "none":
        return None

    return _parse_numeric_literal(arg)


def execute_program(program_str: str) -> Tuple[float, List[float]]:
    """
    Parse and execute a program string.
    Returns (final_result, list_of_all_intermediate_results).
    Raises ValueError on malformed programs, unknown operators, missing
    (`none`) operands where a real value is required, or arithmetic errors
    (e.g. division by zero).
    """
    steps = parse_program(program_str)
    results: List[float] = []

    for op, raw_args in steps:
        vals = [_resolve_arg(a, results) for a in raw_args]

        if op in _BINARY_OPS:
            if len(vals) != 2:
                raise ValueError(f"Operator '{op}' expects 2 args, got {len(vals)}.")
            a, b = vals
            if a is None or b is None:
                raise ValueError(f"Operator '{op}' received a 'none' operand.")
            if op == "add":
                r = a + b
            elif op == "subtract":
                r = a - b
            elif op == "multiply":
                r = a * b
            elif op == "divide":
                if b == 0:
                    raise ValueError("Division by zero.")
                r = a / b
            elif op == "exp":
                r = a ** b
            elif op == "greater":
                r = 1.0 if a > b else 0.0

        elif op in _TABLE_OPS:
            if len(vals) < 1:
                raise ValueError(f"Operator '{op}' requires at least 1 arg.")
            if any(v is None for v in vals):
                raise ValueError(f"Operator '{op}' received a 'none' operand.")
            if op == "table_sum":
                r = sum(vals)
            elif op == "table_average":
                r = sum(vals) / len(vals)
            elif op == "table_max":
                r = max(vals)
            elif op == "table_min":
                r = min(vals)
        else:
            raise ValueError(f"Unknown operator: '{op}'")

        results.append(r)

    return results[-1], results


# --------------------------------------------------------------------------
# 4. Metrics
# --------------------------------------------------------------------------

def _normalize_program(program_str: str) -> List[Tuple[str, Tuple[str, ...]]]:
    """
    Normalize a parsed program for structural comparison:
    - operator names kept as-is
    - numeric args parsed to their true value (percent literals divided by
      100, see _parse_numeric_literal) and rounded to 6 decimals, so "30"
      == "30.0" but "16.63%" != "16.63" (they're not the same magnitude)
    - #N references kept as-is (order-sensitive)
    """
    steps = parse_program(program_str)
    normalized = []
    for op, args in steps:
        norm_args = []
        for a in args:
            a = a.strip()
            if _REF_RE.match(a) or a.lower() == "none":
                norm_args.append(a.lower())
            else:
                try:
                    norm_args.append(f"{round(_parse_numeric_literal(a), 6)}")
                except ValueError:
                    norm_args.append(a)
        normalized.append((op, tuple(norm_args)))
    return normalized


def compute_program_accuracy(
    generated_program: str,
    gold_program: str,
    alternative_gold_programs: Optional[List[str]] = None,
) -> float:
    """
    Program Accuracy (PA): 1.0 if the generated program structurally matches
    the gold program (same operator sequence, same args in the same order,
    numeric args compared after normalization), else 0.0.

    If `alternative_gold_programs` is provided (e.g. FinQA's `program_re`
    field), the generated program is also compared against each alternative
    and the best (max) match is returned.

    Returns 0.0 if either program fails to parse.
    """
    try:
        gen_norm = _normalize_program(generated_program)
    except ValueError:
        return 0.0

    gold_candidates = [gold_program] + (alternative_gold_programs or [])
    for gold in gold_candidates:
        try:
            gold_norm = _normalize_program(gold)
        except ValueError:
            continue
        if gen_norm == gold_norm:
            return 1.0
    return 0.0


def compute_execution_accuracy(
    generated_program: str,
    gold_answer: Union[str, float],
    rel_tol: float = 1e-3,
    abs_tol: float = 1e-4,
) -> float:
    """
    Execution Accuracy (EA): 1.0 if executing the generated program yields
    a numeric value equal to `gold_answer` within tolerance, else 0.0.

    `gold_answer` may be a string (as in the dataset's `exe_ans` field,
    e.g. "31.0") or a float. Returns 0.0 if the program fails to parse
    or execute, or if the gold answer can't be parsed as a number.
    """
    try:
        predicted, _ = execute_program(generated_program)
    except (ValueError, ZeroDivisionError, OverflowError):
        return 0.0

    try:
        gold = _parse_numeric_literal(str(gold_answer))
    except ValueError:
        return 0.0

    if abs(predicted - gold) <= max(abs_tol, rel_tol * abs(gold)):
        return 1.0
    return 0.0


# --------------------------------------------------------------------------
# 5. Batch evaluation helper (for a pandas DataFrame)
# --------------------------------------------------------------------------

def evaluate_dataframe(
    df,
    generated_col: str = "generated_program",
    gold_program_col: str = "program_processed",
    gold_answer_col: str = "answer_processed",
    alternative_gold_col: Optional[str] = None,
    extract_first: bool = True,
):
    """
    Compute per-row PA/EA and overall averages for a DataFrame.

    Adds two columns to a copy of `df`: 'pa_score' and 'ea_score', and
    returns (df_with_scores, {"program_accuracy": ..., "execution_accuracy": ...}).

    Set `extract_first=True` (default) to run `extract_program` on the raw
    generated text first, useful when the model output may contain extra
    prose, markdown fences, etc.
    """
    df = df.copy()
    pa_scores = []
    ea_scores = []

    for _, row in df.iterrows():
        raw_generated = row[generated_col]
        generated = extract_program(raw_generated) if extract_first else raw_generated
        gold_program = row[gold_program_col]
        gold_answer = row[gold_answer_col]

        alt_programs = None
        if alternative_gold_col is not None and alternative_gold_col in row:
            alt_val = row[alternative_gold_col]
            if isinstance(alt_val, str) and alt_val.strip():
                alt_programs = [alt_val]

        pa = compute_program_accuracy(generated, gold_program, alt_programs)
        ea = compute_execution_accuracy(generated, gold_answer)

        pa_scores.append(pa)
        ea_scores.append(ea)

    df["pa_score"] = pa_scores
    df["ea_score"] = ea_scores

    summary = {
        "program_accuracy": sum(pa_scores) / len(pa_scores) if pa_scores else 0.0,
        "execution_accuracy": sum(ea_scores) / len(ea_scores) if ea_scores else 0.0,
    }
    return df, summary


# --------------------------------------------------------------------------
# Quick self-test using the example from the dataset
# --------------------------------------------------------------------------

if __name__ == "__main__":
    # Example from the uploaded sample: program "add(30, 1)" -> exe_ans "31.0"
    gold_program = "add(30, 1)"
    gold_answer = "31.0"

    # Case 1: exact match
    gen1 = "add(30, 1)"
    print("PA (exact):", compute_program_accuracy(gen1, gold_program))
    print("EA (exact):", compute_execution_accuracy(gen1, gold_answer))

    # Case 2: numerically correct but structurally different (from the notebook run)
    gen2 = "table_sum(-54, 30, 1), table_sum(-23, 292)"
    print("PA (wrong structure):", compute_program_accuracy(gen2, gold_program))
    print("EA (wrong structure):", compute_execution_accuracy(gen2, gold_answer))

    # Case 3: messy raw output with extra text/fences
    raw = "```\nSure, here is the program:\nadd(30, 1)\n```"
    extracted = extract_program(raw)
    print("Extracted:", extracted)
    print("PA (extracted):", compute_program_accuracy(extracted, gold_program))

    # Case 4: percent literals must be divided by 100, not just stripped of '%'
    gold_pct_program = "subtract(16.63%, 14.23%)"
    gold_pct_answer = "0.024"
    gen_pct = "subtract(16.63%, 14.23%)"
    print("EA (percent, exact):", compute_execution_accuracy(gen_pct, gold_pct_answer))
    print("PA (percent, exact):", compute_program_accuracy(gen_pct, gold_pct_program))
    gen_pct_wrong_magnitude = "subtract(16.63, 14.23)"  # model dropped the '%'
    print("PA (percent vs dropped '%', should NOT match):",
          compute_program_accuracy(gen_pct_wrong_magnitude, gold_pct_program))

PA (exact): 1.0
EA (exact): 1.0
PA (wrong structure): 0.0
EA (wrong structure): 0.0
Extracted: add(30, 1)
PA (extracted): 1.0
EA (percent, exact): 1.0
PA (percent, exact): 1.0
PA (percent vs dropped '%', should NOT match): 0.0

In [10]:
df_scored, summary = evaluate_dataframe(
    df,
    generated_col="generated_program",   # cột bạn đang ghi output model vào
    gold_program_col="program",
    gold_answer_col="answer",
)

print(summary)  # {'program_accuracy': ..., 'execution_accuracy': ...}

{'program_accuracy': 0.1448692152917505, 'execution_accuracy': 0.3158953722334004}

In [11]:
import json

results_path = Path("outputs/1shot_qwen3-4b_results.csv")
summary_path = Path("outputs/1shot_qwen3-4b_summary.json")

df_scored.to_csv(results_path, index=False)
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump({"model": "Qwen/Qwen3-4B", "shot": "1-shot", "max_new_tokens": 512, **summary}, f, ensure_ascii=False, indent=2)

print(f"Saved per-sample results to {results_path}")
print(f"Saved summary to {summary_path}")

Saved per-sample results to outputs/1shot_qwen3-4b_results.csv
Saved summary to outputs/1shot_qwen3-4b_summary.json