In [1]:
import pandas as pd
from pathlib import Path
from tabulate import tabulate

PROJECT_ROOT = Path.cwd()
while not (PROJECT_ROOT / ".git").exists() and PROJECT_ROOT != PROJECT_ROOT.parent:
    PROJECT_ROOT = PROJECT_ROOT.parent

df = pd.read_json(PROJECT_ROOT / "datasets" / "ViNumQA" / "test.json")
df.sample(n=5)

,pre_text,table,post_text,id,qa
16,"[định giá và khuyến nghị:, chúng tôi khuyến ng...","[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",[.],masvn/2020/2020145-VN_POW_Update_BUY_MAS_20201...,{'question': 'Tính toán tỷ lệ tăng trưởng doan...
232,"[đánh giá kết quả 2018, năm 2018, mbb báo cáo ...","[[Năm tài chính, 2013, 2014, 2015, 2016, 2017,...",[.],masvn/2020/2020010-190314_MBB_2018review_VN/pa...,{'question': 'Tỷ lệ thu nhập ngoài lãi trên tổ...
337,[hoạt động chính trong lĩnh vực sản xuất giấy ...,"[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",[.],masvn/2020/2020058-DHC_Companynote_MAS27.05.20...,{'question': 'Doanh thu của DHC tăng bao nhiêu...
98,"[lợi nhuận sau thuế quý 3 tăng trưởng 16,2%, p...","[[Kết quả kinh doanh, 1Q19, 2Q19, 3Q19, 4Q19, ...",[.],masvn/2020/2020155-201005_BID_3Q20-review-vn/p...,{'question': 'Tính mức tăng của lãi thuần từ h...
101,[mục lục marketaxess holdings inc. thuyết minh...,"[[năm kết thúc ngày 31 tháng 12,, tính đến ngà...",[cổ phiếu ưu đãi chuyển đổi 9 cổ đông 2019 vốn...,MKTX/2004/page_99.pdf-4,"{'question': 'Trong năm 2001, công ty đã trao ..."

In [2]:
len(df)

497

In [3]:
def formatting_pre_text(sample):
    return "\n".join(sample["pre_text"])

def formatting_table(sample):
    return tabulate(sample["table"][1:], headers=sample["table"][0], tablefmt="github")

def formatting_post_text(sample):
    return "\n".join(sample["post_text"])

def processing_input_question(sample):
    return sample["qa"]["question"]

def processing_program_content(sample):
    return sample["qa"]["program"]

def processing_answer_content(sample):
    return sample["qa"]["exe_ans"]

df["pre_text_processed"] = df.apply(lambda x: formatting_pre_text(x), axis=1)
df["post_text_processed"] = df.apply(lambda x: formatting_post_text(x), axis=1)
df["table_processed"] = df.apply(lambda x: formatting_table(x), axis=1)
df["table_raw"] = df["table"]  # keep raw rows for table_* row-name lookup at eval time
df["input_question"] = df.apply(lambda x: processing_input_question(x), axis=1)
df["program_processed"] = df.apply(lambda x: processing_program_content(x), axis=1)
df["answer_processed"] = df.apply(lambda x: processing_answer_content(x), axis=1)
df.sample(n=5)

,pre_text,table,post_text,id,qa,pre_text_processed,post_text_processed,table_processed,table_raw,input_question,program_processed,answer_processed
423,"[kết quả kinh doanh 1h19, kqkd 1h19 của dhg ch...","[[FY (Dec.), 2015, 2016, 2017, 2018, 2019F], [...",[.],masvn/2020/2020030-MAS_Pharmaceutical_Industry...,{'question': 'Doanh thu dự phóng năm 2019F đã ...,kết quả kinh doanh 1h19\nkqkd 1h19 của dhg chứ...,.,| FY (Dec.) | 2015 | 2016 | 2017 ...,"[[FY (Dec.), 2015, 2016, 2017, 2018, 2019F], [...",Doanh thu dự phóng năm 2019F đã thay đổi bao n...,"subtract(3971, 3888), divide(#0, 3888)",0.02135
318,"[năm 2019, hpg đã cung cấp gần 2,8 triệu tấn t...","[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",[.],masvn/2020/2020056-HPG_Companynote_MAS22.05.20...,{'question': 'Doanh thu của HPG trong năm 2020...,"năm 2019, hpg đã cung cấp gần 2,8 triệu tấn th...",.,| (Tỷ đồng) | FY 2015 | FY 2016 |...,"[[(Tỷ đồng), FY 2015, FY 2016, FY 2017, FY 201...",Doanh thu của HPG trong năm 2020 dự kiến tăng ...,"subtract(95362, 63658), divide(#0, 63658)",0.49804
213,[mục lục 3 nghĩa vụ thanh toán phá sản tính đế...,"[[Cổ phiếu ưu đãi loại A của AAG, $ 3329], [Ng...",[như một cơ chế để thanh toán các khoản phải t...,AAL/2013/page_172.pdf-4,{'question': 'phần nào trong tổng nghĩa vụ giả...,mục lục 3 nghĩa vụ thanh toán phá sản tính đến...,như một cơ chế để thanh toán các khoản phải tr...,| Cổ phiếu ưu đãi loại A của AAG ...,"[[Cổ phiếu ưu đãi loại A của AAG, $ 3329], [Ng...",phần nào trong tổng nghĩa vụ giải quyết phá sả...,"divide(1246, 5424)",0.22972
76,"[định giá và khuyến nghị, chúng tôi nâng khuyế...","[[Năm tài chính (31/12), 2015, 2016, 2017, 201...",[.],masvn/2020/2020164-DIG_Q3Update_Tradingbuy_MAS...,{'question': 'So sánh ROE năm 2020 dự báo với ...,định giá và khuyến nghị\nchúng tôi nâng khuyến...,.,| Năm tài chính (31/12) | 2015 | 2016 | ...,"[[Năm tài chính (31/12), 2015, 2016, 2017, 201...","So sánh ROE năm 2020 dự báo với năm 2019, mức ...","subtract(9.54, 10.8), divide(#0, 10.8)",-0.11667
252,[hiệu suất lợi nhuận của cổ đông biểu đồ đường...,"[[, 12/31/2007, 12/31/2008, 12/31/2009, 12/31/...","[nguồn : bloomberg l.p., aecharts.]",BLL/2012/page_31.pdf-2,{'question': 'lợi tức đầu tư (ROI) của khoản đ...,hiệu suất lợi nhuận của cổ đông biểu đồ đường ...,nguồn : bloomberg l.p.\naecharts.,| | 12/31/2007 ...,"[[, 12/31/2007, 12/31/2008, 12/31/2009, 12/31/...",lợi tức đầu tư (ROI) của khoản đầu tư vào dj u...,"subtract(107.76, 100), divide(#0, 100)",0.0776

In [4]:
df = df[["pre_text_processed", "table_processed", "table_raw", "post_text_processed", "input_question", "program_processed", "answer_processed"]]
df.columns = ["pre_text", "table", "table_raw", "post_text", "question", "program", "answer"]
df["generated_program"] = ""
df["calculated_program"] = ""
df

,pre_text,table,table_raw,post_text,question,program,answer,generated_program,calculated_program
0,thuyết minh báo cáo tài chính hợp nhất ( tiếp ...,| các thành phần của ảnh hưởng lũy kế của việc...,[[các thành phần của ảnh hưởng lũy kế của việc...,.,Sự thay đổi trong thu nhập ròng từ hiệu ứng tí...,"add(30, 1)",31.0,,
1,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,"Theo dự phóng, doanh thu và lợi nhuận ròng quý...","subtract(9829, 642)",9187.0,,
2,"sử dụng phương pháp p/b và rnav để định giá, c...",| Năm tài chính (31/12) | 2016 | 2017 | ...,"[[Năm tài chính (31/12), 2016, 2017, 2018, 201...",.,IDC có bao nhiêu ha quỹ đất sẵn sàng cho thuê ...,"add(495, 398)",893.0,,
3,27/10/13 26/10/14 25/10/15 30/10/16 29/10/17 2...,| | 27/10/2013 |...,"[[, 27/10/2013, 26/10/2014, 25/10/2015, 30/10/...",.,Tỷ suất lợi nhuận trên đầu tư (ROI) của Applie...,"subtract(96.67, 100), divide(#0, 100)",-0.0333,,
4,thông tin tài chính bổ sung hiệu suất cổ phiếu...,| | 12/26/08 | ...,"[[, 12/26/08, 12/31/09, 12/31/10, 12/31/11, 12...",218 báo cáo thường niên năm 2013 của goldman s...,tỷ lệ lợi nhuận tích lũy tổng cộng theo phần t...,"subtract(248.36, 100), divide(#0, 100)",1.4836,,
...,...,...,...,...,...,...,...,...,...
492,thuyết minh báo cáo tài chính hợp nhất năm 201...,| ...,"[[, 2008, 2007], [Số dư đầu kỳ, $ 134.8, $ 266...",trong tổng số lợi ích thuế chưa được ghi nhận ...,Tỷ lệ phần trăm lợi ích thuế chưa được công nh...,"divide(131.8, 148.8)",0.88575,,
493,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Doanh thu trung bình từ năm tài chính 2017 đến...,"add(29710, 32662), add(#0, 35374), divide(#1, 3)",32582.0,,
494,định giá và khuyến nghị:\nchúng tôi khuyến ngh...,| Năm tài chính (31/12) | FY17 | FY1...,"[[Năm tài chính (31/12), FY17, FY18, FY19, FY2...",.,Tính phần trăm thay đổi EPS từ năm 2020 đến 2021.,"subtract(962, 788), divide(#0, 788)",0.22081,,
495,"trong quá trình kinh doanh thông thường, dựa t...",| ( đơn vị: nghìn ) | diện tích ròng chưa ph...,"[[( đơn vị: nghìn ), diện tích ròng chưa phát ...",( a ) một giếng khoan thăm dò được lên kế hoạc...,Tỷ lệ phần trăm diện tích đất chưa phát triển ...,"divide(145, 586)",0.24744,,
496,.,| | 1Q18 | 1Q19 | YoY (%...,"[[, 1Q18, 1Q19, YoY (%), Kế hoạch 2019 (%)], [...",doanh thu tăng trưởng trong quý đầu năm có phầ...,"dựa trên kết quả quý 1 năm 2019, lợi nhuận sau...","divide(1041, 0.292)",3565.06849,,

In [5]:
SYSTEM_MESSAGE = """You are a financial analysis AI. Your task is to generate a sequential computation program to answer the question, based on the provided context.

### LIST OF 10 VALID OPERATORS:

1. add(a, b) -> a + b
2. subtract(a, b) -> a - b
3. multiply(a, b) -> a * b
4. divide(a, b) -> a / b
5. exp(a, b) -> a^b
6. greater(a, b) -> 1.0 if a > b, else 0.0
7. table_sum(row_name, none) -> sum of the numeric values in the table row named `row_name`
8. table_average(row_name, none) -> arithmetic mean of the numeric values in the table row named `row_name`
9. table_max(row_name, none) -> maximum of the numeric values in the table row named `row_name`
10. table_min(row_name, none) -> minimum of the numeric values in the table row named `row_name`

### RULES:
- Do not use free-form mathematical symbols ("+", "-", "*", "/") outside of parentheses. Every calculation must use one of the 10 operators above.
- table_* operators take exactly two arguments: the row name (copied exactly as it appears as the first cell of the target row) and the literal `none` (e.g. table_max(Lãi ròng, none)), never a list of numeric values.
- Do not perform mental calculations or provide explanations. The output must contain only the program string.
- Reference the result of a previous step using #0 (step 1), #1 (step 2), etc. Steps are separated by commas.
- Preserve the original number format from the context. If a value is missing, use 'none'."""

USER_MESSAGE_FRAME = """### CONTEXT:
[TEXT BEFORE TABLE]
{pre_text}
 
[TABLE]
{table}
 
[TEXT AFTER TABLE]
{post_text}
 
### QUESTION:
{question}
 
### PROGRAM:"""

# One-shot exemplar (from Figure 1 of the VLSP 2025 NumQA paper): a single
# worked Table-Only example prepended as a user/assistant turn before the
# real query. Kept identical to the exemplar used in the team's Qwen3-4B
# 1-shot notebook (notebooks/vinumqa/1-shot/1shot_qwen4B.ipynb on the `chi`
# branch) so results are comparable across models/APIs at the same shot count.
ONE_SHOT_EXAMPLE_TABLE = tabulate(
    [["Net revenue", "391", "914"], ["Gross profit", "163", "513"]],
    headers=["Metric (VND billion)", "2022", "2023"],
    tablefmt="github",
)

ONE_SHOT_EXAMPLE_USER = USER_MESSAGE_FRAME.format(
    pre_text=(
        "h\u1ec7 s\u1ed1 n\u1ee3 tr\u00ean v\u1ed1n ch\u1ee7 s\u1edf h\u1eefu (d/e) c\u1ee7a c\u00f4ng ty c\u1ed5 ph\u1ea7n ph\u00e1t tri\u1ec3n \u0111\u00f4 th\u1ecb "
        "t\u1eeb li\u00eam l\u00e0 0.1 l\u1ea7n v\u00e0 th\u01b0\u1eddng xuy\u00ean \u1edf m\u1ee9c th\u1ea5p, tr\u00e1nh r\u1ee7i ro thanh kho\u1ea3n "
        "cho doanh nghi\u1ec7p."
    ),
    table=ONE_SHOT_EXAMPLE_TABLE,
    post_text=".",
    question="Doanh thu thu\u1ea7n n\u0103m 2023 g\u1ea5p bao nhi\u00eau l\u1ea7n doanh thu thu\u1ea7n n\u0103m 2022?",
)
ONE_SHOT_EXAMPLE_ASSISTANT = "divide(914, 391)"

## Batch API generation (1-shot, gpt-5-nano)

Same Batch API approach as the 0-shot and few-shot batch notebooks. Each request's
`input` is a 3-turn conversation: the single `ONE_SHOT_EXAMPLE_*` demonstration as a
user/assistant pair, followed by the real query.

Reasoning effort is `medium` (same as 0-shot): a single example isn't diverse enough
(unlike the 3-example few-shot set spanning Table Only / Text Only / Table & Text)
for the model to reliably generalize the grounding/format pattern, so we keep the
higher effort budget rather than dropping to `low` as in the few-shot notebook.

In [6]:
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

# Requires a real OpenAI API key (not the FPT Cloud / third-party BASE_URL used
# by the other notebooks) -- Batch API is an OpenAI-account-level feature.
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
client = OpenAI(api_key=OPENAI_API_KEY)

MODEL = "gpt-5-nano"
REASONING_EFFORT = "medium"  # 1-shot: single example isn't enough to drop effort, same budget as 0-shot

In [7]:
import json
from pathlib import Path

BATCH_DIR = Path(f"outputs/1shot_{MODEL}_batch")
BATCH_DIR.mkdir(parents=True, exist_ok=True)

REQUESTS_PATH = BATCH_DIR / "requests.jsonl"

one_shot_turns = [
    {"role": "user", "content": ONE_SHOT_EXAMPLE_USER},
    {"role": "assistant", "content": ONE_SHOT_EXAMPLE_ASSISTANT},
]

def build_request(df_index, values):
    user_msg = USER_MESSAGE_FRAME.format(
        pre_text=values["pre_text"],
        table=values["table"],
        post_text=values["post_text"],
        question=values["question"],
    )
    return {
        "custom_id": str(df_index),
        "method": "POST",
        "url": "/v1/responses",
        "body": {
            "model": MODEL,
            "instructions": SYSTEM_MESSAGE,
            "input": [*one_shot_turns, {"role": "user", "content": user_msg}],
            "reasoning": {"effort": REASONING_EFFORT},
            "max_output_tokens": 2048,
        },
    }

with open(REQUESTS_PATH, "w", encoding="utf-8") as f:
    for df_index, values in df.iterrows():
        f.write(json.dumps(build_request(df_index, values), ensure_ascii=False) + "\n")

print(f"Wrote {len(df)} requests to {REQUESTS_PATH}")

Wrote 497 requests to outputs\1shot_gpt-5-nano_batch\requests.jsonl

In [8]:
# Submit the batch job. Re-run-safe: if a batch_id was already saved from a
# previous run of this notebook, reuse it instead of submitting a duplicate job.
BATCH_ID_PATH = BATCH_DIR / "batch_id.txt"

if BATCH_ID_PATH.exists():
    batch_id = BATCH_ID_PATH.read_text().strip()
    print(f"Reusing existing batch job: {batch_id}")
else:
    batch_input_file = client.files.create(
        file=open(REQUESTS_PATH, "rb"),
        purpose="batch",
    )
    batch = client.batches.create(
        input_file_id=batch_input_file.id,
        endpoint="/v1/responses",
        completion_window="24h",
        metadata={"description": f"ViNumQA 1-shot {MODEL} ({REASONING_EFFORT} effort)"},
    )
    batch_id = batch.id
    BATCH_ID_PATH.write_text(batch_id)
    print(f"Submitted batch job: {batch_id}")

Submitted batch job: batch_6a687e19254c8190972e67250e665dda

In [9]:
# Poll until the batch completes. Safe to re-run this cell repeatedly --
# it just checks status and returns immediately if not done yet.
import time

TERMINAL_STATUSES = {"completed", "failed", "expired", "cancelled"}

def poll_batch(batch_id, poll_interval_s=30, max_wait_s=None):
    waited = 0
    while True:
        batch = client.batches.retrieve(batch_id)
        counts = batch.request_counts
        print(f"status={batch.status}  completed={counts.completed}/{counts.total}  failed={counts.failed}")
        if batch.status in TERMINAL_STATUSES:
            return batch
        if max_wait_s is not None and waited >= max_wait_s:
            print(f"Stopped polling after {waited}s (still {batch.status}). Re-run this cell later to keep waiting.")
            return batch
        time.sleep(poll_interval_s)
        waited += poll_interval_s

# max_wait_s=None polls indefinitely; set e.g. max_wait_s=600 to check in, then
# stop and resume later (batch jobs can take minutes to ~24h).
batch = poll_batch(batch_id, poll_interval_s=30, max_wait_s=None)

status=validating  completed=0/0  failed=0
status=validating  completed=0/0  failed=0
status=in_progress  completed=0/497  failed=0
status=in_progress  completed=0/497  failed=0
status=in_progress  completed=0/497  failed=0
status=in_progress  completed=12/497  failed=0
status=in_progress  completed=131/497  failed=0
status=in_progress  completed=303/497  failed=0
status=in_progress  completed=467/497  failed=0
status=in_progress  completed=489/497  failed=0
status=in_progress  completed=489/497  failed=0
status=finalizing  completed=497/497  failed=0
status=completed  completed=497/497  failed=0

In [10]:
# Download and parse the batch output, mapping results back onto df via custom_id.
if batch.status != "completed":
    raise RuntimeError(f"Batch did not complete successfully: status={batch.status}, errors={batch.errors}")

output_file = client.files.content(batch.output_file_id)
OUTPUT_PATH = BATCH_DIR / "results.jsonl"
output_file.write_to_file(OUTPUT_PATH)

n_ok, n_err = 0, 0
with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
    for line in f:
        record = json.loads(line)
        df_index = int(record["custom_id"])
        response = record.get("response")
        if response is None or response.get("status_code") != 200:
            n_err += 1
            continue
        body = response["body"]
        output_text = body.get("output_text")
        if output_text is None:
            texts = []
            for item in body.get("output", []):
                for content in item.get("content", []):
                    if content.get("type") == "output_text":
                        texts.append(content["text"])
            output_text = "".join(texts)
        df.at[df_index, "generated_program"] = output_text.strip().strip("\n")
        n_ok += 1

print(f"Parsed {n_ok} successful / {n_err} failed responses out of {n_ok + n_err}.")

Parsed 497 successful / 0 failed responses out of 497.

In [11]:
import sys
sys.path.insert(0, "../../evaluate")  # fallback: relative path when running locally

from scorer import evaluate_dataframe  # noqa: E402

# scorer.py is the shared ViNumQA evaluator (notebooks/evaluate/scorer.py): it
# ports FinQA's official evaluation protocol (sympy-based symbolic Program
# Accuracy, table-row-lookup-aware Execution Accuracy) instead of a
# hand-rolled parser, and correctly executes table_*(row_name, none) calls by
# looking up the named row in the raw table -- which the previous in-notebook
# parser could not do at all (it treated table_* arguments as raw numbers).

In [12]:
df_scored, summary = evaluate_dataframe(
    df,
    generated_col="generated_program",
    gold_program_col="program",
    gold_answer_col="answer",
    table_col="table_raw",
)

print(summary)

{'program_accuracy': 0.2837022132796781, 'execution_accuracy': 0.31388329979879276}

In [13]:
results_path = BATCH_DIR / "scored_results.csv"
summary_path = BATCH_DIR / "summary.json"

df_scored.to_csv(results_path, index=False)
with open(summary_path, "w", encoding="utf-8") as f:
    json.dump({"model": MODEL, "shot": "1-shot", "reasoning_effort": REASONING_EFFORT, "api": "batch", **summary}, f, ensure_ascii=False, indent=2)

print(f"Saved per-sample results to {results_path}")
print(f"Saved summary to {summary_path}")

Saved per-sample results to outputs\1shot_gpt-5-nano_batch\scored_results.csv
Saved summary to outputs\1shot_gpt-5-nano_batch\summary.json