In [21]:
import pandas as pd

In [22]:
df_train = pd.read_json(r".\train.json")
df_val = pd.read_json(r".\dev.json")
df_test = pd.read_json(r".\test.json")

In [23]:
df_train.sample(2)

,pre_text,post_text,filename,table_ori,table,qa,id,table_retrieved,text_retrieved,table_retrieved_all,text_retrieved_all
18,[while we have remediated the previously-ident...,[we maintain all of our manufacturing and proc...,KHC/2017/page_21.pdf,"[[, Owned, Leased], [United States, 41, 1], [C...","[[, owned, leased], [united states, 41, 1], [c...",{'question': 'what percent of total facilities...,KHC/2017/page_21.pdf-4,"[{'score': 1.487656235694885, 'ind': 'table_4'...","[{'score': 2.221584320068359, 'ind': 'text_18'...","[{'score': 1.487656235694885, 'ind': 'table_4'...","[{'score': 2.221584320068359, 'ind': 'text_18'..."
3253,[and $ 19 million of these expenses in 2011 an...,"[( 1 ) includes cash and cash equivalents , sh...",AON/2011/page_91.pdf,"[[, Amountsrecorded as ofthe acquisitiondate],...","[[, amountsrecorded as ofthe acquisitiondate],...",{'question': 'what is the total value of ident...,AON/2011/page_91.pdf-2,"[{'score': 1.335734248161316, 'ind': 'table_3'...",[],"[{'score': 1.335734248161316, 'ind': 'table_3'...","[{'score': -0.22396248579025202, 'ind': 'text_..."

In [24]:
df_val.sample(2)

,pre_text,post_text,filename,table_ori,table,qa,id,table_retrieved,text_retrieved,table_retrieved_all,text_retrieved_all
298,"[note 6 : inventories we use the last-in , fir...",[inventories valued under the lifo method comp...,LLY/2018/page_63.pdf,"[[, 2018, 2017], [Finished products, $988.1, $...","[[, 2018, 2017], [finished products, $ 988.1, ...",{'question': 'what was the percent of the fini...,LLY/2018/page_63.pdf-3,"[{'score': 2.037463188171386, 'ind': 'table_1'...","[{'score': -1.236567258834838, 'ind': 'text_5'}]","[{'score': 2.037463188171386, 'ind': 'table_1'...","[{'score': -1.236567258834838, 'ind': 'text_5'..."
668,[future regulatory developments future regulat...,[.],AAL/2013/page_15.pdf,"[[, American, US Airways, Wholly-owned Regiona...","[[, american, us airways, wholly-owned regiona...",{'question': 'what is the ratio of the total f...,AAL/2013/page_15.pdf-1,"[{'score': 2.3906443119049072, 'ind': 'table_2...","[{'score': -1.870020508766174, 'ind': 'text_5'}]","[{'score': 2.3906443119049072, 'ind': 'table_2...","[{'score': -1.870020508766174, 'ind': 'text_5'..."

In [25]:
df_test.sample(2)

,pre_text,post_text,filename,table_ori,table,qa,id,table_retrieved,text_retrieved,table_retrieved_all,text_retrieved_all
517,[the grant date fair value of options is estim...,[total compensation expense for stock options ...,EMR/2017/page_78.pdf,"[[, Shares, Average Grant DateFair Value Per S...","[[, shares, average grant datefair value per s...",{'question': 'at the pace of 2017 how many yea...,EMR/2017/page_78.pdf-1,"[{'score': 0.22747954726219102, 'ind': 'table_...","[{'score': 0.7494400143623351, 'ind': 'text_27...","[{'score': 0.22747954726219102, 'ind': 'table_...","[{'score': 0.7494400143623351, 'ind': 'text_27..."
642,[2 0 1 9 a n n u a l r e p o r t1 6 performanc...,[this comparison assumes $ 100 was invested on...,JKHY/2019/page_18.pdf,"[[, 2014, 2015, 2016, 2017, 2018, 2019], [JKHY...","[[, 2014, 2015, 2016, 2017, 2018, 2019], [jkhy...",{'question': 'what was the percentage growth o...,JKHY/2019/page_18.pdf-1,"[{'score': 2.446802854537964, 'ind': 'table_3'...","[{'score': -0.550297379493713, 'ind': 'text_2'}]","[{'score': 2.446802854537964, 'ind': 'table_3'...","[{'score': -0.550297379493713, 'ind': 'text_2'..."

In [26]:
df = pd.concat(objs=[df_train, df_val, df_test], axis=0)
df = df.reset_index(drop=True)
len(df)

8281

In [27]:
df.columns

Index(['pre_text', 'post_text', 'filename', 'table_ori', 'table', 'qa', 'id',
       'table_retrieved', 'text_retrieved', 'table_retrieved_all',
       'text_retrieved_all'],
      dtype='object')

In [28]:
df = df[["pre_text", "table", "post_text", "id", "qa"]]
df

,pre_text,table,post_text,id,qa
0,[interest rate to a variable interest rate bas...,"[[, october 31 2009, november 1 2008], [fair v...",[fair value of forward exchange contracts afte...,ADI/2009/page_49.pdf-1,{'question': 'what is the the interest expense...
1,"[abiomed , inc ., and subsidiaries notes to co...","[[, number of shares ( in thousands ), weighte...",[the remaining unrecognized compensation expen...,ABMD/2012/page_75.pdf-1,"{'question': 'during the 2012 year , did the e..."
2,[the following table shows annual aircraft fue...,"[[year, gallons, average priceper gallon, airc...","[as of december 31 , 2018 , we did not have an...",AAL/2018/page_13.pdf-2,{'question': 'what was the total operating exp...
3,[the fair value of our grants receivable is de...,"[[( in millions ), dec 282013, dec 292012], [a...","[in the third quarter of 2013 , we sold our sh...",INTC/2013/page_71.pdf-4,{'question': 'what percentage of total cash an...
4,"[entergy louisiana , llc management's financia...","[[, amount ( in millions )], [2007 net revenue...",[the retail electric price variance is primari...,ETR/2008/page_313.pdf-3,{'question': 'what is the growth rate in net r...
...,...,...,...,...,...
8276,[performance graph the following graph compare...,"[[, 3/31/2007, 3/31/2008, 3/31/2009, 3/31/2010...",[this graph is not 201csoliciting material 201...,ABMD/2012/page_41.pdf-4,{'question': 'what is the roi of an investment...
8277,[payables that were reclassified as part of ou...,"[[contractual obligations millions of dollars,...",[[a] excludes capital lease obligations of $ 2...,UNP/2009/page_42.pdf-4,{'question': 'what percent of total material o...
8278,[note 17 2014 sales-type leases and financing ...,"[[( millions of dollars ), 2018, 2017, 2016], ...",[( a ) represents losses recognized upon our r...,BDX/2018/page_106.pdf-3,{'question': 'what is the average of total oth...
8279,"[table of contents hologic , inc ., notes to c...","[[cash portion of consideration, $ 2094800], [...","[source : hologic inc , 10-k , november 24 , 2...",HOLX/2009/page_127.pdf-4,"{'question': 'during the purchase , what was t..."
8280,[printing papers net sales for 2006 decreased ...,"[[in millions, 2006, 2005, 2004], [sales, $ 69...","[u.s ., uncoated papers net sales in 2006 were...",IP/2006/page_30.pdf-4,{'question': 'what was the sum of the european...

In [32]:
df.iloc[0]["qa"]

{'question': 'what is the the interest expense in 2009?',
 'program': 'divide(100, 100), divide(3.8, #0)',
 'exe_ans': 3.8}

In [31]:
KEEP_KEYS = {"question", "program", "exe_ans"}

df["qa"] = df["qa"].apply(lambda qa: {k: v for k, v in qa.items() if k in KEEP_KEYS})
df

,pre_text,table,post_text,id,qa
0,[interest rate to a variable interest rate bas...,"[[, october 31 2009, november 1 2008], [fair v...",[fair value of forward exchange contracts afte...,ADI/2009/page_49.pdf-1,{'question': 'what is the the interest expense...
1,"[abiomed , inc ., and subsidiaries notes to co...","[[, number of shares ( in thousands ), weighte...",[the remaining unrecognized compensation expen...,ABMD/2012/page_75.pdf-1,"{'question': 'during the 2012 year , did the e..."
2,[the following table shows annual aircraft fue...,"[[year, gallons, average priceper gallon, airc...","[as of december 31 , 2018 , we did not have an...",AAL/2018/page_13.pdf-2,{'question': 'what was the total operating exp...
3,[the fair value of our grants receivable is de...,"[[( in millions ), dec 282013, dec 292012], [a...","[in the third quarter of 2013 , we sold our sh...",INTC/2013/page_71.pdf-4,{'question': 'what percentage of total cash an...
4,"[entergy louisiana , llc management's financia...","[[, amount ( in millions )], [2007 net revenue...",[the retail electric price variance is primari...,ETR/2008/page_313.pdf-3,{'question': 'what is the growth rate in net r...
...,...,...,...,...,...
8276,[performance graph the following graph compare...,"[[, 3/31/2007, 3/31/2008, 3/31/2009, 3/31/2010...",[this graph is not 201csoliciting material 201...,ABMD/2012/page_41.pdf-4,{'question': 'what is the roi of an investment...
8277,[payables that were reclassified as part of ou...,"[[contractual obligations millions of dollars,...",[[a] excludes capital lease obligations of $ 2...,UNP/2009/page_42.pdf-4,{'question': 'what percent of total material o...
8278,[note 17 2014 sales-type leases and financing ...,"[[( millions of dollars ), 2018, 2017, 2016], ...",[( a ) represents losses recognized upon our r...,BDX/2018/page_106.pdf-3,{'question': 'what is the average of total oth...
8279,"[table of contents hologic , inc ., notes to c...","[[cash portion of consideration, $ 2094800], [...","[source : hologic inc , 10-k , november 24 , 2...",HOLX/2009/page_127.pdf-4,"{'question': 'during the purchase , what was t..."
8280,[printing papers net sales for 2006 decreased ...,"[[in millions, 2006, 2005, 2004], [sales, $ 69...","[u.s ., uncoated papers net sales in 2006 were...",IP/2006/page_30.pdf-4,{'question': 'what was the sum of the european...

In [39]:
df.to_json("FinQA_processed.json", orient="records", indent=2, force_ascii=False)